- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/identities/components/index.ts
- pkg/client/src/app/pages/repositories/Git.tsx
- pkg/client/src/app/pages/repositories/Mvn.tsx
- pkg/client/src/app/pages/repositories/Svn.tsx
Add api support for mvn,svn, & git settings configuration from the repositories nav section.
> Settings api

- README.md
- entrypoint.sh
- pkg/client/package.json
- pkg/server/setupProxy.js
Update following 
* https://github.com/konveyor/tackle2-operator/issues/7
* https://github.com/konveyor/tackle2-operator/issues/8
> Update cluster env variables

- pkg/client/src/app/api/rest.tsx
Previous PR https://github.com/konveyor/tackle2-ui/pull/10 broke HAL+JSON requests because of Javascript property shorthand value behavior.
> Fix Headers for HAL+JSON

- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
- pkg/client/src/app/pages/applications/applications.tsx
- pkg/client/src/app/pages/controls/controls.tsx
- pkg/client/src/app/shared/components/FilterToolbar/FilterToolbar.tsx
- pkg/client/src/app/shared/hooks/useFilterState.ts
Helps address https://github.com/konveyor/tackle2-ui/issues/17
> No implicity any for filters and tabs

- pkg/client/tsconfig.json
Fixes https://github.com/konveyor/tackle2-ui/issues/17
> tsconfig.json use strict type check

- pkg/client/__mocks__/JBoss5-web-class-loading.windup.xml
- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/analysis-mode.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/select-card.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/custom-rules.css
- pkg/client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/options.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/review.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/scope.css
- pkg/client/src/app/pages/applications/analysis-wizard/scope.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Populate task data from tasks and scope values to run analysis accordingly
All steps are handled but custom rules is not finished.
> Analysis Wizard: All steps but options to allow task creation

- README.md
This badge will display the status of container builds in quay
> Add quay.io status badge to repo

- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- Update repository fields on the add app modal form 
- Add conditional validation for the application repo url field
- Disables binary fields until the api field exists for binary.
> Update add app modal

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- Fixes update app modal initial value load 
- Fixes a bug with url validation not matching what is expected by the api
> App edit modal changes

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- Allow URL without branch or path but check valid url if any input exists for url field.
> Update repo url validation

- pkg/client/src/app/pages/proxies/proxy-form.tsx
- Show selected identity when loading existing modified proxies 
- Update associated identity when de-selecting switch for identities
> Fix proxy identity initial values

- pkg/client/src/app/pages/proxies/proxies.tsx
- pkg/client/src/app/pages/proxies/proxy-form.tsx
- pkg/client/src/app/queries/proxies.ts
Previously, the save button was not changing when updating values/saving. This was in part due to proxies not being properly refetched after a mutation.
> Fix proxy save button disabled state when value changes 

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/queries/common.ts
- pkg/client/src/app/queries/tasks.ts
Applications without a task "Scheduled" or "In progress" can be analyzed.
Applications with a task "Scheduled" or "In progress" can be cancelled.
> Filter Apps for analysis and cancellation

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/axios-config/apiInit.ts
- pkg/client/src/app/axios-config/index.ts
- pkg/client/src/index.tsx
- pkg/server/setupProxy.js
- "/api/pathfinder" => "/pathfinder" 
- "/api" => "/hub"
> Proxy: Remove /api path

- pkg/client/package-lock.json
- pkg/client/package.json
- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/identities/components/identity-form.tsx
- pkg/client/src/app/pages/identities/components/schema.xsd
- pkg/client/src/app/pages/identities/components/settings-example.xml
- pkg/client/src/app/shared/components/simple-select/simple-select.tsx
- pkg/client/src/app/shared/components/simple-select/single-select-fetch-optionvalue-formik-field.tsx
- pkg/client/src/app/utils/model-utils.tsx
- Converting identities form to use react-hook-form library to eliminate a few bugs I am seeing with form validation. 
- Includes support for tackle2-hub change for showing edited values on identity.
> Convert identities to hook form library 

- pkg/client/src/app/api/rest.tsx
- Removes HAL headers for imports and dependencies.
> Remove legacy headers

- pkg/client/src/app/pages/applications/applications.tsx
Fixes: https://issues.redhat.com/browse/TACKLE-418
> Fix application redirect route load

- pkg/client/src/app/pages/applications/components/application-tags/application-tags.tsx
- Show correct tag colors in app expanded view.
https://issues.redhat.com/browse/TACKLE-420
> Tag color fix for app expanded view

- pkg/client/public/locales/en/translation.json
- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx
- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/queries/applications.ts
- pkg/client/src/app/queries/identities.ts
- pkg/client/src/app/queries/taskgroups.ts
- pkg/client/src/app/queries/tasks.ts
- Use React query for custom rules files upload
- Consolidate analysis queries and prepare for `queryClient.invalidateQuery()` and `queryClient.setQueryData()` for handling data synchronization
- Also benefit from type inference
> Analysis: custom rules uploadfile with cleaner queries

- pkg/client/src/app/layout/AppAboutModal/AppAboutModal.tsx
- pkg/client/src/app/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-423
- Set version to 2.0
- Updated Copyright to 2022
> About: Set Version 2.0

- pkg/client/src/app/pages/controls/controls.tsx
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-438
- Highlight current active tab
> Controls: set active tab

- pkg/client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-437
- Use the correct i8n reference
> Use correct stakeholderGroup term

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- pkg/client/src/app/queries/applications.ts
- When attempting to clear the URL field, the user would get a silent failure. This fixes this and fixes the refetch delay for app loading after mutation.
> Convert applications to react-query and fix url field clear bug

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- pkg/client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx
- Spreads app properties to the payload when attaching a credential to an application
- Fixes credential properties overwritten in app edit form
> Fix application property overwriting when adding credentials 

- pkg/client/src/app/pages/repositories/Mvn.tsx
https://issues.redhat.com/browse/TACKLE-440
> Repositories: Fix mispelled word

- pkg/client/src/app/context/LocalStorageContext.tsx
- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
https://issues.redhat.com/browse/TACKLE-439
> Persist persona on reload

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/queries/applications.ts
- Adds delete mutation for apps & migrates assessment view to use query fetch
> Fix delete application not showing up in table

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
Alleviate the validation for the application mode (SetMode)
> Analysis Mode validation: do not check for Creds

- pkg/client/src/app/layout/SidebarApp/SidebarApp.css
- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-470
> Fix css leak

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/pages/applications/applicationsFilter.ts
Adds shared filter logic across analysis/assessments. Also fixes broken assessments application table filter.
> Add shared filter for applications tables

- pkg/client/src/app/pages/controls/stakeholders/stakeholders.tsx
https://issues.redhat.com/browse/TACKLE-449
> Update stakeholders to stakeholder groups

- pkg/client/src/app/pages/identities/identities.tsx
[Credentials : Sorting on Type and Name field does not work](https://issues.redhat.com/browse/TACKLE-431) 
https://issues.redhat.com/browse/TACKLE-429
> Fix identities sort and filter

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- pkg/client/src/app/pages/identities/components/identity-form.tsx
- pkg/client/src/app/utils/utils.ts
- Also adds a util function to replicate this functionality across other types
[Assessment : Application with duplicate name give Error 409](https://issues.redhat.com/browse/TACKLE-474) - New bug
> Duplicate name check for applications

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/pages/applications/applicationsFilter.ts
https://issues.redhat.com/browse/TACKLE-477
> Fix application sorting

- pkg/client/src/app/pages/controls/controls.tsx
- pkg/client/src/app/pages/controls/tags/tags.tsx
https://issues.redhat.com/browse/TACKLE-441 
- Shows correct controls tab when reloading
- Fixes color filter issue in tags table
> Fix tab loading bug and color filter bug

- pkg/client/src/app/shared/components/app-table/app-table.css
- pkg/client/src/app/shared/components/app-table/app-table.tsx
- pkg/client/src/app/shared/components/app-table/tests/__snapshots__/app-table.test.tsx.snap
https://issues.redhat.com/browse/TACKLE-434
> Remove header expand icon bug

- pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
https://issues.redhat.com/browse/TACKLE-478
> Fix import filter and sort

- pkg/client/src/app/pages/controls/job-functions/job-functions.tsx
- pkg/client/src/app/pages/controls/stakeholders/stakeholders.tsx
https://issues.redhat.com/browse/TACKLE-432
> Stakeholder filter fixes

- pkg/client/public/locales/en/translation.json
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-487
> Stakeholders group

- pkg/client/public/locales/en/translation.json
- pkg/client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx
- pkg/client/src/app/queries/stakeholders.ts
https://issues.redhat.com/browse/TACKLE-451
> Stakeholders duplicate check

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/controls/tags/components/tag-form/tag-form.tsx
- pkg/client/src/app/queries/tags.ts
[Tags: Tags unique constraint validation](https://issues.redhat.com/browse/TACKLE-445)
> Duplicate tag check fix. Adds ui validation

- pkg/client/src/app/pages/applications/applicationsFilter.ts
https://issues.redhat.com/browse/TACKLE-368
> Filter apps by credentials

- pkg/client/src/app/pages/controls/stakeholder-groups/components/stakeholder-group-form/stakeholder-group-form.tsx
https://issues.redhat.com/browse/TACKLE-486
> Stakeholder groups duplicate fix

- pkg/client/src/app/pages/controls/business-services/components/business-service-form/business-service-form.tsx
- pkg/client/src/app/shared/components/simple-select/single-select-fetch-optionvalue-formik-field.tsx
https://issues.redhat.com/browse/TACKLE-484
> Allow clearable select box via prop

- pkg/client/src/app/pages/applications/applicationsFilter.ts
https://issues.redhat.com/browse/TACKLE-372
https://issues.redhat.com/browse/TACKLE-376
> Filter apps by repository type

- pkg/client/src/app/pages/applications/applicationsFilter.ts
https://issues.redhat.com/browse/TACKLE-383
> Filter by associated binary

- pkg/client/src/app/pages/controls/business-services/business-services.tsx
https://issues.redhat.com/browse/TACKLE-483
> Disable deleting associated business services

- pkg/client/src/app/pages/controls/job-functions/components/job-function-form/job-function-form.tsx
https://issues.redhat.com/browse/TACKLE-494
> Duplicate check for job function name

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/pages/applications/applicationsFilter.ts
https://issues.redhat.com/browse/TACKLE-504
> Add tags to applications filtering

- pkg/client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx
Fixes https://issues.redhat.com/browse/TACKLE-519
> Fix reports screen not showing application data

- pkg/client/src/app/pages/reports/application-selection-context.tsx
https://issues.redhat.com/browse/TACKLE-452
> Fix assessment sort by risk

- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
https://issues.redhat.com/browse/TACKLE-520
> Add kind to app repos

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
https://issues.redhat.com/browse/TACKLE-530
> Analysis wizard: truncate applications list

- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/components/application-analysis-status.tsx
```
const taskStateToAnalyze: Map<TaskState, AnalysisState> = new Map([
["not supported", "Canceled"],
["Created", "Scheduled"],
["Succeeded", "Completed"],
["Failed", "Failed"],
["Running", "InProgress"],
["No task", "NotStarted"],
["Pending", "Scheduled"],
["Postponed", "Scheduled"],
["Ready", "Scheduled"],
]);
```
> Add Pending and Postponed states to TaskState

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx
- pkg/client/src/app/pages/applications/components/application-list-expanded-area/application-list-expanded-area-analysis.tsx
- pkg/client/src/app/queries/applications.ts
https://issues.redhat.com/browse/TACKLE-514
> Fix mvn creds not updating

- pkg/client/src/app/pages/proxies/proxies-validation-schema.ts
- pkg/client/src/app/pages/proxies/proxy-form.tsx
https://issues.redhat.com/browse/TACKLE-505
> Proxy form save button fix

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/applications/manage-imports-details/manage-imports-details.tsx
- pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
- pkg/client/src/app/queries/imports.ts
- Add refresh interval for `importSummaries`, to avoid reloading page for latest
- Displays import report (the page was freezing) 
- Fix delete warning message
https://issues.redhat.com/browse/TACKLE-530
https://issues.redhat.com/browse/TACKLE-515
> Fix imports

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/utils.ts
https://issues.redhat.com/browse/TACKLE-508
> Analysis wizard: triage applications upon analysis mode 

- pkg/client/public/locales/en/translation.json
- pkg/client/public/locales/es/translation.json
- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/components/application-list-expanded-area/application-list-expanded-area-analysis.tsx
https://issues.redhat.com/browse/TACKLE-551
> Application inventory analysis: Show task details

- pkg/client/src/app/pages/controls/tags/components/tag-type-form/tag-type-form.tsx
https://issues.redhat.com/browse/TACKLE-493
> Duplicate check for TagType

- pkg/client/public/locales/en/translation.json
- pkg/client/src/app/pages/controls/controls.tsx
https://issues.redhat.com/browse/TACKLE-487
> Stakeholder group is singular

- pkg/client/package-lock.json
- pkg/client/package.json
- pkg/client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- pkg/client/src/app/shared/components/simple-select/tests/__snapshots__/select-entity.test.tsx.snap
PF upload file component is still under Beta and is changing along so we need to keep up until stable.
There are also ongoing issues which are depending on this one as they benefit from its latest.
> Bump PF upload file component

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx
https://issues.redhat.com/browse/TACKLE-547
> Reset artifact when removing upload binary

- entrypoint.sh
- Syntax error causing ui pod to crash at entrypoint.sh
> Fix build error

- Dockerfile
- pkg/client/package.json
- pkg/server/helpers.js
- pkg/server/index.js
> Update index.html logic

- pkg/client/src/app/Constants.ts
- pkg/client/src/app/common/KeycloakProvider.tsx
- pkg/client/src/app/common/RouteWrapper.tsx
- pkg/client/src/app/layout/HeaderApp/HeaderApp.tsx
- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
- pkg/client/src/app/rbac.ts
- Follow up to single user changes: 
- Allows admin view when auth is not enabled
> Allow admin view if no auth

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
Removes old mode variable which clashes which new one.
https://issues.redhat.com/browse/TACKLE-562
https://issues.redhat.com/browse/TACKLE-570
> Remove old mode

- pkg/client/public/locales/en/translation.json
- pkg/client/public/locales/es/translation.json
- pkg/client/src/app/shared/components/toolbar-bulk-selector/toolbar-bulk-selector.tsx
Remove unused text in toolbar selector
> Children render warning resulting from unused text

- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/application-review/components/application-assessment-summary-table/application-assessment-summary-table.tsx
- pkg/client/src/app/pages/identities/identities.tsx
- pkg/client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-452?filter=allopenissues
> Adds sorting for risks in summary table

- entrypoint.sh
- Correct misleading variable names on error condition
> Fix entrypoint error condition variable names

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
https://issues.redhat.com/browse/TACKLE-544
Pending backend support
> Add support for git urls

- pkg/client/src/app/layout/SidebarApp/SidebarApp.css
- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
https://issues.redhat.com/browse/TACKLE-417
> Cleanup sidenav css

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
https://issues.redhat.com/browse/TACKLE-585
> Update regex for repo URL 

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
> Allow all actions if auth not required

- pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- pkg/client/src/app/queries/taskgroups.ts
https://issues.redhat.com/browse/TACKLE-575
> Add axios error display for file upload

- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
https://issues.redhat.com/browse/TACKLE-586
> Reset localstorage on fresh login

- pkg/client/src/app/api/rest.tsx
https://issues.redhat.com/browse/TACKLE-469
> Wire up bulk copy reviews api

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
(cherry picked from commit 11e6bf5d8c54259aaf7d88e22370d1c61def8bf2)
> [Backport] Single application analysis: no next unless artifact (#199)

- pkg/client/src/app/pages/controls/tags/tags.tsx
(cherry picked from commit c53857b90e0c6d6c25fcd863653324a79eef69ea)
> [Backport] Add rbac rules for tag page (#200)

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
Reverts konveyor/tackle2-ui#203
> Revert "[Backport] Single application analysis: no next unless artifact (#199)"

- pkg/client/src/app/pages/controls/tags/tags.tsx
Reverts konveyor/tackle2-ui#204
> Revert "[Backport] Add rbac rules for tag page (#200)"

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
This reverts commit 11e6bf5d8c54259aaf7d88e22370d1c61def8bf2.
> Revert "Single application analysis: no next unless artifact (#199)"

- pkg/client/src/app/common/RouteWrapper.tsx
- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
https://issues.redhat.com/browse/TACKLE-606
> Redirect to /applications on first load

- pkg/client/src/app/pages/applications/applicationsFilter.ts
https://issues.redhat.com/browse/TACKLE-582
https://issues.redhat.com/browse/TACKLE-584
https://issues.redhat.com/browse/TACKLE-612
> Update string check for repo type

- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/rbac.ts
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-597
https://issues.redhat.com/browse/TACKLE-602
> No credential management as a migrator

- pkg/client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx
https://issues.redhat.com/browse/TACKLE-599
> Source credentials are not required

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/repositories/Mvn.tsx
- pkg/client/src/app/queries/volumes.ts
- Adds a new hook to handle POST/FETCH for clean functionality
- Adds a confirmation dialog modal to confirm the clean action
> Poll tasks for clean completion

- pkg/client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
https://issues.redhat.com/browse/TACKLE-561
> Include custom rules targets in options

- pkg/client/src/app/App.tsx
- pkg/client/src/app/common/KeycloakProvider.tsx
- pkg/client/src/app/queries/cookies.ts
- pkg/client/src/index.tsx
https://issues.redhat.com/browse/TACKLE-601
> Fix cookie auto update

- pkg/client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
- pkg/client/src/app/utils/utils.ts
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-573
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-576
> Add description and count sorting for stakeholder groups

- pkg/client/src/app/layout/HeaderApp/SSOMenu.tsx
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-613
> TACKLE-613: Reset local storage on logout for persona storage

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/queries/applications.ts
- pkg/client/src/app/queries/assessments.ts
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-611
> TACKLE-611: Cascade assessment delete when app is deleted

- pkg/client/src/app/pages/identities/components/identity-form.tsx
Resolves the rest of https://issues.redhat.com/browse/TACKLE-536 (partially resolved by https://github.com/konveyor/tackle2-ui/pull/221)
> TACKLE-536: Correct validation error when Maven settings field is blank

- pkg/client/src/app/shared/containers/application-dependencies-form/application-dependencies-form.tsx
https://issues.redhat.com/browse/TACKLE-492?
> TACKLE-492: Prevent mapping to existing conflicting dependency

- pkg/client/src/app/pages/identities/identities.tsx
https://issues.redhat.com/browse/TACKLE-534
> TACKLE-534: Add dependency check for deleting credentials

- pkg/client/src/app/layout/HeaderApp/SSOMenu.tsx
https://issues.redhat.com/browse/TACKLE-627
> TACKLE-627: Wait for logout before clearing localstorage

- pkg/client/src/app/pages/applications/components/application-list-expanded-area/application-list-expanded-area-analysis.tsx
https://issues.redhat.com/browse/TACKLE-620
> TACKLE-620: Add failed text for analysis status

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
https://issues.redhat.com/browse/TACKLE-632
> TACKLE-632: Add tooltip and icon for overwriting analysis

- pkg/client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx
https://issues.redhat.com/browse/TACKLE-542
> TACKLE-542: Refactor identified risks table to use FilterToolbar

- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
https://issues.redhat.com/browse/TACKLE-592
> TACKLE-592: Remove manage creds from assessment table

- pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
https://issues.redhat.com/browse/TACKLE-563
> TACKLE-563: Clear filters on manage imports page

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
https://issues.redhat.com/browse/TACKLE-636
> TACKLE-636: Convert to conditional tooltip

- pkg/client/public/locales/en/translation.json
- pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
Quick fix for dev envs. Long term solution still pending on why this may be happening.
> Fix i18n problematic term

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
https://issues.redhat.com/browse/TACKLE-550
> TACKLE-550: Prevent duplicate rules files

- pkg/client/src/app/pages/applications/analysis-wizard/set-options.tsx
https://issues.redhat.com/browse/TACKLE-600
> TACKLE-600: Add missing targets

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/pages/applications/applicationsFilter.ts
- pkg/client/src/app/shared/components/FilterToolbar/FilterToolbar.tsx
- pkg/client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx
- pkg/client/src/app/shared/components/FilterToolbar/SelectFilterControl.tsx
- pkg/client/src/app/shared/components/app-table-with-controls/app-table-with-controls.tsx
https://issues.redhat.com/browse/TACKLE-506
> TACKLE-506: Convert multiselect filter to use checkbox and inline search, use multiselect for enumerable fields in applications table

- entrypoint.sh
- pkg/client/src/app/api/rest.tsx
- pkg/server/setupProxy.js
- Route all pathfinder routes through the hub
> Route pathfinder urls to hub api

- pkg/client/src/app/pages/controls/tags/components/tag-form/tag-form.tsx
https://issues.redhat.com/browse/TACKLE-648
> TACKLE-648: Fix initial value for tag edit

- pkg/client/src/app/layout/HeaderApp/SSOMenu.tsx
Backports #288 (for https://issues.redhat.com/browse/TACKLE-659)
> [Backport - v2.0.0] TACKLE-659: Ensure selected persona will get cleared on logout

- pkg/client/src/app/pages/proxies/proxy-form.tsx
https://issues.redhat.com/browse/TACKLE-679
> TACKLE-679: Add placeholder text for proxy excluded text area

- pkg/client/src/app/layout/SidebarApp/SidebarApp.css
- pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx
Resolves https://issues.redhat.com/browse/TACKLE-417
After discussion in Slack we determined that the design of the perspective selector should match the design guidelines found here: https://www.patternfly.org/v4/components/context-selector/design-guidelines#recommended-placement-0
Reference design:
It appears that the PF React components and CSS are not currently aligned with this design, so I've gotten as close as possible to this design in the meantime with custom CSS. I used as many PF CSS variables as possible so colors will stay up to date if these colors change in future versions. We may want to revisit this if the components change in PatternFly later on.
New screenshots:
> TACKLE-417: Change style of perspective selector to match PatternFly design guidelines

- pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- pkg/client/src/app/queries/taskgroups.ts
https://issues.redhat.com/browse/TACKLE-646
> TACKLE-646: Next enable sync with api call response

- pkg/client/src/app/pages/identities/components/identity-form.tsx
https://issues.redhat.com/browse/TACKLE-621
> TACKLE-621: Add check for existing encrypted file before showing encrypted placeholder

- pkg/client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
- pkg/client/src/app/pages/controls/stakeholders/stakeholders.tsx
- pkg/client/src/app/queries/stakeholdergoups.ts
- pkg/client/src/app/queries/stakeholders.ts
https://issues.redhat.com/browse/TACKLE-635
> TACKLE-635: Update stakeholder/stakeholder groups to use react query

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/queries/tasks.ts
https://issues.redhat.com/browse/TACKLE-558
> TACKLE-558: Task cancelation

- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
- Remove nested form elements in favor of a div with form styling to fix expandable form style issues.
> Address nested form warning

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
This is a follow-up to https://github.com/konveyor/tackle2-ui/pull/313
> Task in Pending state is cancellable

- pkg/client/src/app/api/rest.tsx
- pkg/client/src/app/queries/applications.ts
- pkg/client/src/app/shared/containers/application-dependencies-form/application-dependencies-form.tsx
- pkg/client/src/app/shared/hooks/useFetchApplicationDependencies/useFetchApplicationDependencies.ts
https://issues.redhat.com/browse/TACKLE-637?filter=12396745
> TACKLE-637: Update list exclusion logic

- pkg/client/public/locales/en/translation.json
- pkg/client/public/locales/es/translation.json
- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/review.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-options.tsx
https://issues.redhat.com/browse/TACKLE-687
Requires https://github.com/konveyor/tackle2-addon-windup/pull/42
> TACKLE-687: Advanced Option: DIVA

- pkg/client/src/app/pages/applications/components/import-applications-form/import-applications-form.tsx
Adds createEntities functionality to the UI. HUB PR: https://github.com/konveyor/tackle2-hub/pull/123
> TACKLE-691: Add create entities checkbox to csv import

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/queries/applications.ts
Remove UI assessment delete cascading logic in favor of newly merged API code. Hub pull request: https://github.com/konveyor/tackle2-hub/pull/125
> Remove cascading assessment delete

- pkg/client/src/app/api/models.tsx
- pkg/client/src/app/pages/applications/components/application-analysis-status.tsx
https://issues.redhat.com/browse/TACKLE-558
> TACKLE-558: Add canceled state for Analysis

- pkg/client/public/locales/en/translation.json
- pkg/client/public/locales/es/translation.json
- pkg/client/src/app/layout/AppAboutModal/AppAboutModal.tsx
- pkg/client/src/app/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap
https://issues.redhat.com/browse/TACKLE-699
> TACKLE-699: IconLibrary for about modal

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx
Fixes:  https://issues.redhat.com/browse/TACKLE-714
> Fix broken object reference for custom rule files

- pkg/client/src/app/layout/AppAboutModal/AppAboutModal.tsx
- pkg/client/src/app/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap
> TACKLE-698 - About: Version 2.1

- pkg/client/src/app/shared/components/simple-select/simple-select.tsx
- pkg/client/src/app/shared/components/simple-select/tests/__snapshots__/select-entity.test.tsx.snap
- pkg/client/src/app/shared/containers/application-dependencies-form/application-dependencies-form.tsx
- pkg/client/src/app/shared/containers/application-dependencies-form/select-dependency.tsx
> [Backport 2.1] - Add custom IDs for select toggle for QE

- pkg/client/public/locales/en/translation.json
- pkg/client/public/locales/es/translation.json
- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/queries/applications.ts
This PR adds delete and bulk delete notifications for applications.
> TACKLE-676: Add application delete / bulk delete notification

- pkg/client/config/webpack.prod.js
- pkg/client/public/index.html.ejs
https://issues.redhat.com/browse/TACKLE-713
> TACKLE-713: Fix favicon

- pkg/client/config/webpack.prod.js
- pkg/client/public/index.html.ejs
* Fix favicon
* Cleanup old dependency
> [Backport 2.1] - TACKLE-713 - Fix favicon

- pkg/client/src/app/pages/controls/tags/tags.tsx
Add back in delete functionality which was inadvertently removed.
> TACKLE-734: Re-add missing delete tag functions

- pkg/client/src/app/pages/controls/tags/tags.tsx
- pkg/client/src/app/shared/hooks/useSortState.ts
https://issues.redhat.com/browse/TACKLE-680
> TACKLE-680: Fix locale sort support & numeric sort support

- pkg/client/src/app/pages/controls/tags/tags.tsx
- pkg/client/src/app/shared/hooks/useSortState.ts
* Fix locale sort support & numeric sort support
* cleanup
> [Backport 2.1.0] - TACKLE-680: Fix locale sort support & numeric sort support 

- pkg/client/src/app/pages/controls/tags/tags.tsx
- pkg/client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx
* WIP tag filter
* reorder
* Update to search both tag type and tag name
* cleanup
* Move to a more maintainable else pattern
> [Backport - 2.1.0] - Tackle-689: Tag /Tag type name filter fix (

- pkg/client/src/app/shared/hooks/usePaginationState.ts
https://issues.redhat.com/browse/TACKLE-694
> TACKLE-694: Fix items per page bug

- pkg/client/src/app/pages/proxies/proxy-form.tsx
- pkg/client/src/app/queries/applications.ts
- pkg/client/src/app/queries/businessservices.ts
- pkg/client/src/app/queries/identities.ts
- pkg/client/src/app/queries/imports.ts
- pkg/client/src/app/queries/jobfunctions.ts
- pkg/client/src/app/queries/proxies.ts
- pkg/client/src/app/queries/stakeholdergoups.ts
- pkg/client/src/app/queries/stakeholders.ts
- pkg/client/src/app/queries/tags.ts
- pkg/client/src/app/queries/volumes.ts
RE: https://github.com/konveyor/tackle2-ui/pull/347
> Favor inferred query types & remove detrimental type overrides

- pkg/client/src/app/pages/proxies/proxy-form.tsx
- pkg/client/src/app/queries/applications.ts
- pkg/client/src/app/queries/businessservices.ts
- pkg/client/src/app/queries/identities.ts
- pkg/client/src/app/queries/imports.ts
- pkg/client/src/app/queries/jobfunctions.ts
- pkg/client/src/app/queries/proxies.ts
- pkg/client/src/app/queries/stakeholdergoups.ts
- pkg/client/src/app/queries/stakeholders.ts
- pkg/client/src/app/queries/tags.ts
- pkg/client/src/app/queries/volumes.ts
* Remove detrimental type overrides
* Assert error type
> [Backport 2.1.0] - Favor inferred query types & remove detrimental type overrides (#352)

- pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx
- pkg/client/src/app/pages/applications/application-review/components/application-assessment-summary-table/components/select-risk-filter/select-risk-filter.tsx
- pkg/client/src/app/pages/applications/components/application-form/__tests__/application-form.test.tsx
- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
Add dropdown toggle selectors for QE
> Add missing selectors for dropdown toggles

- pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx
- pkg/client/src/app/pages/applications/application-review/components/application-assessment-summary-table/components/select-risk-filter/select-risk-filter.tsx
- pkg/client/src/app/pages/applications/components/application-form/__tests__/application-form.test.tsx
- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
* Add missing selectors for dropdown toggles
* Update to IDs for QE
* Update Ids for QE
> [Backport 2.1.0] -  QE selectors

- pkg/client/public/locales/en/translation.json
- pkg/client/public/locales/es/translation.json
- pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
Application requires business service but does not in 1.x.
https://issues.redhat.com/browse/TACKLE-695
> TACKLE-695: Change application form validation 

- .github/workflows/ci-actions.yml
- pkg/client/package.json
- pkg/client/src/app/pages/controls/business-services/business-services.tsx
- pkg/client/src/app/pages/controls/job-functions/job-functions.tsx
- pkg/client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
- pkg/client/src/app/pages/controls/stakeholders/stakeholders.tsx
- pkg/client/src/app/pages/identities/identities.tsx
- pkg/client/src/app/pages/reports/components/adoption-candidate-graph/adoption-candidate-graph.tsx
- pkg/client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx
- pkg/client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx
- pkg/client/src/app/shared/hooks/useSortState.ts
Updates the github actions ci file to fix an issue that was causing builds to be skipped & not checked with typescript. 
Fixes resulting typescript failures that are present due to the transpiler actually running
> Fix Typescript errors resulting from TS not turned on for production builds.

- pkg/client/src/app/common/rbac-utils.tsx
https://issues.redhat.com/browse/TACKLE-756
> TACKLE-756: Flip check access all logic

- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/pages/applications/components/application-list-expanded-area/application-list-expanded-area.tsx
- pkg/client/src/app/pages/applications/components/application-list-expanded-area/application-risk.tsx
- Adds assessment to dependency array for fetch risks useEffect function.
> TACKLE-759: Fix fetch risks not being called after assessment data change

- pkg/client/src/app/Routes.tsx
> Fixes broken redirect for undefined routes

- client/src/app/pages/applications/analysis-wizard/set-options.tsx
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
https://issues.redhat.com/browse/TACKLE-793
> Updates OpenJDK and OracleJDK targets

- client/src/typings.d.ts
- server/helpers.js
This a follow-up from https://github.com/konveyor/tackle2-ui/pull/406
> Add PROFILE varenv to local server

- pkg/client/src/app/pages/applications/analysis-wizard/set-options.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-targets.tsx
(cherry picked from commit fb442188770439baba7370979af8d2ebe35c678e)
> [backport - v2.1.1] Tackle-793: Updates OpenJDK and OracleJDK targets (#405)

- pkg/client/src/typings.d.ts
- pkg/server/helpers.js
Signed-off-by: Gilles Dubreuil <gilles@redhat.com>
(cherry picked from commit 4d1bf33bb4ac038baeceaa3edc733e7bcd8ab8c7)
> [backport - v2.1.1] Tackle-794: Add Azure target with 3rd party filtering (#423)

- client/src/app/pages/applications/analysis-wizard/targets.ts
https://issues.redhat.com/browse/TACKLE-793
> Update OpenJDK and OracleJDK targets overidden by PR406

- pkg/client/src/app/pages/applications/analysis-wizard/set-options.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-targets.tsx
(cherry picked from commit fb442188770439baba7370979af8d2ebe35c678e)
> [backport - v2.1.1] Tackle-793: Updates OpenJDK and OracleJDK targets (#405) 

- pkg/client/src/typings.d.ts
- pkg/server/helpers.js
(cherry picked from commit 4d1bf33bb4ac038baeceaa3edc733e7bcd8ab8c7)
> [backport - v2.1.1] Tackle-794: Add PROFILE varenv to local server (#423)

- pkg/client/src/app/pages/applications/analysis-wizard/targets.ts
(cherry picked from commit f778088f9600b1dc71eafc3a25a444fd67d40d96)
> [backport - v2.1.1] Tackle-793: Update OpenJDK and OracleJDK targets overidden by PR406 (#427)

- entrypoint.sh
> [Backport v2.1.2] Create CA certs bundle (#447)

- pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
- pkg/client/src/app/pages/controls/business-services/business-services.tsx
- pkg/client/src/app/pages/controls/job-functions/job-functions.tsx
- pkg/client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
- pkg/client/src/app/pages/controls/stakeholders/stakeholders.tsx
- pkg/client/src/app/pages/controls/tags/tags.tsx
- pkg/client/src/app/pages/identities/identities.tsx
- pkg/client/src/app/shared/hooks/usePaginationState.ts
Backports #451 (https://issues.redhat.com/browse/TACKLE-772)
> [Backport v2.1.2] TACKLE-772: On deleting a table item, remain on current page unless we deleted the last item on the page (#451)

- .github/workflows/ci-actions.yml
Backports #455 so that these workflows will now take effect on future PRs targeting v2.1.2
> [Backport v2.1.2] Run CI checks on PRs and merges to release branches

- pkg/client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
Backports #448 (https://issues.redhat.com/browse/TACKLE-822)
> [Backport V2.1.2] TACKLE-822: Add tags filter to copy assessment form 

- pkg/client/src/app/pages/applications/applicationsFilter.ts
Backport #429 (https://issues.redhat.com/browse/TACKLE-820)
> [Backport v2.1.2] TACKLE-820: Grab the business service name to pass to the filter (#429)

- pkg/client/package-lock.json
- pkg/client/package.json
> [Backport v2.1.2] Bump keycloak-js to 18.0.1 (#445)

- client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
- Adds the missing description filter to the copy assessment / copy assessment and reviews table
> TACKLE-822: Add description filter to copy assessment table

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/set-scope.tsx
https://issues.redhat.com/browse/TACKLE-843
> TACKLE-843: Move excluded packages boolean to form state

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-scope.tsx
> [Backport 2.1.2] TACKLE-843: Move excluded packages boolean to form state

- pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- pkg/client/src/app/pages/applications/analysis-wizard/set-options.tsx
Backports #468 (https://issues.redhat.com/browse/TACKLE-844)
> [Backport v2.1.2] - TACKLE-844: Add validation to set options (#468)

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/env.ts
- client/src/app/layout/AppAboutModal/AppAboutModal.tsx
- client/src/app/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap
https://issues.redhat.com/browse/TACKLE-851
> TACKLE-851: Use env vars on about modal for brandType and version

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- Currently we are showing the user an error notification when submitting an application for analysis. This should be an info notification.
> [Bug Fix] Update notification type for analysis submission

- client/src/app/env.ts
- server/helpers.js
> TACKLE-851: Fix version in about modal

- pkg/server/helpers.js
> [Backport v2.1.2] TACKLE-851: Fix version in about modal 

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/set-mode.tsx
- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- Updates submit to use correct taskgroup object [here](https://github.com/konveyor/tackle2-ui/pull/535/files#diff-768d2fa8006b961ba427e7da8744a278b3f79b1e93f362f9f86b190a04b75ff9R280)
- Removes the unnecessary duplicate task group initialization on mode change & some other changes for clarity
> Fix broken analysis & remove unused taskgroup initialization on mode change 

- client/src/app/pages/identities/identities.tsx
> Bug Fix: Fix broken template string with delete confirmation for creds

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/repositories/Mvn.tsx
Follow up from https://github.com/konveyor/tackle2-ui/pull/554
> feat: Adjust button space and tooltip when RWX is disabled 

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/controls/tags/components/tag-form/tag-form.tsx
https://issues.redhat.com/browse/TACKLE-948
> bug: Fix message and use i18n

- client/src/app/queries/risks.ts
Fixes the 400 Bad Request error produced on the report page.
> bug: Return empty list when no applications are passed

- client/src/app/pages/repositories/Mvn.tsx
- Adds in missing spacer for the clear repository button
- Adds an ID for QE testing
> css: Fix spacing for clear repo button

- client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap
- client/src/app/layout/HeaderApp/HeaderApp.tsx
- client/src/app/layout/HeaderApp/SSOMenu.tsx
- client/src/app/layout/HeaderApp/tests/__snapshots__/HeaderApp.test.tsx.snap
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- client/src/app/pages/applications/application-review/components/review-form/review-form.tsx
- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx
- client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
- client/src/app/pages/controls/business-services/components/business-service-form/business-service-form.tsx
- client/src/app/pages/controls/job-functions/components/job-function-form/job-function-form.tsx
- client/src/app/pages/controls/stakeholder-groups/components/stakeholder-group-form/stakeholder-group-form.tsx
- client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx
- client/src/app/pages/controls/tags/components/tag-form/tag-form.tsx
- client/src/app/pages/controls/tags/components/tag-type-form/tag-type-form.tsx
- client/src/app/pages/identities/components/identity-form/identity-form.tsx
- client/src/app/pages/proxies/proxy-form.tsx
- client/src/app/shared/components/FilterToolbar/SearchFilterControl.tsx
- client/src/app/shared/components/app-table-action-buttons/app-table-action-buttons.tsx
- client/src/app/shared/components/confirm-dialog/confirm-dialog.tsx
- client/src/app/shared/components/confirm-dialog/tests/__snapshots__/confirm-dialog.test.tsx.snap
- client/src/app/shared/containers/application-dependencies-form/application-dependencies-form.tsx
For QE: 
```button[aria-label='Options menu'] - x-element-toggle
input[aria-label='name'] - application-name, business-service-name, job-function-name, stakeholder-group-name, stakeholder-name, tag-name, tag-type-name
input[aria-label='rank'] - rank, rank-input-id
table[aria-label='tag-table'] - patternfly does not currently support IDs for a table 
button[aria-label='Actions'] - id="sso-actions-toggle"
input[aria-label='Private Key Passphrase'] private-key-passphrase-input
button[aria-label=create-job-function] create-job-function
button[aria-label=confirm], confirm-copy-checkbox, confirm-dialog-button
div > button[aria-label='Actions'] sso-actions-toggle
button[aria-label='close'] application-dependencies-close, ** confirm dialog close button may have generic ID. confirm-cancel-button …
```
> qe: Add missing ids where QE is using aria-label selectors

- client/src/app/pages/custom-targets/custom-targets.tsx
Handles breaking down custom targets array size for a better layout
Fixes the drop logic between areas
> :sparkles:: Custom Targets - Spread cards over 5 columns

- client/src/app/shared/notifications-context.tsx
https://issues.redhat.com/browse/MTA-28
> :bug: Implement clear notifications 

- client/package.json
- client/src/app/pages/migration-targets/grid.tsx
- client/src/app/pages/migration-targets/item.tsx
- client/src/app/pages/migration-targets/migration-targets.tsx
- client/src/app/pages/migration-targets/sortable-item.tsx
- package-lock.json
- This PR introduces a solution for a sortable drag-and-drop view for custom targets.  
https://user-images.githubusercontent.com/11218376/217974018-bee9aad3-ff4e-4f3b-ac46-39da6beacf62.mov
> :sparkles: dnd-kit library integration for custom targets screen

- .github/workflows/march-image-build-push.yml
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
> :sparkles: Use composite action for image builds

- .github/workflows/march-image-build-push.yml
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
> :bug: Try using new ubuntu release

- client/src/app/components/target-card.tsx
- Grab drag and drop icon should not be visible in the wizard
> :bug: Hide grab icon in wizard

- client/src/app/components/target-card.tsx
- client/src/app/pages/migration-targets/components/dnd/sortable-item.tsx
- Adds custom label for wizard cards
> :sparkles: Add space for long descriptions and add custom label

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/analysis-wizard/set-scope.tsx
Resolves https://issues.redhat.com/browse/MTA-51
> :sparkles: Change statement and add missing i18n

- client/public/locales/en/translation.json
> :seedling: Update sidebar persona names

- client/src/app/pages/migration-targets/migration-targets.tsx
- Scroll to the bottom of the custom targets page when "Take me there" link is clicked on customTarget create
> :sparkles: Scroll to bottom notification link

- package-lock.json
- Downstream builds are failing due to a stale lockfile
> :seedling: Update stale package-lock.json file

- client/src/app/api/rest.ts
- client/src/app/pages/repositories/Mvn.tsx
- client/src/app/queries/cache.ts
Resolves https://github.com/konveyor/tackle2-ui/issues/671
> :bug: mvn: Refactor without useEffect

- client/public/locales/en/translation.json
- client/src/app/api/models.ts
- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/applications/analysis-wizard/set-options.tsx
Supports https://github.com/konveyor/tackle2-addon-windup/pull/87
> :sparkles: Add auto tagging flag to wizard

- client/src/app/pages/applications/application-review/application-review.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/612
> :sparkles: Allow reviews without assessment when flagged

- client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap
- client/src/app/layout/HeaderApp/HeaderApp.tsx
- client/src/app/layout/HeaderApp/SSOMenu.tsx
- client/src/app/layout/HeaderApp/tests/__snapshots__/HeaderApp.test.tsx.snap
- Fixes broken keycloak logout 
- Pending oauth2 env vars for supporting https://github.com/konveyor/tackle2-operator/pull/159
> :bug: Fix logout and add placeholder for oauth logout functionality

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
resolves https://issues.redhat.com/browse/MTA-219
> :bug: Analysis details needs task obj

- client/src/app/api/models.ts
- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/utils/model-utils.tsx
- Removes unused "category" field in applications form tag dropdown 
- Add 'source' field to tagRef so that it will not be overwritten on application edit 
- Fixes the issues we were seeing around duplicate tags being created with automated tags turned on during subsequent analysis attempts
> :bug: Update tags model to include source for tags

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
> :sparkles: Add download buttons for report

- client/src/app/data/targets.ts
- client/src/app/pages/applications/analysis-wizard/sources.ts
Closes UI portion of https://issues.redhat.com/browse/MTA-267
> :seedling: Add eap8 as a target option

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/analysis-wizard/review.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/697
> :sparkles: Add auto tagging to review

- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
Fixes https://issues.redhat.com/browse/MTA-284
> :bug: Fix hub download URL for html reports

- INTERNATIONALIZATION.md
- README.md
- client/public/locales/en/translation.json
- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/controls/business-services/components/business-service-form/business-service-form.tsx
- client/src/app/pages/controls/job-functions/components/job-function-form/job-function-form.tsx
- client/src/app/pages/controls/stakeholder-groups/components/stakeholder-group-form/stakeholder-group-form.tsx
- client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx
- client/src/app/pages/controls/tags/components/tag-category-form/tag-category-form.tsx
- client/src/app/pages/identities/components/identity-form/identity-form.tsx
- client/src/app/pages/migration-targets/custom-target-form.tsx
Closes https://github.com/konveyor/tackle2-ui/issues/211 
Fixes https://issues.redhat.com/browse/MTA-303
> :bug: Remove please statements in all UI text

- client/package.json
- client/public/locales/en/translation.json
- client/src/app/Paths.ts
- client/src/app/Routes.tsx
- client/src/app/api/models.ts
- client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap
- client/src/app/layout/SidebarApp/SidebarApp.tsx
- client/src/app/layout/SidebarApp/tests/__snapshots__/SidebarApp.test.tsx.snap
- client/src/app/pages/waves/index.ts
- client/src/app/pages/waves/wave-applications-table/wave-applications-table.tsx
- client/src/app/pages/waves/wave-stakeholders-table/wave-stakeholders-table.tsx
- client/src/app/pages/waves/waves.tsx
- client/src/app/queries/waves.ts
- client/src/app/shared/components/composable-app-table/composable-app-table.tsx
- client/src/app/shared/components/composable-app-table/index.ts
- package-lock.json
UPDATE: Now tracking a feature branch off of main for migration-waves
Closes #570 
Closes #572 
Closes #571
> :sparkles: Migration waves table architecture

- client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
If any of the application copied to has either an existing assessment or a review then the message should be displayed and confirmation is required:
Conversely no message and confirmation box are required when all of the applications copied to has no assessment or review:
Uses a function instead for useEffect().
resolves https://issues.redhat.com/browse/MTA-261
> :bug: bulk copy: Fix assessment state evaluation

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
Resolves https://github.com/konveyor/tackle2-ui/issues/708
> :sparkles: Application assessment/review: Discard message

- client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
(cherry picked from commit 457792ea051f734bee9e7d678df0d9a46fee9f30)
> :bug: [backport 6.1.0] bulk copy: evaluate assessment state (#706)

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
(cherry picked from commit e7941a267aee2f515539ee262431f12dfef57109)
> :bug: [backport 6.1.0] Discard message (#710)

- client/src/app/pages/applications/applicationsFilter.ts
[MTA-283](https://issues.redhat.com/browse/MTA-283)
> :bug: Fix applications table sorting

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/review.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/applications/analysis-wizard/set-options.tsx
According to Ramon, we do not need to parse source names from the custom-rules-files.
> :bug: Don't auto select parsed sources from custom rule files

- client/src/app/api/models.ts
- client/src/app/common/CustomRules/useRuleFiles.tsx
- client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/migration-targets/custom-target-form.tsx
Fixes https://issues.redhat.com/browse/MTA-300
> :bug: Fix initial loading state for existing rule file placeholders

- client/src/app/pages/applications/applicationsFilter.ts
Backports 9378a525f47dccfcc4a244af34b0a112735a72f8
> :bug: [backport 6.1] Fix applications table sorting (#719)

- client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
Fixes [MTA-306](https://issues.redhat.com/browse/MTA-306)
> :bug: Hide upload when a binary exists

- client/src/app/pages/migration-targets/custom-target-form.tsx
Fixes https://issues.redhat.com/browse/MTA-297
> :bug: Allow .jpg uploads for custom target images

- client/src/app/pages/migration-targets/custom-target-form.tsx
https://issues.redhat.com/browse/MTA-345
> :bug: [backport-6.1] Fix error validation for image id (#725)

- client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap
- client/src/app/layout/HeaderApp/SSOMenu.tsx
- client/src/app/layout/HeaderApp/tests/__snapshots__/HeaderApp.test.tsx.snap
https://issues.redhat.com/browse/MTA-330
> :bug: Hide SSO menu if keycloak is not available

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/queries/assessments.ts
- client/src/app/queries/reviews.ts
Fix regression to not display "Discard assessment" kebab option.
Fix error when discarding application's assessment/review when there was only a review.
Resolves https://issues.redhat.com/browse/MTA-282
> :bug: Fix deletion for Applications assessment/review 

- client/src/app/pages/migration-targets/custom-target-form.tsx
Fixes https://issues.redhat.com/browse/MTA-364
> :bug: Unknown image file name fixed for default image

- Dockerfile
(cherry picked from commit 704f913cd96a0c32c9309b1b1403f706060deba1)
> :bug: [backport-6.1] Rebump UBI9 (#733)

- client/src/app/pages/migration-targets/custom-target-form.tsx
Fixes https://issues.redhat.com/browse/MTA-363?filter=-1
> :bug: Add missing form label for repository type

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
591399dde17a01c2d0674514243419d7f8359203
> :bug: Update application tags when analysis completes (#748)

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
https://issues.redhat.com/browse/MTA-375
> :bug: Remove wizard validation for rulebundle length

- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
https://issues.redhat.com/browse/MTA-381
> :bug: Clear state when closing add rules modal

- client/src/app/pages/migration-targets/migration-targets.tsx
https://issues.redhat.com/browse/MTA-369
> :bug: Duplicate rendered custom target form issues

- client/src/app/api/models.ts
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
https://issues.redhat.com/browse/MTA-388?filter=-1
> :bug: Conditional csv download button 

- client/src/app/api/models.ts
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
fed7ebfc85ae56351c5d4b748c6054d182a8e5e4
> :bug: [backport 6.1] Conditional csv download button

- client/src/app/common/CustomRules/useRuleFiles.tsx
https://issues.redhat.com/browse/MTA-300
> :bug: Fix multi upload for wizard rules

- client/src/app/common/CustomRules/useRuleFiles.tsx
f23f0ca11bf97416d0cbda89f5ac7d6a0a48d229
> :bug: [backport 6.1] Fix multi upload for wizard rules (#762)

- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
9df97bb5ed47931be096a9c51d55a758dc4c6351
> :bug: [backport 6.1] Remove initial files for custom rules wizard mode (#763)

- client/src/app/pages/migration-targets/components/dnd/grid.css
- client/src/app/pages/migration-targets/components/dnd/grid.tsx
- client/src/app/pages/migration-targets/migration-targets.tsx
93f0382afd4c4c58f23ca68b5a2ef8ab8bda042b
> :bug: [backport 6.1] Make grid responsive for migration targets (#765)

- client/src/app/Paths.ts
- client/src/app/Routes.tsx
- client/src/app/api/models.ts
- client/src/app/api/rest.ts
- client/src/app/layout/SidebarApp/SidebarApp.tsx
- client/src/app/pages/jira-trackers/index.ts
- client/src/app/pages/jira-trackers/jira-configuration-table/index.ts
- client/src/app/pages/jira-trackers/jira-configuration-table/jira-configuration-table.tsx
- client/src/app/pages/jira-trackers/jira-trackers.tsx
- client/src/app/queries/jiratrackers.ts
- client/src/app/shared/components/composable-app-table/composable-app-table.tsx
> :sparkles: Add skeleton for JIRA tracker table & routing

- client/package.json
- client/public/locales/en/translation.json
- client/src/app/Constants.ts
- client/src/app/pages/applications/application-review/components/application-assessment-donut-chart/tests/__snapshots__/application-assessment-donut-chart.test.tsx.snap
- client/src/app/pages/applications/components/application-tags/application-tag-label.tsx
- client/src/app/pages/applications/components/application-tags/application-tags.tsx
- client/src/app/pages/controls/tags/components/tag-category-form/tag-category-form.tsx
- client/src/app/pages/controls/tags/tags.tsx
- client/src/app/shared/components/color/color.tsx
- package-lock.json
See #745 and #781
for https://issues.redhat.com/browse/MTA-332
> :bug: [backport 6.1] Tag category color changes from #745 and #781

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Closes https://issues.redhat.com/browse/MTA-377
Assists with https://issues.redhat.com/browse/MTA-430
> :bug: Alert for custom rule file required when no targets

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Closes https://issues.redhat.com/browse/MTA-377
Closes https://issues.redhat.com/browse/MTA-430
> :bug: Alert for custom rule file required when no targets (#780)

- client/src/app/common/KeycloakProvider.tsx
> :bug: [backport 6.1] Do not refresh token when feature disabled (#771)

- client/src/app/common/CustomRules/useRuleFiles.tsx
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
Re-closes https://issues.redhat.com/browse/MTA-382
> :bug: Fix status of duplicate rule files

- client/src/app/common/CustomRules/useRuleFiles.tsx
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
https://issues.redhat.com/browse/MTA-382
e0f71343a0e753f75b14aa896e0b9209bade12ab
> :bug: [Backport 6.1] Fix status of duplicate rule files (#785)

- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-assessment.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
- client/src/app/pages/applications/components/application-tags/application-tags.tsx
https://issues.redhat.com/browse/MTA-438
> :bug: Add loading spinner for active tasks

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Allows app drawers to be toggled on click.
> :bug: Toggle drawer open if row clicked

- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-assessment.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
- client/src/app/pages/applications/components/application-tags/application-tags.tsx
https://issues.redhat.com/browse/MTA-438
> :bug: [backport 6.1] Add loading spinner for active tasks (#793)

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/analysis-wizard/set-options.tsx
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Fixes https://issues.redhat.com/browse/MTA-430
> :bug: Fix label for targets screen selection

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/analysis-wizard/set-options.tsx
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Fixes https://issues.redhat.com/browse/MTA-430
> :bug: [backport-6.1]  Fix label for targets screen selection (#804)

- client/src/app/api/rest.ts
- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/pages/applications/applicationsFilter.ts
- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx
- client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
- client/src/app/pages/controls/business-services/business-services.tsx
- client/src/app/pages/identities/identities.tsx
- client/src/app/pages/reports/reports.tsx
- client/src/app/queries/applications.ts
- client/src/app/shared/containers/application-dependencies-form/application-dependencies-form.tsx
- client/src/app/shared/containers/application-dependencies-form/select-dependency.tsx
I had to close #644 and recreate this PR because there was something odd and files were not syncing with my branch.
Let's continue bring more consistency when using axios, regarding applications queries.
https://github.com/konveyor/tackle2-ui/issues/607
> :sparkles: Applications Queries to use Axios

- client/src/app/pages/controls/business-services/components/business-service-form/business-service-form.tsx
Replace formik with react-hook-form
> :seedling: Rewrite Business service form with react-hook-form

- client/src/app/pages/controls/tags/components/tag-category-form/tag-category-form.tsx
- Update hex string value case to match db seeded expectations when editing the color values.
> :bug: Fix case comparison for hex values

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/api/models.ts
- client/src/app/pages/applications/components/application-form/application-form.tsx
This is prerequisite for using applications waves, see https://github.com/konveyor/enhancements/tree/master/enhancements/migration-waves for details.
> :sparkles: Application form: add owner & contributors

- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/controls/business-services/components/business-service-form/business-service-form.tsx
- client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx
- client/src/app/pages/waves/wave-stakeholders-table/wave-stakeholders-table.tsx
- Fix leftover missed changes after formik refactor.
> :bug: Fix clear & cancel functionality for app / stakeholder/ business service

- client/src/app/FeatureFlags.ts
- client/src/app/api/models.ts
- client/src/app/pages/identities/components/identity-form/identity-form.tsx
- client/src/app/pages/identities/identities.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/589
> :sparkles: Adds Jira creds

- client/src/app/pages/applications/components/application-form/application-form.tsx
The `ApplicationForm` now handles directly tags (TagRef[]) allowing to preserve value of existing tags "source" field and to avoid automated tags (source = "Analysis") to be overridden with source = "". 
Resolves https://github.com/konveyor/tackle2-ui/issues/836
> :bug: Fix tag source override when updating application

- client/public/locales/en/translation.json
- client/src/app/Routes.tsx
- client/src/app/api/models.ts
- client/src/app/api/rest.ts
- client/src/app/layout/SidebarApp/SidebarApp.tsx
- client/src/app/pages/controls/stakeholders/stakeholders.tsx
- client/src/app/pages/external/jira/trackers.tsx
- client/src/app/pages/issues/index.ts
- client/src/app/pages/issues/issues.tsx
- client/src/app/pages/waves/wave-applications-table/wave-applications-table.tsx
- client/src/app/pages/waves/wave-stakeholders-table/wave-stakeholders-table.tsx
- client/src/app/pages/waves/waves.tsx
- client/src/app/queries/issues.ts
- client/src/app/shared/components/table-controls/TableRowContentWithControls.tsx
- client/src/app/shared/hooks/use-table-controls/types.ts
- client/src/app/shared/hooks/use-table-controls/useTableControlProps.ts
- client/src/app/shared/hooks/use-table-controls/useTableControlState.ts
- client/src/app/shared/hooks/use-table-controls/useTableControlUrlParams.ts
- client/src/app/shared/hooks/use-table-controls/useTableControls.ts
- client/src/app/shared/hooks/useCompoundExpansionState.ts
- client/src/app/utils/type-utils.ts
- Includes initial api requests for loading issues & related UI components
- Adds an idProperty field to hooks where a unique key is required for state management
> :sparkles: Issue table initial work

- client/src/app/api/models.ts
- client/src/app/pages/external/jira/instance-form.tsx
Interface insecure field with backend.
Follow-up https://github.com/konveyor/tackle2-ui/pull/833
Resolves https://github.com/konveyor/tackle2-ui/issues/585
> :sparkles: Add insecure field to /trackers for instance-form

- client/src/app/pages/applications/applicationsFilter.ts
- client/src/app/shared/components/FilterToolbar/SearchFilterControl.tsx
Resolves https://issues.redhat.com/browse/MTA-467
> :sparkles: SearchFilterControl: Ignore multiple space

- client/public/locales/en/translation.json
- client/src/app/api/rest.ts
- client/src/app/layout/SidebarApp/SidebarApp.tsx
- client/src/app/pages/migration-waves/manage-applications-form.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
- client/src/app/queries/applications.ts
Resolves https://github.com/konveyor/tackle2-ui/issues/862
> :sparkles: Add application waves management

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/reports/components/landscape/landscape.tsx
Resolves https://issues.redhat.com/browse/MTA-469
(cherry picked from commit 8f4b4e576f20aebe734bdabf83478e3ab442f873)
> :bug: [backport-release-0.1] Fix unassessed typo (#834)

- client/src/app/pages/applications/application-assessment/application-assessment.tsx
https://issues.redhat.com/browse/MTA-466
> :bug: [backport] Discard assessment on cancel

- client/src/app/api/models.ts
- client/src/app/api/rest.ts
- client/src/app/pages/external/jira/instance-form.tsx
- client/src/app/pages/migration-waves/migration-wave-status-table/migration-wave-status-table.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
- client/src/app/queries/tickets.ts
Resolves https://github.com/konveyor/tackle2-ui/issues/573
> :sparkles: Migration waves status

- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/external/jira/instance-form.tsx
Addressed URL validation for application-form and instance-form after recent change.
> :bug: Fix RegExp

- client/src/app/api/models.ts
- client/src/app/api/rest.ts
- client/src/app/common/CustomRules/rules-utils.tsx
- client/src/app/common/CustomRules/useRuleFiles.tsx
- client/src/app/components/target-card.tsx
- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/applications/analysis-wizard/set-options.tsx
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
- client/src/app/pages/migration-targets/components/dnd/item.tsx
- client/src/app/pages/migration-targets/components/new-custom-target-modal/new-custom-target-modal.tsx
- client/src/app/pages/migration-targets/components/update-custom-target-modal/update-custom-target-modal.tsx
- client/src/app/pages/migration-targets/custom-target-form.tsx
- client/src/app/pages/migration-targets/migration-targets.tsx
- client/src/app/queries/rulesets.ts
- package-lock.json
- https://github.com/konveyor/tackle2-hub/commit/86df55c553f5c7d584bb01a788951dee4b87edc0 -> bring ui up to date
> :warning: Rulebundle -> Ruleset

- client/src/app/pages/migration-waves/components/manage-applications-form.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/876
> :sparkles: ManageApplicationsForm: Set initialSelected items

- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Closes https://github.com/konveyor/tackle2-ui/issues/872
- Disable edit date of a previously started migration wave 
- Use dayjs instead of custom formatter/parser 
- Add validation for end date before start date
> :bug:  Fix edit migration wave

- client/src/app/pages/migration-waves/components/manage-applications-form.tsx
Remove unnecessary commented lines
> :sparkles: follow-up cleanup for PR#902

- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Closes https://github.com/konveyor/tackle2-ui/issues/872
- Disable edit date of a previously started migration wave 
- Use dayjs instead of custom formatter/parser 
- Add validation for end date before start date
> :bug: [backport] Fix migration wave edit

- client/src/app/pages/migration-waves/components/export-form.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/906
> :sparkles: ExportForm: Disable fields until available

- client/public/locales/en/translation.json
- client/src/app/api/rest.ts
- client/src/app/pages/migration-waves/migration-waves.tsx
- client/src/app/queries/migration-waves.ts
Wraps individual migration waves delete for bulk delete
Resolves https://github.com/konveyor/tackle2-ui/issues/913
> :sparkles: Migration Waves: refactor bulk delete

- client/src/app/FeatureFlags.ts
> :ghost: Enable migration waves for release testing

- client/src/app/FeatureFlags.ts
- client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap
- client/src/app/layout/SidebarApp/tests/__snapshots__/SidebarApp.test.tsx.snap
- Help with confusion around waves not available in community operator
> :ghost: Turn on feature flag for migration waves in main

- client/src/app/pages/controls/stakeholders/components/stakeholder-form.tsx
- client/src/app/pages/controls/tags/components/tag-category-form.tsx
- client/src/app/pages/controls/tags/components/tag-form.tsx
Follow-up from https://github.com/konveyor/tackle2-ui/pull/924, included weren't saved and missed previous PR.
> :sparkles: Notifications: Fix Toastr lowercase()

- client/src/app/pages/applications/components/application-form/application-form.tsx
Resolves https://issues.redhat.com/browse/MTA-651
> :bug: ApplicationForm: Force onChange when unBlur Owner field

- client/src/app/pages/controls/stakeholders/components/stakeholder-form.tsx
- client/src/app/pages/controls/tags/components/tag-category-form.tsx
- client/src/app/pages/controls/tags/components/tag-form.tsx
Follow-up from https://github.com/konveyor/tackle2-ui/pull/924, included weren't saved and missed previous PR.
(cherry picked from commit 67be5dade77a7fbcaaa591efc26620367a27b32c)
> :sparkles: [Backport release-0.2] Notifications: Fix Toastr lowercase() (#932)

- client/src/app/pages/applications/components/application-form/application-form.tsx
Resolves https://issues.redhat.com/browse/MTA-651
(cherry picked from commit 6e60dcae3f24e11d3cd0c2ac6e08016965d50a0b)
> :bug: [Backport release-0.2] ApplicationForm: Force onChange when unBlur Owner field (#940)

- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-680
> :sparkles: MigrationWaveForm: fix select label, adjust placeholderText

- client/src/app/queries/trackers.ts
- Tracker poll option was in the wrong place
> :bug: Tracker polling not working

- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
Closes https://issues.redhat.com/browse/MTA-464
> :bug: Reflect form state in active tab for custom rules step

- client/src/app/pages/external/jira/tracker-form.tsx
- client/src/app/utils/utils.ts
> :bug: Require https for jira instances

- client/src/app/pages/migration-waves/components/export-form.tsx
> :bug: Skip applications that have already been exported

- client/src/app/pages/external/jira/tracker-form.tsx
- client/src/app/utils/utils.ts
Closes #969
(cherry picked from commit 85ca0a4b6dbd1daa29ac77dce62c1d46d57c0679)
> :bug: [Backport release-0.2] Require https for jira instances (#976)

- client/src/app/pages/migration-waves/components/export-form.tsx
Closes #970 #952
(cherry picked from commit dded7be40623d9303949d961ed22126b13eaf2a4)
> :bug: [Backport release-0.2] Skip applications that have already been exported (#978)

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Resolves https://issues.redhat.com/browse/MTA-681
> :sparkles: Add tooltip when deleting application(s) assigned to wave(s)

- client/src/app/pages/external/jira/components/tracker-status.tsx
- client/src/app/pages/external/jira/trackers.tsx
Resolves https://issues.redhat.com/browse/MTA-697
(cherry picked from commit 4a057ca78761fa4facfd0eed3b9e41cb26492846)
> :sparkles: [Backport release-0.2] Jira configuration: instance error details (#982)

- client/src/app/pages/controls/job-functions/job-functions.tsx
Resolves https://issues.redhat.com/browse/MTA-481
(cherry picked from commit c60775fc79c31faccdef46677f1ac4b277582116)
> :sparkles: [Backport release-0.2] Disable deletion of assigned job function (#983)

- client/src/app/pages/repositories/Mvn.tsx
Resolves https://issues.redhat.com/browse/MTA-470
(cherry picked from commit 7dd62183d248279a9a141f732bcbbe6131e2f429)
> :sparkles: [Backport release-0.2] Maven Repo: Display spinner when fetching cache (#990)

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Fix the following error which occurs when selecting an application: 
`Uncaught TypeError: b is undefined`
> :bug: AppliationTableAssessment: Fix selectRow

- client/src/app/pages/applications/components/application-tags/application-tag-label.tsx
- client/src/app/pages/controls/tags/components/tag-category-form.tsx
- client/src/app/pages/controls/tags/tags.tsx
Fixes https://issues.redhat.com/browse/MTA-479
> :bug: MTA-479: Use tag category fallback colors in tags table and tag category edit form

- client/src/app/components/target-card.tsx
> :bug: Allow selecting of custom targets with no associated targets

- client/src/app/common/CustomRules/rules-utils.tsx
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
Closes https://github.com/konveyor/tackle2-ui/issues/1015
> :bug: Show rules total and fix xml support

- client/src/app/pages/external/jira/trackers.tsx
Resolves [MTA-766](https://issues.redhat.com/browse/MTA-766)
> :bug: Remove duplicate identifier in jira trackers table

- client/public/locales/en/translation.json
- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
https://issues.redhat.com/browse/MTA-753
> :bug: Add specific wave success notification.

- client/src/app/pages/identities/components/identity-form/identity-form.tsx
- client/src/app/pages/identities/identities.tsx
- client/src/app/queries/trackers.ts
- Closes #1026 
- Reintroduces the tracker polling refetch interval that was inadvertently removed
- Add new identity types for filter/display in identity table
> :bug: Update jira cred names & add filter/table support

- client/src/app/api/rest.ts
- client/src/app/pages/identities/components/identity-form/identity-form.tsx
https://github.com/konveyor/tackle2-ui/pull/1036 follow-up.
Resolves https://issues.redhat.com/browse/MTA-772
> :sparkles: Identities: Add bearer key

- client/src/app/api/rest.ts
- client/src/app/pages/identities/identities.tsx
- client/src/app/queries/identities.ts
Closes https://issues.redhat.com/browse/MTA-764
Closes https://issues.redhat.com/browse/MTA-765
> :bug: Show full credential name on deletion

- client/src/app/pages/external/jira/tracker-form.tsx
- The tracker page is crashing on create button click
> :bug: jira trackers page is crashing

- client/src/app/pages/external/jira/tracker-form.tsx
Trap undefined which slipped through the cracks of React Hook Form.
> :bug: TrackerForm: Fix identityOptions

- client/public/locales/en/translation.json
- client/src/app/pages/external/jira/tracker-form.css
- client/src/app/pages/external/jira/tracker-form.tsx
Resolves https://issues.redhat.com/browse/MTA-739
> :sparkles: TrackerForm: Popover to detail insecure communication

- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/migration-targets/custom-target-form.tsx
- client/src/app/utils/utils.ts
Resolves https://issues.redhat.com/browse/MTA-484
> :sparkles: CustomTargetForm: Repository validation

- client/src/app/pages/external/jira/trackers.tsx
Resolves https://issues.redhat.com/browse/MTA-815
> :sparkles: Trackers : Display kind string

- client/src/app/api/models.ts
- client/src/app/api/rest.ts
- client/src/app/pages/external/jira/tracker-form.tsx
- client/src/app/pages/migration-waves/components/export-form.tsx
- client/src/app/pages/migration-waves/components/status-table.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
- client/src/app/queries/trackers.ts
Resolves https://github.com/konveyor/tackle2-ui/issues/1053
> :sparkles: Refactor HUB API Jira changes

- client/src/app/pages/migration-waves/components/ticket-issue.tsx
- client/src/app/pages/migration-waves/components/wave-status-table.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
Use TicketIssue component to wrap ticket lookup hook.
> :bug: Add TicketIssue component to fix WaveStatusTable

- client/src/app/pages/external/jira/trackers.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
Resolves https://issues.redhat.com/browse/MTA-895
> :bug: Trackers: add noDataEmptyState

- package-lock.json
Fix high critical vulnerability by running "npm audit fix"
> :sparkles: npm audit fix

- client/src/app/pages/controls/tags/components/tag-category-form.tsx
- client/src/app/pages/controls/tags/components/tag-form.tsx
Resolves https://issues.redhat.com/browse/MTA-909
> :sparkles: Tag/TagCategory forms: fix placeholder text

- client/public/locales/en/translation.json
- client/public/locales/es/translation.json
- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/pages/controls/business-services/business-services.tsx
- client/src/app/pages/controls/job-functions/job-functions.tsx
- client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
- client/src/app/pages/controls/stakeholders/stakeholders.tsx
- client/src/app/pages/controls/tags/tags.tsx
- client/src/app/pages/identities/identities.tsx
Resolves https://issues.redhat.com/browse/MTA-881
Also moves trailing dot to translation file.
> :sparkles: Stakeholders: Add noDataEmptyState

- client/src/app/pages/identities/identities.tsx
Resolves https://issues.redhat.com/browse/MTA-863
> :sparkles: Identities: Consistent display names for Jira auth

- client/src/app/pages/reports/reports.tsx
This will help with PF V5 migration.
> :sparkles: Fix Report button for Suggested adoption plan

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Resolves https://issues.redhat.com/browse/MTA-814
> :sparkles: Notifications: No lower case for Application when saving

- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-906
(cherry picked from commit 3a085a6d81340d47f41d633dbbd9a17554658cbe)
> :sparkles: [backport release-0.2] Migration wave validation requires min. 3 characters (#1096)

- client/public/locales/en/translation.json
- client/src/app/pages/external/jira/trackers.tsx
Resolves https://issues.redhat.com/browse/MTA-908
(cherry picked from commit 573bce2d99ad6d11188ed236d5ba2fcf22c72e5f)
> :sparkles: [backport release-0.2] Jira: Add URL filter and sorting (#1088)

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Resolves https://issues.redhat.com/browse/MTA-898
(cherry picked from commit 18c320d21f99a8ddda8ee6cc75afd7facb9670be)
> :sparkles: [backport release-0.2] Applications: No tooltip when no selections (#1097)

- client/src/app/pages/applications/applicationsFilter.ts
Resolves https://issues.redhat.com/browse/MTA-916
(cherry picked from commit 82cfeae208141b2a5d14a972621d8bac72179d40)
> :sparkles: [backport release-0.2] Default value for tag sort (#1108)

- client/src/app/pages/controls/tags/components/tag-form.tsx
- client/src/app/pages/controls/tags/tags.tsx
- client/src/app/queries/tags.ts
Resolves https://issues.redhat.com/browse/MTA-802
(cherry picked from commit 1af3f9dfd8c445583680a8c51fb1d0a5bc60469e)
> :sparkles: [backport release-0.2] Tags: Mark stall data after create/edit mutation (#1098)

- client/src/app/pages/identities/components/identity-form/identity-form.tsx
- client/src/app/pages/identities/identities.tsx
- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
- client/src/app/pages/migration-waves/migration-waves.tsx
- client/src/app/queries/migration-waves.ts
- client/src/app/utils/waves-selector.ts
…  (#1124)
Resolves https://issues.redhat.com/browse/MTA-877
Resolves https://github.com/konveyor/tackle2-ui/issues/974 https://github.com/konveyor/tackle2-ui/issues/911
- Adds Completed status
- Adds In Progress status
- Filters out empty status from derived status calculation. This could mean the issue has been deleted from the underlying JIRA instance OR that the Jira ticket is in the process of being created. We have no way of knowing how to interpret empty string, so this filters it out which gives us a more accurate representation of aggregated status.
- Add TODO for info text around auth types for JIRA credential creation
- Remove Created By field in identity page table
- Fixes stale tickets data in migration waves table by mounting the tickets query
> :bug: [backport release-0.2] MTA-877- Fix Jira status polling and handle completed status

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- Restore CSV download functionality
> :bug: [backport-release specific] Restore csv download feature

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Resolves https://issues.redhat.com/browse/MTA-898
(cherry picked from commit 807e094caa87bb448479b0326dcd721c536468e5)
> :bug: [backport release-0.2] Applications: bulk delete disabled when no selection (#1149)

- client/src/app/FeatureFlags.ts
- client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap
- client/src/app/layout/SidebarApp/tests/__snapshots__/SidebarApp.test.tsx.snap
- Dynamic reports should not be enabled for release-0.2
> :bug: Turn off dynamic reports for release-0.2

- client/src/app/pages/external/jira/tracker-form.tsx
- client/src/app/queries/trackers.ts
- Resolves https://issues.redhat.com/browse/MTA-973?filter=-1
> :bug: [backport release-0.2] Fix missing notification for adding tracker (#1176)

- client/src/app/pages/migration-waves/migration-waves.tsx
Resolves https://issues.redhat.com/browse/MTA-937
> :bug: Use id field instead of name to uniquely select items

- client/src/app/pages/migration-waves/migration-waves.tsx
Resolves https://issues.redhat.com/browse/MTA-937
(cherry picked from commit a8c9b2c6cf5690c1c04b4eb3bd7b1541977ae12d)
> :bug: [backport release-0.2] Use id field instead of name to uniquely select items (#1174)

- client/src/app/pages/controls/business-services/business-services.tsx
- client/src/app/pages/controls/job-functions/job-functions.tsx
- client/src/app/pages/migration-targets/migration-targets.tsx
Solves https://issues.redhat.com/browse/MTA-974
Co-authored-by: Mike Turley <mike.turley@alum.cs.umass.edu>
> :bug: [backport release-0.2]  Start notifications in upper case (#1142)

- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/utils/utils.test.ts
- client/src/app/utils/utils.ts
Resolves https://issues.redhat.com/browse/MTA-985
> :bug: [backport release-0.2] Add url validation to rules step (#1180)

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/queries/assessments.ts
Resolves https://issues.redhat.com/browse/MTA-1041
> :bug:[backport release-0.2] Fix crashing app when deleting (#1202)

- codecov.yml
Follow up to #1217 and also make patch status checks non-blocking.
> :seedling: Make codecov patch checks non-blocking

- client/src/app/pages/applications/manage-imports/manage-imports.tsx
- client/src/app/pages/external/jira/components/tracker-status.tsx
- client/src/app/shared/components/status-icon/status-icon.tsx
- client/src/app/shared/components/status-icon/tests/__snapshots__/status-icon.test.tsx.snap
closes #1070 
lib-ui statusicon dep replaced with an updated app/shared/components statusicon
> :seedling: 1070 remove lib-ui statusicon dep

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
closes #1237 
applied nowrap for a few tables columns where it seemed to make sense
> :bug: 1237 - fix status column widths

- client/src/app/pages/identities/components/identity-form/identity-form.tsx
- Closes https://github.com/konveyor/tackle2-ui/issues/1255
- Also fixes broken settings file upload
> :bug: Fix key file upload

- client/src/app/pages/controls/tags/components/tag-table.tsx
> :seedling:  chore(tag-table): update from pf deprecated

- client/src/app/api/models.ts
- client/src/app/pages/applications/analysis-wizard/__tests__/analysis-wizard.test.tsx
- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/review.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/applications/analysis-wizard/set-scope.tsx
- Request from the hub team: Change withKnown to withKnownLibs for taskData passed to task pod for analysis
> :ghost: withKnown-> withKnownLibs

- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
Resolves https://issues.redhat.com/browse/MTA-1250
> :bug: Analysis details and cancelation are conditional

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
Closes https://issues.redhat.com/browse/MTA-1047?filter=-1
> :bug: String value breaking schema validation for repo type

- client/public/locales/en/translation.json
- client/src/app/pages/archetypes/archetypes-page.tsx
Resolves [No warning that archetype has already been reviewed](https://issues.redhat.com/browse/MTA-1383)
> :bug: Alert archetype has already been reviewed

- client/src/app/api/models.ts
- client/src/app/data/mock-questionnaire.ts
- client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx
- client/src/mocks/stub-new-work/questionnaireData.ts
> :ghost: Wire up builtin questionnaire feature

- client/src/app/api/models.ts
- client/src/app/api/rest.ts
- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/applications/analysis-wizard/set-targets.tsx
- client/src/app/pages/migration-targets/components/custom-target-form.tsx
https://issues.redhat.com/browse/MTA-1407
> :bug: Overlapping label targets fixed

- client/src/app/pages/migration-targets/components/custom-target-form.tsx
https://issues.redhat.com/browse/MTA-1405
> :bug: Add custom validation for max size error

- client/src/app/pages/assessment/components/custom-wizard-footer/custom-wizard-footer.tsx
Resolves https://issues.redhat.com/browse/MTA-1207?filter=12422675
Don't allow save as draft to be rendered on first page when nothing has been answered yet.
> :bug: Don't allow save as draft on first page of wizard

- client/src/app/layout/HeaderApp/HeaderApp.tsx
closes https://issues.redhat.com/browse/MTA-1333
> :bug: fix issue with nonkonveyor header styling

- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-assessment.tsx
https://issues.redhat.com/browse/MTA-1367?filter=12422675
> :bug: Remove app level risk

- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- client/src/app/pages/applications/components/application-assessment-status/application-assessment-status.tsx
https://issues.redhat.com/browse/MTA-1391
> :bug: determine assessment status from all assessments

- hack/import-questionnaire/cloud-native.yaml
The questionnaire didn't have order on the sections, questions and answers before.  Adding them ensures that the wizard will work correctly.
> :seedling: Add `order` fields to `cloud-native.yaml` sample questionnaire

- client/src/app/pages/identities/components/identity-form/identity-form.tsx
https://issues.redhat.com/browse/MTA-1322
> :bug: Address upload via text bug for maven cred settings file

- client/src/app/api/models.ts
- client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
- Adds story points/effort field
Closes [Adding Efforts Column in Application Inventory Analysis](https://issues.redhat.com/browse/MTA-1535)
> :ghost: Add effort column to table and drawer

- client/src/app/pages/applications/components/application-detail-drawer/review-fields.tsx
- client/src/app/pages/archetypes/components/archetype-detail-drawer.css
- client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx
https://issues.redhat.com/browse/MTA-1326
> :sparkles: Add review fields to archetype drawer

- client/src/app/components/labels-from-items/labels-from-items.tsx
- client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
https://issues.redhat.com/browse/MTA-1541
> :sparkles: Add archetype filter for applications

- client/public/locales/en/translation.json
- client/src/app/pages/migration-waves/components/wave-applications-table.tsx
- client/src/app/queries/migration-waves.ts
https://issues.redhat.com/browse/MTA-1539
> :sparkles: Add an unlink button for removing underlying tickets

- client/public/locales/en/translation.json
- client/src/app/api/models.ts
- client/src/app/pages/migration-targets/components/custom-target-form.tsx
- client/src/app/pages/migration-targets/migration-targets.tsx
Resolves https://issues.redhat.com/browse/MTA-1627 as discussed in the UXD call 11-7-23
> :bug: Add provider to custom target form

- client/src/app/components/FilterToolbar/SearchFilterControl.tsx
> :bug: Consistent search input ID for QE

- client/src/app/pages/issues/helpers.ts
Resolves remainder of https://issues.redhat.com/browse/MTA-1541
> :bug: Allow filtering issues & dependencies by archetype

- client/src/app/pages/applications/applications-table/applications-table.tsx
- client/src/app/pages/issues/helpers.ts
https://issues.redhat.com/browse/MTA-1393
> :bug: Allow multiple business services to be selectedin filter

- client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
Resolves https://issues.redhat.com/browse/MTA-1715
> :bug: Fix text for stakeholder group empty state

- client/src/app/pages/applications/applications-table/applications-table.tsx
https://issues.redhat.com/browse/MTA-1711
> :bug: Fix filter name for archetypes

- client/src/app/pages/issues/issue-detail-drawer/issue-detail-drawer.tsx
Resolves https://issues.redhat.com/browse/MTA-1389
> :bug: Fix responsiveness for issues drawer

- client/public/locales/en/translation.json
- client/src/app/pages/applications/applications-table/applications-table.tsx
https://issues.redhat.com/browse/MTA-1751
> :bug: Fix edit review message for apps

- client/src/app/pages/assessment-management/import-questionnaire-form/import-questionnaire-form.tsx
https://issues.redhat.com/browse/MTA-1752
> :bug: Remove dupe text for upload

- client/src/app/pages/issues/helpers.ts
Resolves https://issues.redhat.com/browse/MTA-1739
> :bug: Update the formatting for incident name

- client/src/app/pages/applications/applications-table/applications-table.tsx
- Question mark always visible for review / assess status
> :bug: Fix broken icon state

- client/public/templates/questionnaire-template.yaml
- Add a more relevant template questionnaire demonstrating all of the assessment capabilities
> :bug: Create a better template for questionnaires

- client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx
Resolves https://issues.redhat.com/browse/MTA-1836
> :bug: Update name col in identified risks table

- client/src/app/pages/reports/components/application-landscape/application-landscape.tsx
- client/src/app/pages/reports/components/donut/donut.tsx
Resolves https://issues.redhat.com/browse/MTA-1860
> :bug: Fix donut tooltip

- client/src/app/queries/questionnaires.ts
https://issues.redhat.com/browse/MTA-1721?filter=12422675
> :bug: Remove required field on export

- client/src/app/pages/applications/applications-table/applications-table.tsx
Resolves https://issues.redhat.com/browse/MTA-1843
> :bug: Disallow delete of app assigned to wave

- client/src/app/pages/review/components/review-form/review-form.tsx
Resolves https://issues.redhat.com/browse/MTA-1858
> :bug: Update create review text

- client/src/app/pages/applications/applications-table/applications-table.tsx
- client/src/app/rbac.ts
Resolves https://issues.redhat.com/browse/MTA-1640
> :bug: Fix migrator permissions

- client/src/app/pages/assessment/components/assessment-actions/components/dynamic-assessment-actions-row.tsx
- client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx
- client/src/app/queries/assessments.ts
https://issues.redhat.com/browse/MTA-1894
> :bug: Address missing archetype name in delete assessment notification

- client/src/app/pages/assessment/components/view-archetypes/components/view-archetypes-table.tsx
https://issues.redhat.com/browse/MTA-1895
> :bug: Hide non required questionnaires from view in view archetypes page

- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
- client/src/app/pages/applications/components/application-review-status/application-review-status.tsx
Resolves https://issues.redhat.com/browse/MTA-1900
> :bug: lengthen term width to fit associated archetypes text

- client/src/app/components/questions-table/questions-table.tsx
https://issues.redhat.com/browse/MTA-1881
> :bug: Disable pagination for questionnaire summary

- client/src/app/pages/applications/applications-table/applications-table.tsx
https://issues.redhat.com/browse/MTA-1903
> :bug: Address required manage credential scopes

- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
[[Regression][Migration wave] False error when clicking on a date picker for the first time on the create wizard](https://issues.redhat.com/browse/MTA-1871)
> :bug: Update validation method to address datepicker event firing

- client/src/app/api/rest.ts
- client/src/app/components/SimpleDocumentViewer.css
- client/src/app/components/SimpleDocumentViewer.tsx
- client/src/app/pages/applications/applications-table/applications-table.tsx
- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
- client/src/app/queries/tasks.ts
- Adds support for the merged flag for getTasksById get request
> :sparkles: Support for analysis merged flag

- client/src/app/pages/assessment/components/assessment-actions/components/dynamic-assessment-actions-row.tsx
https://issues.redhat.com/browse/MTA-1935
> :bug: Fix create assessment logic to prevent 409 conflicts

- client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx
> :bug: Allow save as draft when all questions answered

- client/src/app/pages/archetypes/archetypes-page.tsx
- client/src/app/pages/archetypes/components/archetype-description-column.tsx
https://issues.redhat.com/browse/MTA-1921
> :bug: Truncate archatype description

- client/public/locales/en/translation.json
https://github.com/konveyor/tackle2-ui/pull/1620
> :bug: Missing translation for import summary

- client/src/app/components/questionnaire-summary/questionnaire-summary.tsx
https://issues.redhat.com/browse/MTA-1906
> :bug: remove unecessary warning

- client/public/locales/en/translation.json
- client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx
https://issues.redhat.com/browse/MTA-1940
> :bug: Update close messsage when no questions answered

- client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- client/src/app/pages/migration-targets/components/custom-target-form.tsx
Helps address https://issues.redhat.com/browse/MTA-1456
> :bug: remove hardcoded custom label

- client/src/app/pages/archetypes/archetypes-page.tsx
Resolves https://issues.redhat.com/browse/MTA-1893
> :bug: Hide create and kebab when no valid permissions on archetypes page

- client/src/app/pages/migration-waves/components/migration-wave-form.tsx
https://issues.redhat.com/browse/MTA-1871
> :bug: Add range styles and remove initial validation for end date

- client/src/app/components/IconedStatus.tsx
- client/src/app/pages/applications/components/application-assessment-status/application-assessment-status.tsx
- client/src/app/pages/applications/components/application-review-status/application-review-status.tsx
https://issues.redhat.com/browse/MTA-1878
https://issues.redhat.com/browse/MTA-1954
> :bug: Address in progress inherited status gap

- client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
https://issues.redhat.com/browse/MTA-1963
> :bug: Add missing label group for app drawer

- client/public/locales/en/translation.json
- client/src/app/pages/reports/components/application-landscape/application-landscape.tsx
https://issues.redhat.com/browse/MTA-1955
> :bug: Account for unknown risk in landscape view

- client/src/app/pages/applications/applications-table/applications-table.tsx
- client/src/app/rbac.ts
- Addresses an issue with the analysis details permissions.
analysis:get -> analyses:get
> :bug: Fix analyses details required permissions

- client/src/app/pages/issues/issue-detail-drawer/issue-affected-files-table.tsx
https://issues.redhat.com/browse/MTA-1961
> :bug: Handle wrap of long file paths

- client/src/app/pages/migration-waves/components/stakeholders-table.tsx
- client/src/app/pages/migration-waves/components/wave-applications-table.tsx
Resolves https://issues.redhat.com/browse/MTA-1790
> :bug: Fix wave subtable pagination

- client/src/app/queries/questionnaires.ts
https://issues.redhat.com/browse/MTA-1721
> :bug: Remove unneccessary metadata

- client/src/app/components/KebabDropdown.tsx
- client/src/app/pages/applications/applications-table/applications-table.tsx
https://issues.redhat.com/browse/MTA-1807
> :bug: Reuse toggle component for apps table

- client/src/app/pages/applications/applications-table/applications-table.tsx
> :bug: Cherry pick PR 1688

- client/src/app/pages/applications/applications-table/applications-table.tsx
- client/src/app/pages/applications/components/application-assessment-status/application-assessment-status.tsx
- Replaces erroneous not available status that is shown when no assessments are available on an app
> :bug: Adds spinner for isLoading prop in asessment status component

- client/src/app/pages/applications/components/application-assessment-status/application-assessment-status.tsx
[App 'Assessment' status shows Completed and Inheritance indicator icon even when not associated with archetypes](https://issues.redhat.com/browse/MTA-2354)
> :bug: Consider only inherited archetypes when computing status

- client/src/app/utils/rules-utils.ts
Reference-Url: https://issues.redhat.com/browse/MTA-2003
> :bug: Count custom rules imported from yaml file

- client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx
> :sparkles: Add deleteChipGroup handler

- .github/workflows/image-build.yaml
- .github/workflows/pr-closed.yaml
Apply github actions changes to the release-0.3 branch:
- #1759
- #1746
> :seedling: [release-0.3] Backport github action changes

- client/src/app/components/Autocomplete.tsx
Resolves https://issues.redhat.com/browse/MTA-2400
> :bug: Filter pre-existing selections from options

- client/src/app/layout/HeaderApp/SSOMenu.tsx
Reverts konveyor/tackle2-ui#1786 
This PR breaks logout functionality.
> :ghost: Revert ":bug: sso-actions-toggle: Adding onBlur event (#1766)"

- client/src/app/layout/HeaderApp/SSOMenu.tsx
Resolves: https://issues.redhat.com/browse/MTA-1578
> :bug: Add onOpenChange prop to Dropdown component for better state management

- client/src/app/pages/issues/helpers.ts
- client/src/app/utils/utils.ts
Resolves: #1754
Resolves: https://issues.redhat.com/browse/MTA-2560
> :seedling: MTA-2560: Use multi select filter for application names (#1771)

- client/src/app/pages/applications/components/application-tags/application-tags.tsx
Resolves: https://issues.redhat.com/browse/MTA-2287
> :bug:  Capitalize first letter of tag source

- README.md
Updated the variable to export  before running Konveyor with keycloak authentication enabled
> :book: Update README

- client/src/app/queries/assessments.ts
Resolves https://issues.redhat.com/browse/MTA-2616
Regression caused by: https://github.com/konveyor/tackle2-ui/pull/1811/files#diff-ecd17d80b98373a12f2bff08592b3c11fd40b31658c42eaec589f45e05d9714cL123
> :bug: Address retake regression

- client/src/app/pages/controls/tags/tags.tsx
Resolves: https://issues.redhat.com/browse/MTA-2186
> :bug: Fallback to tag category name for empty categories

- client/package.json
- client/src/app/pages/applications/components/application-form/__tests__/application-form.test.tsx
- client/src/app/pages/identities/components/identity-form/__tests__/identity-form.test.tsx
- package-lock.json
Resolves https://issues.redhat.com/browse/MTA-1698
Resolves https://issues.redhat.com/browse/MTA-1899
https://www.npmjs.com/package/@testing-library/jest-dom 
https://stackoverflow.com/a/77375453
> :bug: Update css-tools via react testing library dep bump

- client/src/app/pages/applications/applications-table/applications-table.tsx
- client/src/app/queries/applications.ts
After successful import re-enable useFetchApplications() hook for the next 15 seconds.
Resolves: https://issues.redhat.com/browse/MTA-2451
Cherry-picked from: https://github.com/konveyor/tackle2-ui/pull/1856
> :bug: [backport release-0.3] Re-enable fetching applications after application import

- client/src/app/pages/controls/tags/tags.tsx
Resolves https://issues.redhat.com/browse/MTA-2681
> :bug: Column name change to tagCategory

- OWNERS.md
> :ghost: Add OWNERS.md

- client/src/app/pages/tasks/tasks-page.tsx
> :bug: Refresh tasks page every 5 seconds

- client/package.json
- client/src/app/pages/applications/applications-table/applications-table.tsx
- package-lock.json
Includes:
- Basic refactoring of applications-table.tsx
- Add radash as a dependency for future use
Pre-work for #1985
> :seedling: refactor application table

- package-lock.json
Updated the database after starting to see a few DB out-of-date warnings.
> :ghost: Update browserslist/caniuse DB

- client/src/app/components/FilterToolbar/SelectFilterControl.tsx
Resolves: https://github.com/konveyor/tackle2-ui/issues/2094
> :bug: Fix closing filter chips created via SelectFilterControl

- client/src/app/pages/applications/applications-table/applications-table.tsx
Resolves: https://issues.redhat.com/browse/MTA-4158
> :bug: Ensure task existence before checking the state

- README.md
- docs/local-minikube-setup.md
- hack/README.md
Update typos and formatting in docs
> :book: Fix some typos in readme and docs

- package-lock.json
- package.json
Remove the unused type-fest dependency.  It can be added back later if needed.
> :ghost: remove unused type-fest dep

- client/package.json
- client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- client/src/app/pages/applications/analysis-wizard/schema.ts
- client/src/app/pages/applications/components/application-form/__tests__/application-form.test.tsx
- client/src/app/pages/applications/components/application-form/application-form.tsx
- client/src/app/pages/migration-targets/components/custom-target-form.tsx
- client/src/app/pages/migration-waves/components/manage-applications-form.tsx
- client/src/app/test-config/setupTests.ts
- client/src/app/utils/utils.test.ts
- client/src/app/utils/utils.ts
- client/src/app/yup.ts
- client/src/index.tsx
- package-lock.json
Resolves: https://issues.redhat.com/browse/MTA-5385
https://github.com/konveyor/operator/issues/441
Covers repository URL strings in:
- Application source code, source repository
- Application analysis wizard, custom rules step, repository tab, source repository
- Custom migration targets, Retrieve from a repository, source repository
Use [git-url-parse](https://github.com/IonicaBizau/git-url-parse) to handle git URLs.  Subversion URLs are handled by the same RegEx and previous.
> :bug: Fix Configuring a ssh connection to a git repository fails
