Dockerfile, pkg/client/package.json
This allows to build client and server directly from their respective directories.
This won't be necessary once npm workspace is in place (and supported by cachito)
=> Dockerfile: Build without workspace

pkg/client/config/webpack.common.js
Give the plugin a big more memory to avoid crash after few reloads (stack overflow)
=> ForkTsCheckerWebpackPlugin: tune memory

pkg/client/src/app/api/models.tsx, pkg/client/src/app/api/rest.tsx, pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx, pkg/client/src/app/store/alert/actions.tsx
Completely set up custom rules:
- Uploads custom rules files
- Makes rules optional for task.data
Adds generic rest request for file uploads to be used by both binary and custom rules
Harmonize notifications for Task creation (wizard initialization), custom rules uploads, task data set (update) and submission.
=> Set ouptut, mode.artifact and rules path uploads

pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx
Still need to find a fix for deep type checking against field values. This fixes the circular dep error that keeps popping up. https://github.com/react-hook-form/react-hook-form/discussions/7764
=> Loosen types on field values to fix ts error

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/pages/applications/analysis-wizard/components/select-card.tsx, pkg/client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Makes sure targets selected are properly active when going back and forth between wizard steps.
=> Wizard: SetTargets to remember selection

pkg/client/src/app/api/rest.tsx, pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, pkg/client/src/app/queries/applications.ts, pkg/client/src/app/queries/taskgroups.ts, pkg/client/src/app/queries/tasks.ts
Fixes the binary file upload for single application analysis case.
Recent change using taskgroups API needs to upload file with `taskgroups` and not through `tasks` API.
=> Wizard: Single app requires `taskgroups` to upload file

pkg/client/public/locales/en/translation.json, pkg/client/src/app/pages/identities/components/identity-form.tsx, pkg/client/src/app/pages/identities/identities.tsx, pkg/client/src/app/queries/identities.ts
https://issues.redhat.com/browse/TACKLE-427 
- Adds inline form validation
- converts identities to queries for cache usage & general flow enhancements
=> Add inline form validation for duplicates & convert identities to queries

pkg/client/src/app/pages/controls/tags/tags.tsx, pkg/client/src/app/shared/components/ConditionalTooltip.tsx, pkg/client/src/app/shared/components/app-table-action-buttons/app-table-action-buttons.tsx
- Disables the delete button for tag types when tags are attached to it.
- Display a user friendly error notification "Cannot delete a used tag" when trying to delete a tag that is used .
For the latter, a long term solution to disable delete tag button would require to fetch applications to determine if the tag to be deleted is used or not. This would require a bigger effort because Tackle 1 UI didn't have foreign key constraint enabled for tags and tag types and therefore wasn't designed to handle it.
https://issues.redhat.com/projects/TACKLE/issues/TACKLE-446
=> Tags/TagTypes: Workaround Foreign key constraint error

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- When you load the app and click analyze on a previously run analysis item in the app analyze table, the app crashes due to an issue with the pf implementation of wizard modal. 
- Closes #107
=> Fix infinite wizard re-render

pkg/client/src/app/pages/controls/tags/tags.tsx
[Tags: Deleting attached "Tag name" from the "Tag Type" the expand shows the "Tag name" field](https://issues.redhat.com/browse/TACKLE-447)
=> Bug: Collapse tagtype if no tags attached in table

.github/workflows/ci-actions.yml, pkg/client/.eslintrc, pkg/client/.prettierrc, pkg/client/package-lock.json, pkg/client/package.json
Replace lint-stagged with eslint configuration without any impact for now as only warnings would be generated allowing us to gradually make changes.
=> Use npm eslint instead of lint-stagged

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/queries/taskgroups.ts
This is a follow up for https://github.com/konveyor/tackle2-ui/pull/149
To make sure there is no existing taskgroup to delete when swapping between modes.
=> Adjust taskgroup deletion when changing mode

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/pages/applications/analysis-wizard/review.tsx, pkg/client/src/app/pages/applications/analysis-wizard/set-mode.tsx, pkg/client/src/app/pages/applications/analysis-wizard/utils.ts
https://github.com/konveyor/tackle2-ui/pull/164 follow-up
Besides the change for the mode value, I removed mode from the reack-hook-form at the wizard level on above PR, but was still used in the review.
Basically we'll gradually remove all formValues at the wizard level to keep the needed one only at step level (like set-options).
But we'll do that in a separate PR.
=> Mode object change

pkg/client/src/app/pages/reports/components/adoption-candidate-graph/adoption-candidate-graph.tsx, pkg/client/src/app/pages/reports/components/adoption-candidate-graph/cartesian-square.tsx
There was reported overlapping of application circle and adoption candidate chart description. Updating paddings to make title text readable.
Note, this is my first commit to the Tackle2 UI, I'm happy for every possible feedback. (the change might be naive, but looks to me to solving the reported issue). Sample screenshots attached in comments.
https://issues.redhat.com/browse/TACKLE-529
=> Update padding to display Report adoption correctly

pkg/client/src/app/pages/applications/components/application-form/application-form.tsx
Allow repo url to be empty after latest validation changes
=> Repository url always required bug fix

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
In the single application use case for analysis the wizard first step (set mode) next button cannot be enabled unless a binary file has been uploaded, so isMutating is false indicating there is no upload in progress and the `artifact` field is allocated.
This is taken care of the first part of the following condition, the OR part covers multiple applications use case, therefore the number of analyze able applications is greater than one.
```
enableNext:
(analyzeableApplications.length === 1 &&
!isMutating &&
artifact !== "") ||
analyzeableApplications.length > 1,
```
=> Single application analysis: no next unless artifact

pkg/client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx, pkg/client/src/app/utils/utils.ts
Resolves https://issues.redhat.com/projects/TACKLE/issues/TACKLE-451
Also simplifies and abstracts the logic from the existing `duplicateNameCheck` into a `duplicateFieldCheck` function that can check based on any field. The type signature uses `keyof T` to enforce that the field key you pass is present in the objects you're checking.
=> TACKLE-451: Check for duplicate email address when creating a stakeholder

pkg/client/src/app/pages/identities/components/identity-form.tsx
Resolves https://issues.redhat.com/projects/TACKLE/issues/TACKLE-537.
The bug here was caused by the Yup validation of the Maven settings field being unaware that its value is encrypted when prefilling for editing. The field was failing validation because its encrypted form cannot be parsed as XML, and that validation error was not appearing on the screen because the form is configured to only update the validation errors when a field changes (not when its initial value is set -- this is done so that "this field is required" doesn't appear on all required fields when a form first renders).
The solution is to short circuit the validation if the field's value has not changed relative to the credential being edited. If it was valid before, we assume it is still valid. If the field has been …
=> TACKLE-537: Fix validation on encrypted Maven settings field so we can save edits, fix SCM private key field to behave consistently

pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, pkg/client/src/app/pages/applications/applicationsFilter.ts
- Moves select/expand state into shared applications filter. This allows selected/expanded state to respect filter/sort logic
=> Fix applications filter

pkg/client/src/app/pages/identities/components/identity-form.tsx
Resolves https://issues.redhat.com/browse/TACKLE-538
=> TACKLE-538: Only allow toggling password visibility if the password is not encrypted (contains a fresh user-entered value)

pkg/client/src/app/api/rest.tsx, pkg/client/src/app/pages/applications/manage-imports-details/manage-imports-details.tsx, pkg/client/src/app/queries/imports.ts
Application import errors list showed all imports from all ImportSummaries and both sucessful&errored.
Updating query to ask API only for Imports for given ImportSummary and valid field is false (as API is expecting it).
Fixes https://issues.redhat.com/browse/TACKLE-589
=> Fix application import errors list

pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
Resolves https://issues.redhat.com/projects/TACKLE/issues/TACKLE-566.
Sorting was actually working properly in this view except that `useSortState` uses a straight `<` / `>` comparison on the strings which is sorting by unicode character id order rather than alphabetical order. This means all uppercase letters are considered to come before all lowercase letters.
Calling `.toLowerCase()` on the values being compared fixes this, but it might be worth revisiting this to see if `localeCompare` should be used inside `useSortState` to prevent this problem in the future. This is something I was considering in https://github.com/konveyor/lib-ui/pull/73#issuecomment-894476380 which I'll try to return to.
=> TACKLE-566: Case-insensitive sorting in 'manage imports' table

pkg/client/src/app/pages/applications/components/application-list-expanded-area/application-list-expanded-area-analysis.tsx, pkg/client/src/app/queries/tasks.ts
Resolves https://issues.redhat.com/projects/TACKLE/issues/TACKLE-554 and https://issues.redhat.com/projects/TACKLE/issues/TACKLE-559.
The main issue here was the `isReport` state which was being set to true in a `useEffect` whenever the latest analysis task entered the "Succeeded" state, but was never set to false again afterwards. We don't need this state at all because we can simply use the current status of the latest task for each application to drive the rendering logic. So we'll only get a report link if the latest task is still in the succeeded state.
The other changes here in `useFetchTasks` were part of a prior attempt to troubleshoot and aren't required to fix the bug, but I decided to keep them because they are still an improvement:
* The `tasks` state in that hook was …
=> TACKLE-554 / TACKLE-559: Ensure Analysis report details are always up-to-date

pkg/client/src/app/pages/proxies/proxy-form.tsx
Requested by @ibragins . Currently it is not possible for QE automation to distinguish between the dropdown toggles for HTTP and HTTPS credentials in the proxy configuration. Adding `toggleId` to each of these solves the problem.
=> QE: Add unique ids to Select toggles for proxy credentials selections

pkg/client/src/app/pages/applications/components/import-applications-form/import-applications-form.tsx, pkg/client/src/app/queries/imports.ts
- Disables import button & allows clearing of the import error within the upload import csv modal. 
https://issues.redhat.com/browse/TACKLE-616
=> TACKLE-616: Close modal on import with validation errors & show notification with error

pkg/client/package-lock.json, pkg/client/package.json, pkg/client/public/locales/en/translation.json, pkg/client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap, pkg/client/src/app/layout/HeaderApp/tests/__snapshots__/HeaderApp.test.tsx.snap, pkg/client/src/app/layout/SidebarApp/tests/__snapshots__/SidebarApp.test.tsx.snap, pkg/client/src/app/pages/applications/application-assessment/components/application-assessment-page/__snapshots__/application-assessment-page-header.test.tsx.snap, pkg/client/src/app/pages/applications/application-assessment/components/application-assessment-page/__snapshots__/application-assessment-page.test.tsx.snap, pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, pkg/client/src/app/pages/applications/components/application-assessment/application-assessment.tsx, pkg/client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx, pkg/client/src/app/queries/applications.ts, pkg/client/src/app/queries/assessments.ts, pkg/client/src/app/queries/identities.ts, pkg/client/src/app/queries/imports.ts, pkg/client/src/app/queries/proxies.ts, pkg/client/src/app/queries/reviews.ts, pkg/client/src/app/queries/stakeholders.ts, pkg/client/src/app/queries/tags.ts, pkg/client/src/app/queries/volumes.ts, pkg/client/src/app/shared/components/app-table/tests/__snapshots__/state-no-data.test.tsx.snap, pkg/client/src/app/shared/components/page-header/tests/__snapshots__/page-header.test.tsx.snap, pkg/client/src/app/shared/components/toolbar-search-filter/__snapshots__/toolbar-search-filter.test.tsx.snap, pkg/client/src/app/shared/containers/bulk-copy-notifications-container/bulk-copy-notifications-container.tsx
https://issues.redhat.com/browse/TACKLE-512
There were two problems here:
* We weren't triggering a refetch of assessments when completing the discard action in the table.
* Application assessments were being fetched and stored in state local to the table using `useFetchMultiple`, but the bulk copy is an asynchronous task that is later watched elsewhere, so there is no way for the table to know when it is complete and trigger a refetch of this local state.
To solve these, I refactored the assessments fetch logic to use react-query's `useQueries` so that it is stored in the global `queryClient` cache. That way, we can invalidate those queries from wherever we want, which I've done from the notifications container (because that was already watching for this bulk copy to complete. Also, …
=> TACKLE-512: Refetch application assessments and reviews properly when copying/discarding (+ upgrade TypeScript)

pkg/client/src/app/api/rest.tsx, pkg/client/src/app/pages/applications/components/application-form/application-form.tsx, pkg/client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx, pkg/client/src/app/pages/controls/tags/components/tag-form/tag-form.tsx, pkg/client/src/app/pages/identities/components/identity-form.tsx, pkg/client/src/app/queries/applications.ts, pkg/client/src/app/queries/identities.ts, pkg/client/src/app/queries/proxies.ts, pkg/client/src/app/queries/reviews.ts, pkg/client/src/app/queries/stakeholders.ts, pkg/client/src/app/queries/tags.ts, pkg/client/src/app/queries/volumes.ts, pkg/client/src/app/shared/hooks/useFetchApplications/useFetchApplications.ts
Turns out TypeScript didn't save me from this particular foot-gun. We were using `queryClient.getQueryData()` in a few places, which returns `unknown`, so TS couldn't catch that I had inadvertently changed the structure of data in the cache with #261. This PR removes that direct cache usage, but it also ensures Axios objects will not end up in the cache so that the cache contains the same bare data arrays that we return from our query hooks (in case we need to directly use the cache for some reason in the future).
=> Fix regressions related to useQuery refactoring

pkg/client/src/app/api/rest.tsx, pkg/client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, pkg/client/src/app/queries/taskgroups.ts
- Displays the uploaded file name when navigating backwards after initial file upload
- Deletes file from bucket when removing from the ui. 
https://issues.redhat.com/browse/TACKLE-607
=> TACKLE-607: Display uploaded file on back nav

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- This warning does not apply on  the upload binary screen. The next button being disabled should be enough to notify that they have not uploaded a binary.
=> Remove applications cannot be analyzed message for upload binary mode

pkg/client/src/app/pages/identities/identities.tsx
Replacing User placeholder with the API provided createUser field.
Related to https://github.com/konveyor/tackle2-hub/pull/103 but can be merged before it (the field would be empty until Hub API provides the username).
https://issues.redhat.com/browse/TACKLE-424
=> Enable CreateUser field in Identities

pkg/client/src/app/pages/applications/applicationsFilter.ts, pkg/client/src/app/pages/controls/tags/tags.tsx, pkg/client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx
https://issues.redhat.com/browse/TACKLE-645
Checks for undefined key name when building filter options list. Also, filter out empty tag names for unassociated tag types.  An empty value was being populated in the tag name filter when a tag type without a tag is added.
=> TACKLE-645: Check for undefined tag name causing app to crash

pkg/client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx, pkg/client/src/app/shared/components/FilterToolbar/SelectFilterControl.tsx
For QE: Adds a unique id on the toggle button for selecting filter values in each category for select and multiselect filter types.
The filter category key is used, followed by `-filter-value-select`. For example, `#tags-filter-value-select`. This may not exactly match the name of the filter shown to the user, because to guarantee uniqueness it is based on the underlying filter key.
cc @sshveta
=> Add unique ids on filter value select toggle buttons

pkg/client/src/app/common/rbac-utils.tsx
When the `isAuthRequired` constant (based on the `AUTH_REQUIRED` environment variable) was added in https://github.com/konveyor/tackle2-ui/pull/166/files#diff-d6a22eefc16798dd8630ea7dbf7eea49a64e64949c9a7b6a4fc825b45e6cc7dfR14, the only reusable place it was referenced was in the `<RBAC>` component. This meant any other code that directly called the `checkAccess()` function (which is used inside `<RBAC>`) were not affected.
For example, the actions kebab above the applications table is shown based on a `checkAccess` call [here](https://github.com/konveyor/tackle2-ui/blob/065711b870291c759c04604dfc6f73fbd0f0b17e/pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx#L312-L317) which circumvents the `<RBAC>` component, so currently it does not …
=> Fix AUTH_REQUIRED flag not affecting direct calls to checkAccess function

pkg/client/src/app/common/RouteWrapper.tsx, pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx, pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Follow-up to https://github.com/konveyor/tackle2-ui/pull/283.
Now that the `isAuthRequired` check is part of `checkAccess()`, any place in the UI that was checking both no longer needs to care about `isAuthRequired`. This PR removes it from those places. To ensure we are always calling `checkAccess()` even when the token is undefined, it also replaces guards like:
```ts
let userRoles = token?.realm_access?.roles,
access = userRoles && checkAccess(userRoles, roles);
```
with:
```ts
let userRoles = token?.realm_access?.roles || [],
access = checkAccess(userRoles, roles);
```
If the token is defined this makes no difference, but if the token is undefined the `userRoles` array will be `[]` and the `checkAccess` function will still be called (when called with an empty array, it effectively …
=> TACKLE-661: Ensure `checkAccess` is called even when token is undefined, remove unnecessary references to isAuthRequired

pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, pkg/client/src/app/rbac.ts
See #284. This solves the same problem described there in a couple more places.
Needed for https://issues.redhat.com/browse/TACKLE-661
=> TACKLE-661: Ensure `checkAccess` is called even when token is undefined (missed cases from PR #284)

pkg/client/src/app/common/RouteWrapper.tsx, pkg/client/src/app/common/rbac-utils.tsx, pkg/client/src/app/layout/SidebarApp/SidebarApp.tsx, pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, pkg/client/src/app/rbac.ts
Backports #283, #284 and #285 to v2.0.0.
> When the isAuthRequired constant (based on the AUTH_REQUIRED environment variable) was added in https://github.com/konveyor/tackle2-ui/pull/166/files#diff-d6a22eefc16798dd8630ea7dbf7eea49a64e64949c9a7b6a4fc825b45e6cc7dfR14, the only reusable place it was referenced was in the `<RBAC>` component. This meant any other code that directly called the `checkAccess()` function (which is used inside `<RBAC>`) were not affected.
> 
> For example, the actions kebab above the applications table is shown based on a `checkAccess` call [here](https://github.com/konveyor/tackle2-ui/blob/065711b870291c759c04604dfc6f73fbd0f0b17e/pkg/client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx#L312-L317) which circumvents the …
=> [Backport - v2.0.0] TACKLE-661: Ensure all RBAC checks always respect `AUTH_REQUIRED=false`

pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
Resolves part of https://issues.redhat.com/browse/TACKLE-667.
The other part of that issue is a problem with the RBAC scopes defined in the migrator role (migrators have write access to dependencies, they shouldn't). @jortel is following up on that part.
=> TACKLE-667: Properly restrict application assessment write actions by RBAC scope

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx, pkg/client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
Use updated version of "file upload multiple" from PF
Use `customFileHandler` prop to have a granular control of duplicate files and XML validation (against schema).
Fixes ability to remove a file from upload list. See https://issues.redhat.com/browse/TACKLE-665 for details.
Note: Latest "file upload multiple" doesn't use a modal to warn about unsupported file selected for upload because files without the correct extension are simply ignored.
=> TACKLE-665: AddCustomRules: use customFileHandler

pkg/client/src/app/pages/proxies/proxy-form.tsx
Currently, an empty dropdown is rendered when there are no valid proxy credentials available to add.
This PR disables the dropdown when no valid proxy cred is available.
=> Disable proxy-cred add if no valid cred exists

pkg/client/src/app/pages/applications/analysis-wizard/__tests__/analysis-wizard.test.tsx, pkg/client/src/app/pages/applications/components/application-form/__tests__/application-form.test.tsx, pkg/client/src/app/pages/applications/components/application-form/application-form.tsx, pkg/client/src/app/pages/proxies/__tests__/proxy-form.test.tsx
One of the assertions was not wrapped in a wait for which caused the test to fail. For these async tests, we have to add a timeout if a user event is called that triggers an async render.
=> TESTS: Fix application form tests broken on main

pkg/client/public/locales/en/translation.json, pkg/client/public/locales/es/translation.json, pkg/client/src/app/common/TooltipTitle.tsx, pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
Application CSV import page imports counts records have two expected types - Application and Dependency.
In order to not confuse user with misleading amount of applications, adding tooltip to related table columns as suggested by Nandini.
Fixes https://issues.redhat.com/browse/TACKLE-631
=> Add Applications and deps tooltip to Import page

pkg/client/public/locales/en/translation.json, pkg/client/public/locales/es/translation.json, pkg/client/src/app/common/TooltipTitle.tsx, pkg/client/src/app/pages/applications/manage-imports/manage-imports.tsx
2.1.0 backport of https://github.com/konveyor/tackle2-ui/pull/345
* Add Applications and deps tooltip to Import page
Application CSV import page imports counts records have two expected types
- Application and Dependency. In order to not confuse user with
misleading amount of applications, adding tooltip to related table
columns as suggested by Nandini.
Fixes https://issues.redhat.com/browse/TACKLE-631
* Add tooltip title component
Co-authored-by: Ian Bolton <ibolton@redhat.com>
=> [ Backport 2.1.0 ] Add Applications and deps tooltip to Import page

pkg/client/public/locales/en/translation.json, pkg/client/public/locales/es/translation.json
Adding more descriptive tooltip title to CSV import table mentioning
that rejected records might include also records with unwknown record
type (not application or dependency).
Fixes https://issues.redhat.com/browse/TACKLE-634
=> TACKLE-634: Mention unknown records in Import rejected title

pkg/client/public/locales/en/translation.json, pkg/client/public/locales/es/translation.json
2.1.0 backport of https://github.com/konveyor/tackle2-ui/pull/349
Adding more descriptive tooltip title to CSV import table mentioning
that rejected records might include also records with unwknown record
type (not application or dependency).
Fixes https://issues.redhat.com/browse/TACKLE-634
=> [Backport - 2.1.0] -TACKLE-634: Mention unknown records in Import rejected title

pkg/client/i18next-parser.config.js, pkg/client/public/locales/en/translation.json, pkg/client/public/locales/es/translation.json, pkg/client/src/app/pages/identities/identities.tsx
* i18n error for identity
* Stop autoremoving entries in language.json
=> [Backport 2.1.0]  TACKLE-xxx: i18n missing entry for "credential"  (#354)

pkg/client/src/app/pages/applications/components/application-tags/application-tags.tsx
Line [29](https://github.com/konveyor/tackle2-ui/compare/main...ibolton336:tackle-748?expand=1#diff-212c4e915d8a7bd1a1b8dce1ddfee220f3eb215d073f52c47feffd65f2a03d42R29) was causing the ui logic to short-circuit when tags are all removed from an application. This PR adds in a condition to reset the tags to default state if no tags are attached to an application.
=> TACKLE-748: Reset tags when they are all cleared from an application

pkg/client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, pkg/client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
When selecting ALL applications in the bulk copy assessment/review form, the source application was being selected. This led to the api not receiving the correct list of apps & caused some errors with overwriting the source application data. 
This PR also prevents applications without an assessmend & review from being copied from. [See here](https://github.com/konveyor/tackle2-ui/pull/387/files#diff-38b35274202426ae47eb724b71f4d5dc739f74351444c5bb38bfad24d9d1c636R394)
=> TACKLE-759: Filter out current app from copy to list when selecting all

pkg/client/src/app/App.tsx, pkg/client/src/app/common/KeycloakProvider.tsx, pkg/client/src/app/queries/cookies.ts, pkg/server/setupProxy.js
Addresses #393 
- Change token expiration to 1 hour to reduce auto logout token expiry redirects on 3rd party api served external html pages
- Remove useFetchCookie query hook in favor of leaning on keycloak-js's internal token initialization logic. Since we run the keycloak token validation check on every outgoing Axios request, we can refresh the cookie at this time if it is stale. 
- Automatically redirect to the main apps home page if an authentication error occurs on a 3rd party api served external html page. This will trigger the keycloak authentication init logic upon routing here. 
Depends on: https://github.com/konveyor/tackle2-ui/pull/401
There is an issue with navigating to the /login route. A blank page is rendered and requires the user to click a navigation item to continue …
=> Cookie management improvements

pkg/client/package-lock.json, pkg/client/package.json, pkg/client/src/app/pages/applications/applicationsFilter.ts, pkg/client/src/app/shared/hooks/useFilterState.ts
Adds an optional `storageKey` argument to `useFilterState` and uses it on the application inventory tables. When a `storageKey` is passed to `useFilterState` like this, the filter values will be persisted to sessionStorage using the new `useSessionStorage` hook added to lib-ui in https://github.com/migtools/lib-ui/pull/114. If `storageKey` is not passed, regular React state will be used instead.
Filters set on either app inventory page will now be persisted for the lifetime of the current browser tab (reloading the page or navigating away/back won't clear them, but closing and reopening the tab will). Separate tabs can have separate filter values because they don't share session storage.
=> Persist app inventory page filters to `sessionStorage`

.gitignore, server/package.json
The production build is currently broken due to a missing dependency that was never moved over when we decided to use the production flag for production builds. I have tested this with my image quay.io/ibolton/tackle2-ui:latest with success.
=> Fix production error

package-lock.json
FYI @gildub @ibolton336 when I run `npm install` now (using npm 8.15.0) I get some changes to the package-lock.json that differ from what's currently tracked in git. It looks like just this `devOptional` flag got removed from a few places. Not sure what it means...
=> Lockfile changes on npm install after workspaces refactor

client/package.json, package-lock.json
As part of #400, `css-loader` was upgraded from `^5.2.6` to `^6.7.1`. Something about this upgrade seems to have caused our PatternFly Fonts to fail to load.
Troubleshooting this with @ibolton336, I tried to `curl` one of the font files exposed by webpack-dev-server by copying its path from the browser dev tools network tab, and I found that its contents were not binary font data, but JS:
```
$ curl http://localhost:8080/101eb68a37edfa8a2f9a.woff
export default __webpack_public_path__ + "fonts/overpass-bold.woff";
```
This indicated that it was something about a loader change, and `css-loader` was the only webpack loader with a recent major version bump. Indeed, downgrading it seems to have solved the problem. I'm not certain I understand why, though... here are the breaking changes …
=> Downgrade css-loader to 5.2.7 to fix font loading issues

client/src/app/pages/applications/applicationsFilter.ts, client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/shared/components/FilterToolbar/SelectFilterControl.tsx
I've been seeing this warning whenever I'm on the Application Inventory page:
I found that this is happening because when you have applications with no associated business service, the business service filter dropdown's `selectOptions` array ends up with an element `{ key: undefined, value: undefined }`. To fix this, we can filter out any apps with no business service before mapping over apps to produce this list of filter options.
However, that still results in a Select dropdown with no options inside which looks broken when you click on it. This PR also disables the dropdowns for SelectFilterControl and MultiselectFilterControl if there are no options to select.
Before:
After:
cc @gildub @ibolton336
=> Fix React warning in Application table filters: don't generate empty select options, disable dropdown when there are no options

client/src/app/Constants.ts, client/src/app/env.ts, client/src/app/keycloak.ts
Instead of defining `IEnvVars` as an interface, this defines an object `ENV_VAR_DEFAULTS` as a constant, defines the `EnvVarKey` type based on its keys, and defines the `EnvVars` type as `Record<EnvVarKey, string>`. That way, we can map over `Object.keys(ENV_VAR_DEFAULTS)` at run-time to patch in any vars missing from `window._env` based on a set of defaults, and preserve the type safety (the only valid env var keys are the ones defined in `ENV_VAR_DEFAULTS`).
Moves all this to a separate `env.ts` file since it's a bit more verbose now.
This also uses `{ ...window._env }` to define `ENV` before we patch in the defaults for missing vars, so that we can still inspect `window._env` in the console if we want to see exactly what was passed by the server (without defaults added).
=> Define defaults for missing ENV variables

client/src/app/common/KeycloakProvider.tsx, server/setupProxy.js
This change to [redirect unauthenticated hub routes ](https://github.com/konveyor/tackle2-ui/pull/397/files#diff-911dd5321bcea406fc2f0e84100123245e5286454fdaa310faa81506c6d106d6R34) has caused a regression with no_auth. 
This ^ change redirects the user back through the keycloak authentication when attempting to process unauthenticated requests to pathfinder from an externally served reports.html tab.
This PR adds a check for 'application/json header' before redirecting the users. This ensures when auth_required is set to false,  narrow the specific reports.html redirect down to only redirect unauthenticated text/html requests.
Additionally, this PR solves a bug with the keycloak refresh token not being equal to the set cookie in memory. This is because when keycloak refreshes a token, it …
=> Check for application/json headers before rerouting

client/package.json, package-lock.json
Align keycloak client keycloak-js to back-end version.
See  https://github.com/konveyor/tackle2-operator/pull/115
Using keycloak-js 18.0.1 as 18.0.2 is not available on npm.
=> Bump keycloak-js to 18.0.1

client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
Adds the missing tags filter from the bulk copy assessment form. https://issues.redhat.com/browse/TACKLE-822
=> TACKLE-822: Add tags filter to copy assessment form

client/src/app/pages/applications/manage-imports/manage-imports.tsx
Resolves https://issues.redhat.com/browse/TACKLE-811
Targeted for 2.1.2
=> TACKLE-811: Restore missing sort arrows on Manage Imports table

entrypoint.sh
- Update entrypoint.sh to import Kube API CA, Service CA and Custom Ingress CAs if they exist at runtime
- Necessary for RH-SSO integration which only listens on HTTPS with self serving certificates OCP generated, also will also support users with custom ingress CAs in their clusters
- Depends on https://github.com/konveyor/tackle2-operator/pull/117
- Target 2.1.2 release
Signed-off-by: Franco Bladilo <fbladilo@redhat.com>
=> Create CA certs bundle

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/applications/manage-imports/manage-imports.tsx, client/src/app/pages/controls/business-services/business-services.tsx, client/src/app/pages/controls/job-functions/job-functions.tsx, client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx, client/src/app/pages/controls/stakeholders/stakeholders.tsx, client/src/app/pages/controls/tags/tags.tsx, client/src/app/pages/identities/identities.tsx, client/src/app/shared/hooks/usePaginationState.ts
Fixes [TACKLE-772](https://issues.redhat.com/browse/TACKLE-772)
This was a regression caused by https://github.com/konveyor/tackle2-ui/pull/325, which fixed related issues [TACKLE-635](https://issues.redhat.com/browse/TACKLE-635) and [TACKLE-712](https://issues.redhat.com/browse/TACKLE-712). The original bug was that deleting an item never caused a page change, which left an unexpected empty state if the last item on a page was deleted. https://github.com/konveyor/tackle2-ui/pull/325 changed the behavior such that when an item is deleted, if it was the last item on the page the table will go back 1 page, else the table will go to the first page.
That `else` case was causing this regression. If the deleted item was not the last one on the page, we should stay on the page we were on rather …
=> TACKLE-772: On deleting a table item, remain on current page unless we deleted the last item on the page

.github/workflows/ci-actions.yml
Currently our backport PRs don't run our CI checks. This PR adds filter patterns to the `push` and `pull_request` branch conditions in our CI actions workflow so any PR targeting a release branch will run the CI checks (once this is backported).
`v[0-9]+.[0-9]+.[0-9]+` matches any branch name that is a semantic version beginning with `v`, such as our `v2.1.2`.
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
=> Run CI checks on PRs and merges to release branches

client/src/app/utils/utils.ts
- This PR accounts for the "error" field in the api error response object. This is needed to correctly parse the "cyclic dependencies are not allowed" error. 
Notes: We should add i18n for these special case errors that are passed from the api. The current string is:
I didn't want to change too much here is this is a regression bug. Something to consider for future releases, though.
=> TACKLE-814: Add error parsing check for cyclic deps error

client/src/app/common/KeyDisplayToggle.tsx, client/src/app/common/KeycloakProvider.tsx, client/src/app/common/TooltipTitle.tsx, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/components/add-custom-rules.tsx, client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/applications/analysis-wizard/review.tsx, client/src/app/pages/applications/analysis-wizard/set-mode.tsx, client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/analysis-wizard/set-scope.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/pages/applications/analysis-wizard/validation-wizard/sampleform.tsx, client/src/app/pages/applications/analysis-wizard/validation-wizard/validation-wizard.tsx, client/src/app/pages/identities/identities.tsx, client/src/app/pages/proxies/proxies.tsx, client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx, client/src/app/pages/repositories/Git.tsx, client/src/app/pages/repositories/Mvn.tsx, client/src/app/pages/repositories/Svn.tsx, client/src/app/shared/components/ConditionalTooltip.tsx, client/src/app/shared/components/no-data-empty-state/no-data-empty-state.tsx, client/src/app/shared/components/proposed-action-label/proposed-action-label.tsx, client/src/app/shared/components/risk-label/risk-label.tsx, client/src/app/shared/components/status-icon/status-icon.tsx, client/src/typings.d.ts
React.FC is actually an alias for React.FunctionComponent.
So either one can be used meanwhile let's be consistent.
This patch sets FC everywhere.
Signed-off-by: Gilles Dubreuil <gilles@redhat.com>
=> Use React.FC vs React.FunctionComponent

client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
=> Analysis wizard: fix translation key on 'Add rules' text in custom rules empty state

pkg/client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
=> [Backport v2.1.2] Analysis wizard: fix translation key on 'Add rules' text in custom rules empty state (#472)

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/set-options.tsx
Fixes a regression found by @djzager caused by https://github.com/konveyor/tackle2-ui/pull/468 (which fixed https://issues.redhat.com/browse/TACKLE-844).
Targets 2.1.2 since it fixes a regression that was backported (in https://github.com/konveyor/tackle2-ui/pull/471).
The problem here is that the text field we're validating here is transient; it is only to enter the text of a tag that may or may not be added to the exclusion list. So we need to validate a value that is entered in it if present, but it is also valid for the field to be empty. The validation added in #468 requires some text to remain in the field for the wizard to be submitted.
This PR fixes the issue by changing the `.min(2, ...)` validation to a regular expression which will match if the string is either empty or longer …
=> Fix regression: allow excluded rules tags field to be empty without losing validation

pkg/client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, pkg/client/src/app/pages/applications/analysis-wizard/set-options.tsx
=> [Backport v2.1.2] Fix regression: allow excluded rules tags field to be empty without losing validation

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/repositories/Mvn.tsx, client/src/app/queries/tasks.ts
Adds a `filters` argument to the `useFetchTasks` hook so that we can query only tasks that matter for a particular view. For now the only filter is `addon`, and it is only used in the Analysis table to filter on `{ addon: "windup" }`. These filters are applied BEFORE the selection logic in the query hook (finding the latest unique task per application).
cc @djzager
=> Only consider windup tasks on the Analysis table

client/src/app/shared/components/Notifications.tsx, client/src/app/shared/notifications-context.tsx
- Currently, you cannot dismiss a push notification that was created without a 'key' prop. Rather than adding this prop to all areas of the app, I changed the logic to use title for the key. 
- Adds a check for duplicate notifications before pushing
=> Bug fix: Prevent duplicate notifications & fix dismiss bug

client/src/app/pages/applications/components/application-list-expanded-area/application-risk.tsx, client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx, client/src/app/pages/reports/components/adoption-candidate-graph/adoption-candidate-graph.tsx, client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx, client/src/app/pages/reports/components/adoption-plan/adoption-plan.tsx, client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx, client/src/app/pages/reports/components/landscape/landscape.tsx, client/src/app/pages/repositories/Git.tsx, client/src/app/pages/repositories/Mvn.tsx, client/src/app/pages/repositories/Svn.tsx, client/src/app/queries/proxies.ts, client/src/app/queries/risks.ts
- Replaces dated Tackle 1.2 instances of useFetch- a custom fetch hook that implements common fetching utility functions. This logic can be easily replaced by react-query. 
- Should be merged before [this related PR. ](https://github.com/konveyor/tackle2-ui/pull/485 ) which replaces the  polling logic for bulk notification status with a react-query polling approach we have agreed on in the past.
=> [Tech debt] Move common useFetch to react query

client/src/app/queries/bulkcopy.ts
Fixes a bug causing indefinite review polling when bulk copying assessments without reviews.
=> Bug fix: Check if review exists before checking review result

client/src/app/pages/applications/components/bulk-copy-assessment-review-form/bulk-copy-assessment-review-form.tsx
Avoids following warning on BulkCopyAssessmentReviewForm:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `MultiselectFilterControl`. See https://reactjs.org/link/warning-keys for more information.
SelectOption@webpack-internal:///../node_modules/@patternfly/react-core/dist/esm/components/Select/SelectOption.js:27:9
MultiselectFilterControl@webpack-internal:///./src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx:7:34
FilterControl@webpack-internal:///./src/app/shared/components/FilterToolbar/FilterControl.tsx:10:23
```
=> Unique selectOptions name for MultiselectFilterControl

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts
Fix status and progress when, in the wizard, after an initial binary upload, going back into that first step so uploaded file details are properly displayed.
Little refactor since more recent version of MultipleFileUpload automatically filters out file types and upload file size from `dropzoneProps`.
This introduces a slight visual change.
Effectively now instead of getting an error when the file is too big, no file bigger than the limit is permitted for upload.
Therefore the user needs to be informed upfront what's the upload size limit: 
https://issues.redhat.com/browse/TACKLE-861
=> TACKLE-861: UploadBinary - Fix artifact state

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/set-mode.tsx, client/src/app/queries/taskgroups.ts
Taskgroup deletion and recreation is now handled by `onModeChange()`  which is passed down to set-mode" component in order to avoid using `useEffect()`.
The initialization of the first taskgroup is handled only first time by initial useEffect().
=> Refactor taskGroup handling

server/setupProxy.js
Proxy response handler expected Accept header to check if it is "application/json", Maayan reported failure in this code when the Accept header was ommited (and the request was fulfilled by backend hub API). Adding safe navigation operator to Accept headers lookup.
Signed-off-by: Marek Aufart <maufart@redhat.com>
=> Not require Accept header in API Proxy

client/src/app/pages/applications/application-assessment/components/stakeholders-form/stakeholders-form.tsx, client/src/app/pages/applications/application-review/components/review-form/review-form.tsx, client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx, client/src/app/pages/controls/business-services/components/business-service-form/business-service-form.tsx, client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx, client/src/app/pages/controls/tags/components/tag-type-form/tag-type-form.tsx, client/src/app/shared/components/confirm-dialog/confirm-dialog.tsx, client/src/app/shared/components/confirm-dialog/tests/__snapshots__/confirm-dialog.test.tsx.snap
This adds a unique ID for the selector dropdowns to help avoid selector conflicts with pf autogenerated IDs.
=> QE: Add missing toggle IDs for dropdowns  

README.md, development.md
These docs are intended to improve the developer onboarding experience and should serve as a reference point for all development questions including start up guide, forms, testing,  directory structure, styling, and more.
=> docs: Development markdown docs 

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- Currently, an object is assigned to the filename string. This should be the binary name.
=> bug: Add missing filename when uploading a local binary

client/.husky/pre-commit, client/package.json, package-lock.json
- Adds a fallback for prettier formatting when not using the format-on-save feature provided by the vscode prettier plugin
- Fixes our previous husky hook configuration to accommodate our change to npm workspaces
=> :bug: Husky prepare fix and prettier hook

.github/workflows/pr-checks.yml, VERSIONING.md
This adds the workflow for enforcing our PR title convention laid out in the konveyor/release-tools versioning guidelines. Additionally, we add a link to the konveyor/release-tools versioning guidelines as the baseline for this project's versioning rules/guidelines.
Signed-off-by: David Zager <david.j.zager@gmail.com>
=> :seedling: Versioning and PR title enforcement

client/src/app/keycloak.ts
Uses `new Keycloak()` 
```
@deprecated — Construct a Keycloak instance using the new keyword instead.
The signature '(config?: string | KeycloakConfig | undefined): Keycloak' of 'Keycloak' is deprecated.ts(6387)
keycloak.d.ts(348, 4): The declaration was marked as deprecated here.
```
=> :bug: : Replace keycloak deprecated stanza

client/package.json
To be able to run test, more likely since we move to workspace, we can invoke jest directly.
=> :seedling:  Use jest directly

README.md
- This change updates the readme.md in preparation for on-boarding new developers to the project. The current readme was a little hard to follow and jumped around a bit. The intention here is to give all of the commands required to get our preferred (minikube) environment up and running in a sequential order. Additional info is added via links within the markdown & a troubleshooting section is added at the end of the doc to add any supplemental information.
=> :seedling: Update readme for onboarding

Dockerfile
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
I know we weren't in a hurry to do this, however multi arch builds are experiencing odd failures on arm64 using UBI8.
https://github.com/konveyor/tackle2-ui/actions/runs/4168992831/jobs/7216425953#step:2:1067
https://github.com/konveyor/tackle2-ui/actions/runs/4174604421/jobs/7228394767#step:2:1077
I can reproduce much of this locally, and was able to workaround it using UBI9 node16 and node18 images without a problem both locally and within github actions:
https://github.com/jmontleon/tackle2-ui/actions/runs/4175222062/jobs/7229841318
https://quay.io/repository/jmontleon/tackle2-ui?tab=tags
I've opened an issue with qemu-user-static to see if there are any known issues we might be hitting, or other debugging  steps we can try to resolve …
=> :bug: Update to UBI9 to fix arm64 builds

client/src/app/pages/migration-targets/custom-target-form.tsx, client/src/app/queries/assessments.ts
- Assessments query needs a default return value when no assessments exist for an app.
=> :bug: Fix empty assessments query error in console

client/src/app/components/target-card.tsx, client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx
- Aggregates all sources and targets from selected rule bundles and sets the source/target field values accordingly. 
- This required the cardSelected check to change from the target values to the ruleBundle values to allow multiple targets to be assigned from a single rulebundle (in the case of a custom target). 
- Fixes a bug when the formTargets were not being updated when a selected card's target dropdown value changes. Before the targets were only updated on card click.
=> :bug: Aggregate target sources

client/src/app/pages/identities/components/update-identity-modal/update-identity-modal.tsx, client/src/app/shared/components/hook-form-pf-fields/hook-form-pf-group-controller.tsx
- Adds onBlur method to  hook-form-pf-group-controller component to fix missing validation
- Adds missing xmlValidation prop for edit identity form
=> :bug: Fix regression with form validation messages not being shown 

client/src/app/queries/bulkcopy.ts
v4 react-query had a breaking change where the idle state has been removed making it so that `isLoading` can be set to true when there is nothing to load.
https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4#disabled-queries
We can use `isInitialLoading` to know whether or not we should display the loading spinner.
Fixes #667
=> :bug: change isLoading->isInitialLoading

client/src/app/shared/components/app-table/app-table.tsx
The straightforward fix for this would have been to add `event.stopPropagation()` on the click handlers for each of these buttons in the row that are causing the problem, but then if we add more buttons in the future we would need to remember to do this for those as well or the bug would come back. I tried to implement a future-proof fix for this instead: Any click that is either on an `input`, `button` or `a` element or that is on a child/descendant of one of those elements will not trigger the `onRowClick` that opens the drawer.
=> :bug: AppTable `onRowClick`: Fix click propagation issue where buttons in the row trigger the drawer

client/src/app/rbac.ts
The Administration routes are authorized based upon the user's role in RouteWrapper
Therefore there is no need to create scope for customTargets.
Removing previously defined scopes which don't have a match in the hub since where there were never created.
Resolves https://github.com/konveyor/tackle2-ui/issues/608
=> :sparkles: Custom targets: Remove unused RBAC scopes

README.md
Just a little thing I noticed on the onboarding meeting.
=> :book: Fix syntax of tackle operator link in README

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, server/setupProxy.js
Currently, the report download feature does not work in firefox. This fixes the issue by ensuring the accept headers are cleared when requesting a file download. The 'download' html attribute handles this in chrome, but fails to work in firefox.
=> :bug: Fix firefox html/csv report download

client/public/locales/en/translation.json, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/applications/components/application-tags/application-tags.tsx, client/src/app/shared/components/FilterToolbar/FilterToolbar.tsx, client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/shared/hooks/useFilterState.ts
* Displays tag categories grouped by source in the drawer
* Adjusts fetch / indexing logic of tags and tag categories to support grouping by source
* Adds filter dropdowns for source and tag category
* Enhances FilterToolbar so we can render multiple filter dropdowns side by side
* Enhances useFilterState so we can have filter values applied with OR logic rather than AND in certain circumstances (multi-selecting tag categories and sources only makes sense with OR because they are mutually exclusive, so otherwise there would only ever be 1 or 0 matches for a filter)
=> :sparkles: App detail drawer: group tags by source and category, add filters

client/src/app/api/models.ts, client/src/app/common/CustomRules/rules-utils.tsx, client/src/app/components/target-card.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/pages/migration-targets/custom-target-form.tsx
- Currently, advanced options does not reflect the targets selected in the set targets step within the wizard. This fixes that and allows the selection of rule bundle associated targets and non-associated targets alike from the same select dropdown. This is necessary because there are some targets available that are not tied to rulebundles. This functionality was inherited from the windup web console. 
- Fixes a bug when a user selects a target from a "category: "kind" rulebundle in the set-target dropdown, navigates through the wizard, and then navigates back to the set-targets page to find their selection did not persist. This PR adds a check for previously selected targets. 
- Adds typescript support for the RuleBundle form data.
=> :bug: Mirror rule bundle target metadata selection in advanced options

client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/migration-targets/custom-target-form.tsx
Resolves https://issues.redhat.com/browse/MTA-55
In the custom rules and custom targets forms where we have file upload fields that expect files ending in `.windup.xml`, the `accept` prop of `react-dropzone` was not reliably enforcing that filename suffix on mac. There doesn't seem to be a real fix available to us with the dependency versions we have, so this works around the issue by only restricting the fields to `.xml` files.
Note: We are stuck with `react-dropzone@9.0.0` until PatternFly upgrades to the newer versions of that dependency in their `MultipleFileUpload` component eventually. That is something they won't do until their upcoming breaking change release. When we can eventually make that upgrade we may be able to resolve this issue and restore the requirement for …
=> :bug: Don't enforce .windup.xml filename suffixes because it doesn't work reliably

client/src/app/components/target-card.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Fixes an issue that assumes there is a parent form context in the migrationTargets view. This was breaking the UI. 
Since Target-Card is reused in the wizard & migration targets page, sometimes there is a missing form context parent.
=> :bug: Fix missing formContext bug

client/src/app/api/models.ts, client/src/app/pages/applications/analysis-wizard/schema.ts
This fixes a bug causing validation to fail if a custom target is selected with no description in the wizard.
=> :bug: Description is not a required field for rule bundles

client/src/app/pages/migration-targets/custom-target-form.tsx
Remove redundant onChange handler causing error to flash temporarily when the image is uploading
=> :bug: Fix error validation for image id

client/src/app/pages/applications/analysis-wizard/schema.ts
Add custom validation for:
IF no targets are selected, THEN require a customRuleFile / Repo for a rule file(s)
As agreed upon by Ramon & Jeff in ForumTackle. This allows a user to run analysis with:
- only uploaded rules (which contain no targets)
- only a git repo of rules files.
=> :sparkles: Add conditional validation for no-targets case

Dockerfile
Bump from UBI8 to UBI9 was lost because https://github.com/konveyor/tackle2-ui/pull/685 needed a rebase after https://github.com/konveyor/tackle2-ui/pull/685 was merged.
Resolves https://github.com/konveyor/tackle2-ui/issues/638
=> :sparkles: Rebump UBI9

client/public/locales/en/translation.json, client/public/locales/es/translation.json, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/queries/assessments.ts, client/src/app/queries/reviews.ts
* No discard option unless there is an assessment or review
* Fix assessment/review deletion
* Refetch applications
* Refresh data
* force application fetch
* force fetch after assessment discard too
* Handling success or error callbacks
* With application name for success
* use interface instead of any
* Reducing arguments
* remove async
* cleanup
(cherry picked from commit 8b3574d5d1ff89ae699db664d89566aa91dc169c)
=> :bug: [backport-6.1] Fix deletion for Applications assessment/review  (#715)

client/src/app/layout/SidebarApp/SidebarApp.tsx
Currently the 2nd tab is shown as active when the admin sidenav persona is changed to "administration". This PR changes the default to the new 1st tab which is now "General".
=> :bug: Change default tab to first tab when navigating to admin view

client/public/locales/en/translation.json, client/public/locales/es/translation.json, client/src/app/pages/applications/components/application-tags/application-tags.tsx
Resolves https://issues.redhat.com/browse/MTA-366
=> :sparkles: Empty component when no tags

client/public/locales/en/translation.json, client/public/locales/es/translation.json, client/src/app/pages/applications/components/application-tags/application-tags.tsx
* Empty component when no tags
* Add button
* change test style
(cherry picked from commit d7d0270a59032134c60ff1bcadef710cd609e6cc)
=> :sparkles: [backport 6.1] Empty component when no tags #764

client/package.json, client/src/app/pages/applications/components/application-tags/application-tags.tsx, package-lock.json
PF Label support the following 8 colors "gold" | "red" | "blue" | "cyan" | "green" | "orange" | "purple" | "grey" .
Tag colors depends upon their TagCategory colors which are defined as either keyword names (blue, etc) or hexadecimal values (for the recent ones V3).
Therefore depending on the color of the tag the Label can be displayed with a supported color or will fall back to "grey" (Label default) when not supported.
LabelCustomColor from migtools/lib-ui wraps Label to make tag color supported through CSS properties.
Resolves https://issues.redhat.com/browse/MTA-332
=> :bug: Display tags color upon their category

client/src/app/common/KeycloakProvider.tsx
When the "Use Refresh Token" (OpenID Connect Compatibility Modes) is off the refresh_token is not generated.
Resolves https://issues.redhat.com/browse/MTA-41
=> :bug: Do not refresh token when feature disabled

client/src/app/pages/waves/components/create-edit-wave-modal/create-edit-wave-modal.tsx, client/src/app/pages/waves/components/create-edit-wave-modal/index.ts, client/src/app/pages/waves/components/create-edit-wave-modal/wave-form.tsx, client/src/app/pages/waves/waves.tsx
Part of #574
Boilerplate for the modal and form state is in place. Next steps:
* TypeScript type for MigrationWave, and API queries/mutations for fetching and creating them (need the fetch to validate unique names of new waves)
* Remaining form fields (including #575)
* Populating waves in the table (minimal, row contents can come later), wiring up the kebab Edit action to the state added in this PR
* Form logic for editing (Default values to the ones from `waveBeingEdited` if present)
* Mutation logic for editing (patch request)
* Move on to the waves table itself
=> :sparkles: Add skeleton for new Create Migration Wave modal with an edit mode

client/package.json, client/public/locales/en/translation.json, client/src/app/Constants.ts, client/src/app/pages/applications/application-review/components/application-assessment-donut-chart/tests/__snapshots__/application-assessment-donut-chart.test.tsx.snap, client/src/app/pages/applications/components/application-tags/application-tag-label.tsx, client/src/app/pages/applications/components/application-tags/application-tags.tsx, client/src/app/pages/controls/tags/components/tag-category-form/tag-category-form.tsx, client/src/app/pages/controls/tags/tags.tsx, client/src/app/shared/components/color/color.tsx, package-lock.json
Finishes [MTA-332](https://issues.redhat.com/browse/MTA-332)
=> :sparkles: Expand tag category color palette to 16 colors, add deterministic fallback colors for tag categories

client/src/app/FeatureFlags.ts, client/src/app/Routes.tsx, client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/pages/jira-trackers/jira-trackers.tsx, client/src/app/pages/waves/components/create-edit-wave-modal/create-edit-wave-modal.tsx, client/src/app/pages/waves/components/create-edit-wave-modal/wave-form.tsx, client/src/app/pages/waves/wave-applications-table/wave-applications-table.tsx, client/src/app/pages/waves/wave-stakeholders-table/wave-stakeholders-table.tsx, client/src/app/pages/waves/waves.tsx, client/src/app/shared/components/composable-app-table/index.ts, client/src/app/shared/components/composable-table-with-controls/composable-table-with-controls.tsx, client/src/app/shared/components/composable-table-with-controls/index.ts
Mostly this PR makes it possible for us to merge `feature-migration-waves` to main in a non-disruptive way by disabling the waves route and nav item with a boolean feature flag. I also renamed some things and replaced my TODO comments about introducing a `MigrationWave` type with the existing `Wave` type I had forgotten we already had.
=> :sparkles: Move Migration Waves behind a disabled feature flag + some renaming

client/public/locales/en/translation.json
This clarifies that rules can be uploaded or imported from a repository.
https://issues.redhat.com/browse/MTA-378
=> :bug: Fix ambiguity in custom rules help message

client/public/locales/en/translation.json
This clarifies that rules can be uploaded or imported from a repository.
https://issues.redhat.com/browse/MTA-378
=> :bug: [backport 6.1] Fix ambiguity in custom rules help message (#794)

client/src/app/common/CustomRules/useRuleFiles.tsx, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- Fixes https://issues.redhat.com/browse/MTA-443
- Clears error alert when no files with error state exist after removal
=> :bug: Disable add button when file with error is present

client/src/app/common/CustomRules/useRuleFiles.tsx, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- Fixes https://issues.redhat.com/browse/MTA-443
- Clears error alert when no files with error state exist after removal
=> :bug: [backport 6.1] Disable add button when file with error is present (#799)

client/src/app/pages/migration-targets/custom-target-form.tsx
User's can't upload images >1MB for custom targets, this change let's them know before they try.
https://issues.redhat.com/browse/MTA-299
=> :bug: Add notice about max image size for new custom target

client/src/app/pages/migration-targets/custom-target-form.tsx
User's can't upload images >1MB for custom targets, this change let's them know before they try.
https://issues.redhat.com/browse/MTA-299
=> :bug: [backport 6.1] Add notice about max image size for new custom target (#803)

client/src/app/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx, client/src/app/pages/controls/stakeholders/stakeholders.tsx, client/src/app/shared/hooks/use-table-controls/useTableControlProps.ts
- useTableControls implementation for Stakeholders expandable form 
@mturley Nice work! We don't have to necessarily merge this as I know it is still under construction a bit. Just wanted to explore the changes. Works flawlessly. Only thing I did notice - we might need a way to make individual rows expandable. If I have a stakeholder with no groups assigned, I wonder if there is a way to make only that row not have an expandable icon displayed without shifting the columns/table rows.
=> :seedling: Convert stakeholder table to new table abstraction

client/src/app/FeatureFlags.ts
Feature flags can be overridden in development by setting the `FEATURES_ENABLED` environment variable in the following format:
```
FEATURES_ENABLED=featureKey:boolean[,featureKey:boolean,...]
```
For example:
```
FEATURES_ENABLED=migrationWaves:true,dynamicReports:true npm run start:dev
FEATURES_ENABLED=migrationWaves:true npm run start:dev
```
The values in the `FEATURES_ENABLED` constant in the code will be used for any feature keys not included in the env var.
=> :seedling: Add environment varable to override feature flags

client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap, client/src/app/shared/page-drawer-context.tsx
Fixes the entire app re-rendering when PageDrawerContent renders for the first time, which was causing all our applications table queries to fetch twice and the initial fetch updating state on an older unmounted instance of the page (resulting in React warnings).
=> :bug: Fix unnecessary page remounts: don't attempt to render less boilerplate on pages without a drawer

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/shared/page-drawer-context.tsx
Followup to #848.
This solves the weird behavior where navigating away from a page of the app that has a drawer will cause the drawer to slide closed after navigating rather than disappear immediately with the rest of the page. This fixes an additional quirk I encountered while introducing a drawer to the Dependencies page: I would open the drawer for a Dependency, switch to the apps page, and right as the drawer started closing it would swap its contents for the app table's drawer contents.
A `key` prop on any React component will cause the component to fully unmount and remount when the key changes. This PR adds a `pageKey` prop to the `PageDrawerContent` component, to be a string literal describing the page where a drawer is used. This key is passed to the `DrawerPanelContent` …
=> :bug: Use a React key prop to remount the drawer contents when changing routes

client/src/app/pages/dependencies/dependencies.tsx, client/src/app/shared/components/app-table/app-table.tsx, client/src/app/shared/hooks/table-controls/active-row/getActiveRowDerivedState.ts, client/src/app/shared/hooks/table-controls/active-row/index.ts, client/src/app/shared/hooks/table-controls/active-row/useActiveRowEffects.ts, client/src/app/shared/hooks/table-controls/active-row/useActiveRowState.ts, client/src/app/shared/hooks/table-controls/index.ts, client/src/app/shared/hooks/table-controls/types.ts, client/src/app/shared/hooks/table-controls/useLocalTableControlState.ts, client/src/app/shared/hooks/table-controls/useTableControlProps.ts, client/src/app/shared/hooks/table-controls/useTableControlUrlParams.ts, client/src/app/shared/hooks/table-controls/utils.ts
Implements clickable rows and a drawer on the Dependencies table (with placeholder content) via new reusable features in the table-control hooks. The drawer on these new tables can now be trivially driven by a URL param (thanks to `idProperty` being a thing) so when you navigate away from a page with a drawer open and click Back, the open drawer is restored :slightly_smiling_face:
* Adds `@app/shared/hooks/table-controls/utils.ts` for general table-related utils that can be used either with or without the table control hooks.
* Currently only contains `handlePropagatedRowClick`, which is factored out from the clickable row / drawer changes in the applications table introduced in https://github.com/konveyor/tackle2-ui/pull/654. This is the handler that makes sure that when the user clicks …
=> :sparkles: Add support for clickable/active rows with URL param + example usage with Drawer on Dependencies table

client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/shared/page-drawer-context.tsx
Cherry-picks changes from https://github.com/konveyor/tackle2-ui/pull/848 and https://github.com/konveyor/tackle2-ui/pull/851 onto release-0.1. See those PRs for details.
This is a minor bug we discovered while working on future features and has no JIRA issue. It does not affect any user-visible behavior, this fix just prevents some unnecessary extra network requests.
=> :bug: [backport-release-0.1] Fix unnecessary page remounts on Applications page 

client/config/webpack.dev.ts, client/public/locales/en/translation.json, client/src/app/Paths.ts, client/src/app/Routes.tsx, client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/pages/issues/affected-applications/affected-applications.tsx, client/src/app/pages/issues/affected-applications/index.ts, client/src/app/pages/issues/issues.tsx, client/src/app/queries/applications.ts, client/src/app/queries/issues.ts, client/src/app/shared/components/FilterToolbar/FilterControl.tsx, client/src/app/shared/components/FilterToolbar/FilterToolbar.tsx, client/src/app/shared/components/FilterToolbar/SearchFilterControl.tsx, client/src/app/shared/hooks/table-controls/filtering/getFilterHubRequestParams.ts
- Adds initial issues table expandable area content
- Adds numsearch filter type for handling filtering by number if the need arises. I have commented out the effort filter until more info surfaces on the needs.
- Adds affected applications view with apps viewed by associated issue ruleid. Uses react-router route params approach. 
- https://stackoverflow.com/a/38576357 - disable dot rule to allow routing to rule urls with dot notation.
TODO: 
- convert search filters to select where needed for applications
- Improve grouped categories implementation to dynamically hide empty groups
- Add validation description to composite issue expanded area
- Use new hub api label changes
=> :sparkles: Add expandable issues table content & affected applications page

package-lock.json, server/index.js, server/package.json
Add graceful shutdown handling for Ctrl-C (SIGINT) and the podman/docker container stop (SIGTERM) signals.  There are a few advantages doing this:
1. Allow connections to terminate, and
2. Allow for any resource cleanup, and
3. Allow Ctrl-C (and `podman container stop` without resorting to SIGKILL) to actually work when running the server as PID 1 in the container.
For some graceful shutdown of node/express as PID 1 in a container references, see:
- https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html
- https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
- https://emmer.dev/blog/you-don-t-need-an-init-system-for-node.js-in-docker/#express-doesn-t-trap-exit-signals
=> :seedling: Gracefully shutdown the server on SIGINT/SIGTERM

.github/workflows/ci-actions.yml, .gitignore, package.json
Add a `npm run test` script to the root package and adjust the Github Action to run from the root directory.  This allows for proper installation of any shared dependencies in the root `package.json`, and for test scripts to be run in each workspace.
**Note**: The cli options given in `ci-actions.yml` for the test script were not actually being passed to the jest command.  An extra `--` is needed to send those options.  Those adjustments have also been made.
**Note 2**: Using `npm clean-install` in the `ci-actions.yml` will cause ci tests to fail if `package-lock.json` has not been updated in a PR. This version of install prevents npm from updating the lock file.
**Note 3**: `.gitignore` updated for non-root test, build and dist paths
Extracted from #895
=> :seedling: Add `npm run test` and update github action `ci-actions.yml` to use it

client/src/app/shared/hooks/table-controls/types.ts, client/src/app/shared/hooks/table-controls/useLocalTableControlState.ts
Currently `useLocalTableControlState` (and by extension `useLocalTableControls`) uses `useSelectionState` internally and only passes the required arguments to it. This PR exposes the optional `initialSelected` and `isItemSelectable` arguments for `useSelectionState` on the table args object.
Note: This is to unblock @gildub for now, but eventually we probably want to refactor these to get rid of the usage of `useSelectionState` in its current form, so that we can drive the state from string keys via `idProperty` instead of references to row data in memory. This will make it possible to lift selection state into the URL bar and to set items as initially selected before the data is loaded.
=> :sparkles: Add support for additional useSelectionState args in useLocalTableControls

Dockerfile
With docker version `Docker version 20.10.22, build 3a2c30b`, the build fails not knowing how to map a username to a uid in the `COPY` command.
Do two things to prevent this error, and potentially others, going forward:
- explicitly use the `:latest` tag on the FROM containers
- explicitly use `USER 1001` and `COPY --chown:1001` to avoid any user name to uid lookup problems
=> :seedling: Fix container build for old versions of docker

client/src/app/pages/migration-waves/components/export-form.tsx, client/src/app/pages/migration-waves/migration-waves.tsx
Note. This is not about refactoring bulk ticket creation with newly available HUB API request which will be done separately.
Resolves https://github.com/konveyor/tackle2-ui/issues/914
=> :sparkles: Export only when selection and applications are available

client/src/app/pages/external/jira/tracker-form.tsx, client/src/app/pages/external/jira/trackers.tsx, client/src/app/pages/migration-waves/components/export-form.tsx, client/src/app/pages/migration-waves/components/status-table.tsx, client/src/app/pages/migration-waves/migration-waves.tsx, client/src/app/queries/trackers.ts
- Use the same name ("trackers") for all of the UI components (forms/tables) & underlying architecture (hooks, queries/ etc) dealing with JIRA trackers. 
- Keeps usage of instance in form fields displayed to user and other "copy".
=> :ghost: Change references of "instance" to "tracker"

package-lock.json, package.json
Downstream builds use an npmjs package caching system called cachito[1].  It currently does not support dependencies that use a package-spec alias[2][3].  Downgrading `rimraf` to version `^4.x` removed any aliases from our `package-lock.json` and should allow downstream builds to work again.
[1] - https://github.com/containerbuildsystem/cachito
[2] - https://docs.npmjs.com/cli/v9/using-npm/package-spec?v=true#aliases
[3] - https://github.com/containerbuildsystem/cachito/issues/859
=> :seedling: [backport release-0.2] downgrade `rimraf` to `@^4.x` for downstream builds

package-lock.json, package.json
Downstream builds use an npmjs package caching system called cachito[1].  It currently does not support dependencies that use a package-spec alias[2][3].  Downgrading `rimraf` to version `^4.x` removed any aliases from our `package-lock.json` and should allow downstream builds to work again.
[1] - https://github.com/containerbuildsystem/cachito
[2] - https://docs.npmjs.com/cli/v9/using-npm/package-spec?v=true#aliases
[3] - https://github.com/containerbuildsystem/cachito/issues/859
=> :seedling: downgrade `rimraf` to `@^4.x` for downstream builds

client/src/app/pages/applications/components/application-form/application-form.tsx
- Fixes git url validation
Resolves https://issues.redhat.com/browse/MTA-659
=> :bug: MTA-659: Do not require .git extention for git urls

client/src/app/pages/controls/stakeholder-groups/components/stakeholder-group-form.tsx
Resolves https://issues.redhat.com/browse/MTA-647
(cherry picked from commit 5e8f6c77525ef8d23c8feaa6386d8c8591d12aa6)
=> :sparkles: [Backport release-0.2] StakeholderGroupForm: Stakeholders not mandatory (#939)

client/src/app/layout/AppAboutModal/AppAboutModal.tsx, client/src/app/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap
=> :bug: Update konveyor doc URL

client/src/app/pages/applications/components/application-form/application-form.tsx
- Reinstate fix for git url validation
=> :bug: Do not require .git extention for git urls

client/src/app/shared/hooks/useCreateEditModalState.ts
- Adds a new hook for handling modal state
=> :sparkles: Add new hook for modal state

client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/pages/migration-waves/components/applications-table.tsx, client/src/app/pages/migration-waves/components/export-form.tsx, client/src/app/pages/migration-waves/components/stakeholders-table.tsx, client/src/app/pages/migration-waves/components/status-table.tsx, client/src/app/pages/migration-waves/migration-waves.tsx, client/src/app/queries/migration-waves.ts, client/src/app/queries/stakeholders.ts, client/src/app/queries/tickets.ts, client/src/app/queries/trackers.ts, client/src/app/utils/waves-selector.ts
- Currently migration status is clickable/hoverable when the value is null / applications assigned to wave are empty. This fixes that. Closes https://github.com/konveyor/tackle2-ui/issues/961
- Fixes No Issues status being "clickable / expandable" when no data is available in the table / migration wave
- Remove impure functions deriving state & introduce a selector pattern. Usage is MigrationWaveWithStatus which includes ticket status & derived migration wave status on the UI wave resource. Also, this moves away from prop drilling and moves all derived state to selectors for migration waves page and child component tables. Closes https://github.com/konveyor/tackle2-ui/issues/963
- Surface error to aggregate migration wave status Closes #964
- Refactor createTicket -> createTickets to …
=> :ghost: [backport] Improve status for migration waves (#950)

client/src/app/shared/page-drawer-context.tsx
Fixes https://github.com/konveyor/tackle2-ui/issues/984
In `PageDrawerContent`, there are a few props the consumer can pass in locally to the component that we sync up to the Context using useEffects. The existing ones `isExpanded` and `pageKey` are primitives (boolean and string) and so they were safe to use as dependencies in `useEffect` since an unchanged value is referentially equal to the previous value (`"foo" === "foo"`, `true === true`). However, in https://github.com/konveyor/tackle2-ui/pull/904 I introduced `drawerPanelContentProps`, which is an object with a default value of `{}` when omitted. Because `{} !== {}`, when this prop was omitted the useEffect to sync it to context was causing an infinite loop (React thinks every render has a new value for it and updates context with …
=> :bug: Prevent infinite render loop when `drawerPanelContentProps` is omitted in PageDrawerContent

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/components/import-applications-form/import-applications-form.tsx, client/src/app/queries/applications.ts
Using `refetchInterval` to guaranty refetch because `invalidateQueries()` or `refetch()` are not refreshing the applications.
Resolves https://issues.redhat.com/browse/MTA-478
=> :sparkles: After import applications need automatic refetch

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/components/import-applications-form/import-applications-form.tsx, client/src/app/queries/applications.ts
Using `refetchInterval` to guaranty refetch because `invalidateQueries()` or `refetch()` are not refreshing the applications.
Resolves https://issues.redhat.com/browse/MTA-478
(cherry picked from commit 9491f70d382e0bdd985719ef2348fb201b0d7e83)
=> :sparkles: [Backport release-0.2] After import applications need automatic refetch (#985)

client/src/app/pages/identities/components/identity-form/identity-form.tsx, client/src/app/pages/identities/identities.tsx
When `onFocus` to a password or token input field, reset the value back to default and have the form revalidate. Use `resetField()` instead of `setValue("password", "")` to achieve this behavior.
The field reset and form invalidation causes the Create button to be disabled and the old password removed when focus enters the password field.
Bug-Url: https://issues.redhat.com/browse/MTA-474
Behavior with this change:
https://github.com/konveyor/tackle2-ui/assets/3985964/7c757a42-b83a-44a7-935f-d76a9ddbabd8
=> :bug: Credential modal, reset value and revalidate form for password onFocus

client/src/app/pages/repositories/Mvn.tsx
Resolves https://issues.redhat.com/browse/MTA-470
=> :sparkles: Maven Repo: Display spinner when fetching cache

client/src/app/pages/identities/components/identity-form/__tests__/identity-form.test.tsx
Followup PR #989 and extend the `identity-form.test.tsx` test "Identity form validation test - source - username/password" to include blur of the password field and refocus to make sure the password is cleared and the submit button is disabled.
=> :seedling: Add password blur test to identity form

client/src/app/pages/identities/components/identity-form/__tests__/identity-form.test.tsx
Followup PR #989 and extend the `identity-form.test.tsx` test "Identity form validation test - source - username/password" to include blur of the password field and refocus to make sure the password is cleared and the submit button is disabled.
Backport of #996
=> :seedling: [Backport release-0.2] Add password blur test to identity form

.github/workflows/ci-actions.yml
- enable CI on release branches
- only do the code coverage check on PRs/pushes to the main branch
=> :seedling: Enable CI on release branches

.github/workflows/ci-actions.yml, client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap, client/src/app/layout/SidebarApp/tests/__snapshots__/SidebarApp.test.tsx.snap
- enable CI on release branches
- only do the code coverage check on PRs/pushes to the main branch
- After updating the CI workflow to run on the "release-*" branches,
found that some test snapshot were out of sync.  Update the snapshots
here to pass the tests.
Backport of #999
=> :seedling: [Backport release-0.2] Enable CI on release branches

client/src/app/api/rest.ts, client/src/app/pages/applications/components/application-tags/application-tags.tsx
In https://github.com/konveyor/tackle2-ui/pull/889, the `getTagById` and `getTagCategoryById` functions were changed to use axios, but the `.then` callback was left out. That means a Promise is being returned instead of a Tag or TagCategory, and TypeScript isn't catching it because axios doesn't know what type it is fetching. This led to tags not being displayed in the app details drawer on the app inventory page.
=> :bug: Fix broken axios get calls for fetching tags and tag categories by id

client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/proxies/proxy-form.tsx, client/src/app/shared/components/hook-form-pf-fields/hook-form-pf-group-controller.tsx, client/src/app/shared/components/hook-form-pf-fields/hook-form-pf-text-area.tsx, client/src/app/shared/components/hook-form-pf-fields/hook-form-pf-text-input.tsx, client/src/app/shared/components/string-list-field/string-list-field.tsx, client/src/app/utils/utils.test.ts, client/src/app/utils/utils.ts
Make `getValidatedFromErrorTouched()` to use `isDirty` instead of `isTouched` 
Resolves https://issues.redhat.com/browse/MTA-658
=> :sparkles: Forms: use isDirty instead of isTouched for immediate feedback to user

client/src/app/api/models.ts, client/src/app/pages/external/jira/tracker-form.tsx, client/src/app/pages/identities/components/identity-form/identity-form.tsx, client/src/app/utils/model-utils.tsx
Identities has two new kinds (see https://github.com/konveyor/tackle2-hub/pull/374) :
- basic-auth : username(email) and password(token) fields are used for Jira Cloud and Jira Server/Datacenter use cases
- bearer: key field (containing bearer token) used only for Server/Datacenter
Resolves https://github.com/konveyor/tackle2-ui/issues/1011
=> :sparkles: Jira authentication for Jira Cloud and Jira Server/Datacenter combo 

client/src/app/pages/migration-waves/components/manage-applications-form.tsx, client/src/app/pages/migration-waves/components/migration-wave-form.tsx
The name of migration is optional, the start and end dates are used if needed to distinguish migration waves.
Also migration wave names are not unique.
Resolves https://github.com/konveyor/tackle2-ui/issues/865
=> :sparkles: Migration Waves:  name is not required, use start and end dates if needed

client/src/app/pages/external/jira/tracker-form.tsx
Jira server/datacenter supports both `basic-auth` and `bearer` credential types.
So when user selects instance type `Jira-cloud` or `jira-onprem` (jira server/datacenter) then available identities to select from are filtered on either :
`basic-auth`
`basic-auth and bearer`.
Resolves https://issues.redhat.com/browse/MTA-772
=> :sparkles: Add Jira bearer identity to issue manager form

client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/pages/controls/job-functions/components/job-function-form/job-function-form.tsx, client/src/app/pages/controls/stakeholders/components/stakeholder-form.tsx
With hub fixed, the JobFunction name is displayed
Resolves https://github.com/konveyor/tackle2-ui/issues/1033 
Although it doesn't break backend API, when creating or updating a stakeholder only `id` and `name` fields are necessary when a Job Function is selected.
=> :bug: Stakeholder JobFunction name and address API request

client/src/app/pages/identities/components/identity-form/identity-form.tsx
The jira `basic-auth` token is stored in password field which returns encrypted from the hub with a bigger size.
The maximum size of the password has to be augmented so validation works when editing the creds.
Resolves https://issues.redhat.com/browse/MTA-717
=> :bug: Identities: Fix editing Jira basic-auth

client/public/locales/en/translation.json, client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/controls/business-services/business-services.tsx, client/src/app/pages/controls/job-functions/job-functions.tsx, client/src/app/pages/controls/stakeholder-groups/components/stakeholder-group-form.tsx, client/src/app/pages/identities/components/identity-form/identity-form.tsx, client/src/app/pages/migration-targets/migration-targets.tsx, client/src/app/pages/migration-waves/components/manage-applications-form.tsx, client/src/app/pages/migration-waves/components/migration-wave-form.tsx
- Fixes empty string issue which is breaking QE tests
[Update notifications include two spaces](https://issues.redhat.com/browse/MTA-753)
=> :bug: Don't show empty {{what}} value in success notifications

client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-facts.tsx, client/src/app/pages/applications/components/application-detail-drawer/fact-detail-modal/fact-code-snip-viewer.tsx, client/src/app/pages/applications/components/application-detail-drawer/fact-detail-modal/fact-detail-modal.tsx, client/src/app/pages/applications/components/application-detail-drawer/fact-detail-modal/index.ts, client/src/app/queries/facts.ts
- Adds initial implementation of the facts modal, analysis detail drawer tab for facts, and code viewer for facts json.
Notes: This does not cover the filter/sort logic for facts based on sources. There is no mock data available from the api for this yet, but we will be required to collate the fact sources ourselves on the UI side based on the fact keys returned from the hub. https://github.com/konveyor/tackle2-hub/pull/396 for more info on how the api will look. 
TODO: https://github.com/konveyor/tackle2-ui/issues/1061 
TODO: [How should we type facts with an unknown data type? ](https://github.com/konveyor/tackle2-ui/issues/1062)
=> :sparkles: Add facts modal/code viewer & detail drawer tab 

client/src/app/common/CustomRules/rules-utils.tsx, client/src/app/pages/migration-targets/custom-target-form.tsx, client/src/app/queries/rulesets.ts
- Fixes a bug with the rules selector that was writing ruleset data to each rule in the map. This caused all uploaded rules to show the ruleset name rather than the rule name. 
- Fixes an issue with yaml parsing. yaml.load returns an object when only one value is found rather than an array when multiple values are found from an uploaded rule file. This caused the app to blow up & freeze when trying to iterate through the single object. 
- TODO: Fix the enabled save button on edit with no dirty fields for the custom-target-form #1073
=> :bug: Handle uploaded yaml with a single parsed value

client/src/app/pages/migration-targets/custom-target-form.tsx
- Fixes an issue where the save button is always enabled for custom-target-update form. This is because the default handler calls setValue due to the file upload component form state being manually managed by the useRuleFiles component. This fix bypasses the setValue call for initially loaded placeholder files. 
Closes https://github.com/konveyor/tackle2-ui/issues/1073
=> :bug: Save button always enabled for custom-target edit

client/public/locales/en/translation.json, client/src/app/pages/external/jira/components/tracker-status.css, client/src/app/pages/external/jira/components/tracker-status.tsx
Since a Jira tracker "Not connected" error message can be an unlimited length, update the popover such that:
- The width will be between 30em and 50em
- The message height itself will be a maximum of 450px tall
- Message content will overflow with scroll bars as needed
- If the message is longer than 300 characters, an expandable toggle is added to the code block header to allow showing the message in full
These changes should allow long messages to be displayed in a reasonable way.
Resolves: #1067
=> :bug: Update the `TrackerStatus` popover to handle long error messages

client/src/app/shared/components/simple-task-viewer/simple-document-viewer.tsx
Adds a refresh button for the custom code editor. This will allow the refresh of analysis details without refreshing the browser or relying on polling. 
Closes https://github.com/konveyor/tackle2-ui/issues/1086
=> :sparkles: Add refresh button to document viewer

client/src/app/api/models.ts, client/src/app/common/CustomRules/rules-utils.tsx, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/pages/migration-targets/custom-target-form.tsx, client/src/app/queries/rulesets.ts
- Passes a list of all labels that are associated with rule files along to the analyzer.
=> :bug: Pass all associated rule labels to analyzer

client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-906
=> :sparkles: Migration wave validation requires min. 3 characters

client/public/locales/en/translation.json, client/src/app/pages/external/jira/trackers.tsx
Resolves https://issues.redhat.com/browse/MTA-908
=> :sparkles: Jira: Add URL filter and sorting

client/src/app/shared/components/FilterToolbar/FilterControl.tsx, client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/shared/components/FilterToolbar/SelectFilterControl.tsx, client/src/app/shared/components/FilterToolbar/select-overrides.css
Add param `isScrollable`, and released css, to allow the patternfly `Select` components at the core of `SelectFilterControl` and `MultiselectFilterControl` to scroll its content as needed.  This is a replication of the patternfly Menu `isScrollable` prop[1].
- Add `isScrollable` (with a default value of `false`) to `SelectFilterControl` and `MultiselectFilterControl`
- Add `select-overrides.css` to implement the scrolling for the components
- Minor tweaks to the filter select controls to mirror code formatting as they are very similar components
Resolves: https://issues.redhat.com/browse/MTA-485
[1]: https://www.patternfly.org/v4/components/menu#scrollable-menus
=> :bug: Allow the select and multiselect filter controls to scroll content

client/config/webpack.common.ts, client/config/webpack.dev.ts, client/config/webpack.prod.ts, client/package.json, client/tsconfig.json, package-lock.json
By updating `tsconfig.json` and making a few changes in webpack configuration, code splitting is now working.
For developers, this means that the previous 100MB+ app bundle that could frequently crash my browser when trying to debug code has been replaced by a small initial bundle with dynamic loading of each React.lazy() component.  Code debugging and source viewing works much better now.
For end users, this means the app can start up faster.  Less network traffic is great, but really only has an effect if the network latency is high (e.g. if the app is located on a different continent from the user).
Resolves: #1074 
- By updating the `tsconfig.json` to use `module: es2020`, this allows
webpack to do actual code splitting based on `React.lazy()`.
- Many of the previous settings that …
=> :seedling: Enable webpack to do code splitting

client/src/app/layout/SidebarApp/SidebarApp.tsx
https://github.com/konveyor/tackle2-ui/pull/1078 follow-up to restore personae select look and feel.
=> :sparkles: Restore legacy select

client/src/app/pages/controls/tags/components/tag-form.tsx, client/src/app/pages/controls/tags/tags.tsx, client/src/app/queries/tags.ts
Resolves https://issues.redhat.com/browse/MTA-802
=> :sparkles: Tags: Mark stall data after create/edit mutation

client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Currently, the date pickers in the create/edit migration wave modal misbehave when the user attempts to enter a date string manually.
* The required MM/DD/YYYY format is not enforced.
* Invalid date formats are coerced to the nearest matching date, which leads to inaccurate validation running before the user is done typing.
* Entering a start date that is out of the allowable range (before the current day) disables the field.
The problem seemed to mostly stem from the fact that these dates were stored in form state as `Date` objects, which made it impossible to reference the user's entered string in validation if it was formatted incorrectly. This PR changes the form state to use strings instead of Dates, updates the validation accordingly, and transforms the strings into the correct …
=> :bug: [release-0.2] Fix state management and validation of date pickers in migration wave modal

client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Ports #1110 forward to main.
I implemented this fix first on the release-0.2 branch in anticipation that it would be different for the PF4 and PF5 DatePicker components, since it is a high priority for the release. However, this is a pretty straightforward cherry-pick (with conflicts resolved) because the fix required turned out to be the same for PF5.
=> :bug: [main] Fix state management and validation of date pickers in migration wave modal

client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/file-incidents-detail-modal.tsx
I missed this when reviewing #1078. cc @gildub
I noticed that when clicking an affected file in the drawer on the Issues pages to open the incident details modal, the last tab ("All incidents" table) was split out into its own tab bar and rendered below the contents of the selected tab. This is because of this change: https://github.com/konveyor/tackle2-ui/pull/1078/files#diff-e40974378de11be89b5b1ca02db26b8fed80482f468154ebb84807af7f0e7273L125-R147 (link takes a while to scroll the diff after loading)
When I reversed the change, I saw the reason for it: the new Tabs component doesn't like to have its children expressed as a combination of an array and extra nodes (like we had been doing when mapping over the first 5 incidents and conditionally including a 6th tab). It gave this error:
It …
=> :bug: Fix double tab pane in issue incidents detail modal from PF upgrade

client/config/webpack.common.ts, client/config/webpack.dev.ts, client/config/webpack.prod.ts, client/package.json, client/tsconfig.json, package-lock.json
By updating `tsconfig.json` and making a few changes in webpack configuration, code splitting is now working.
For developers, this means that the previous 100MB+ app bundle that could frequently crash my browser when trying to debug code has been replaced by a small initial bundle with dynamic loading of each React.lazy() component. Code debugging and source viewing works much better now.
For end users, this means the app can start up faster. Less network traffic is great, but really only has an effect if the network latency is high (e.g. if the app is located on a different continent from the user).
Backport of #1075
- By updating the `tsconfig.json` to use `module: es2020`, this allows webpack to do actual code splitting based on `React.lazy()`.
- Many of the previous settings that were …
=> :seedling: [backport release-0.2] Enable webpack to do code splitting

client/src/app/shared/components/FilterToolbar/FilterControl.tsx, client/src/app/shared/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/shared/components/FilterToolbar/SelectFilterControl.tsx, client/src/app/shared/components/FilterToolbar/select-overrides.css
Add param `isScrollable`, and released css, to allow the patternfly `Select` components at the core of `SelectFilterControl` and `MultiselectFilterControl` to scroll its content as needed. This is a replication of the patternfly Menu `isScrollable` prop[1].
- Add `isScrollable` (with a default value of `false`) to `SelectFilterControl` and `MultiselectFilterControl`
- Add `select-overrides.css` to implement the scrolling for the components
- Minor tweaks to the filter select controls to mirror code formatting as they are very similar components
Backport of #1094
[1]: https://www.patternfly.org/v4/components/menu#scrollable-menus
=> :bug: [backport release-0.2] Allow the select and multiselect filter controls to scroll content

client/public/locales/en/translation.json, client/src/app/Constants.ts, client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/pages/dependencies/dependencies.tsx, client/src/app/pages/dependencies/dependency-apps-detail-drawer.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/pages/issues/affected-applications/affected-applications.tsx, client/src/app/pages/issues/helpers.ts, client/src/app/pages/issues/issues-table.tsx, client/src/app/queries/dependencies.ts
- Adds the dependencies page & dependencies drawer from [these](https://www.sketch.com/s/af50e991-8061-4b69-84c1-c11241e274f2/a/elkkKkq) mockups
- Uses the existing server side filter/sort method for both the dependencies and dependencies applications components
=> :sparkles: Add Dependencies page & drawer 

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
- It was reported (no bz) that the analysis details should always be accessible from the side drawer. This PR removes the spinner for in-progress analysis status & replaces it with a link to the code viewer modal. Resolves #1013 
- Also, this PR hides the facts tab when no facts are present. Resolves #1100
=> :bug: Always show analysis details in drawer

client/src/app/shared/components/kebab-dropdown/kebab-dropdown.tsx
Fixes #1125
We were using the old Dropdown component from `@patternfly/react-core/deprecated` with the new DropdownItem component from `@patternfly/react-core`. This change upgrades our shared `KebabDropdown` to use the new PF5 `Dropdown` structure.
=> :bug: Fix mismatched new/deprecated dropdown components in KebabDropdown

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
- Wrong constant was used for analysis detail drawer status icon. This fixes the missing hex color values.
=> :bug: Fix colors for analysis details status icon

client/src/app/pages/identities/components/identity-form/identity-form.tsx, client/src/app/pages/identities/identities.tsx, client/src/app/pages/migration-waves/components/migration-wave-form.tsx, client/src/app/pages/migration-waves/migration-waves.tsx, client/src/app/queries/migration-waves.ts, client/src/app/utils/waves-selector.ts
Resolves https://issues.redhat.com/browse/MTA-877
Resolves https://github.com/konveyor/tackle2-ui/issues/974 https://github.com/konveyor/tackle2-ui/issues/911
- Adds Completed status
- Adds In Progress status
- Filters out empty status from derived status calculation. This could mean the issue has been deleted from the underlying JIRA instance OR that the Jira ticket is in the process of being created. We have no way of knowing how to interpret empty string, so this filters it out which gives us a more accurate representation of aggregated status.
- Add TODO for info text around auth types for JIRA credential creation
- Remove Created By field in identity page table
- Fixes stale tickets data in migration waves table by mounting the tickets query
=> :bug: Fix aggregated wave status. Reflect all states in Jira instance 

client/config/webpack.common.ts, client/config/webpack.dev.ts, client/config/webpack.prod.ts, client/package.json, client/src/app/pages/reports/application-selection-context.tsx, package-lock.json
By adopting react-refresh in webpack dev configurations, via `ReactRefreshWebpackPlugin` and `ReactRefreshTypeScript`, developers can now live edit react components without loosing state.  This means components are replaced on change without forcing a page reload.
The `webpack-dev.ts` configuration is using `mergeWithRules()` to both merge the common configuration, and to replace the `ts-loader` options.  The dev options enable react-refresh.
Add `ForkTsCheckerWebpackPlugin` to dev configuration to do async typescript type checking.  It isn't needed on the prod config since the build runs full `tsc` before running webpack.  Any type errors will stop the build before progressing to webpack.
In all webpack configs, `module/rules` now come before `plugins` to maintain visual consistency.
=> :seedling: Adopt `react-refesh` in dev mode to allow hot component replacement

client/src/app/components/target-card.tsx, client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/migration-waves/migration-waves.tsx, client/src/app/shared/components/kebab-dropdown/kebab-dropdown.tsx
Fixes a regression caused by #1126 where dropdown items that are disabled with tooltips could not trigger the tooltips. Discovered by @gildub when working on #1149.
It appears the `isAriaDisabled` prop which we need for retaining the mouse hover event on a disabled DropdownItem is not present in the new PF5 DropdownItem. This is due to missing styles in PF core that are still being addressed (see https://github.com/patternfly/patternfly/issues/5528, https://github.com/patternfly/patternfly/pull/5692, and related comment here: https://github.com/patternfly/patternfly-react/pull/8992#issuecomment-1530234144)
Until `isAriaDisabled` is supported in the new PF5 DropdownItem we must restore the usage of the deprecated component for these tooltips to work.
=> :bug: Restore deprecated `Dropdown` in `KebabDropdown`, use matching deprecated `DropdownItems`, use `isAriaDisabled` prop for items with tooltips

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
- Fix CodeEditor modal open/close state when viewing a completed analysis.
=> :bug: Add missing icon & fix open/close state

client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-906
=> :bug: Migration wave name is min 3/max 20 chars only when provided

client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-906
(cherry picked from commit 34e68b7419a9a910be00fee4cce19472d0aa0831)
=> :bug: [backport release-0.2] Migration wave name is min 3/max 20 chars only when provided (1156)

README.md
Since we really need at least 4 cpus to run an analysis, update the `README.md` to include those settings.
=> :book: Update README with minikube cpu settings

client/src/app/pages/identities/identities.tsx
- By default, do not show the createdBy field when Authentication is disabled as this just leads to a table column with auth.noAdmin as the createdBy value for every entry in the table.
https://issues.redhat.com/browse/MTA-1015
=> :ghost: [backport release-0.2] Re-enable createdBy field for auth required deployments (#1172)

client/src/app/common/KeyDisplayToggle.tsx, client/src/app/components/target-card.tsx, client/src/app/layout/DefaultLayout/tests/__snapshots__/DefaultLayout.test.tsx.snap, client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/layout/SidebarApp/tests/__snapshots__/SidebarApp.test.tsx.snap, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/pages/external/jira/tracker-form.tsx, client/src/app/shared/components/app-table-with-controls/app-table-with-controls.tsx, client/src/app/shared/components/horizontal-nav/horizontal-nav.tsx
closes #1166 
Also found several `pf-v5-m-` where the version should not be on the modifiers. This affected many items, such as not adding the blue left border to active menu items on the nav panel
Aside from removing the `-v5` from `pf-m` modifiers, for the table I also removed the `inline-edit` div as it doesn't appear we are doing inline edits and the styling for the inline-edit was basically just being removed manually by the `enable` modifier.
should also closes #1165
=> :bug: (various): styling issues with pf-v5-m vs pf-m

client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/utils/utils.test.ts, client/src/app/utils/utils.ts
Resolves https://issues.redhat.com/browse/MTA-985
=> :bug: Add url validation to rules step

client/public/locales/en/translation.json, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
When an analysis task is running, and the application drawer is open, show both loading text and spinner and the existing tags. Once the analysis is complete, the loading text/spinner will be removed and any new tags will be shown.
Bug-Url: https://issues.redhat.com/browse/MTA-465
The Reports tab is also mentioned on MTA-465.  This was already addressed with #1103.
=> :bug: Adjust Tags tab on Application Details Drawer when a Task is running

client/src/app/layout/SidebarApp/SidebarApp.css, client/src/app/layout/SidebarApp/SidebarApp.tsx
Fixes #1163 
As part of the PF5 upgrade we failed to wrap the children of `<PageSidebar>` in `<PageSidebarBody>` as mentioned [in the release notes](https://staging.patternfly.org/get-started/upgrade/release-notes/):
> PageSidebar API has been updated. The nav property has been renamed to children. Any content passed to the property should be wrapped in PageSidebarBody.
Also, the padding at the top of the page sidebar body element has been moved to the top of the nav element in PF5, so our custom styles for the perspective selector broke. This fixes that CSS to restore the styles established in https://github.com/konveyor/tackle2-ui/pull/251 (based on [design guidelines here](https://www.patternfly.org/v4/components/context-selector/design-guidelines#recommended-placement-0)).
Note that …
=> :bug: Fix PageSidebar structure and spacing of perpective selector above nav

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
cherry-pick: 
0b20ab323687a88a2923873071fcbc95ce8a9a8f 
&& 
0ff95b8b4c014e7fcc8d4699d290928d531c94cf
- It was reported (no bz) that the analysis details should always be accessible from the side drawer. This PR removes the spinner for in-progress analysis status & replaces it with a link to the code viewer modal. Resolves #1013
- Also, this PR hides the facts tab when no facts are present. Resolves
Assists with resolving https://issues.redhat.com/browse/MTA-465
=> :bug: [backport release-0.2] Always show analysis details in drawer (#1103)

client/public/locales/en/translation.json, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx
Backport of #1191
When an analysis task is running, and the application drawer is open, show both loading text and spinner and the existing tags. Once the analysis is complete, the loading text/spinner will be removed and any new tags will be shown.
Bug-Url: https://issues.redhat.com/browse/MTA-465
The Reports tab is also mentioned on MTA-465. This was already addressed with #1103 (backported with #1190)
=> :bug: [backport release-0.2] Adjust Tags tab on Application Details Drawer when a Task is running

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
- For release-0.2, we still want to be able to view the windup report in the browser. This fixes that regression
=> :bug: Restore report button for analysis

client/public/locales/en/translation.json, client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-923
=> :sparkles: MigrationWave form: Properly notify user of duplicate wave

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, package-lock.json
Disable properly the row delete option (dropdown) when an application is involved in migration wave.
Note: doesn't need to be back-ported
=> :bug: Adjust Dropdown for deprecated table support in PF V5

client/public/locales/en/translation.json, client/src/app/pages/migration-waves/components/migration-wave-form.tsx
Resolves https://issues.redhat.com/browse/MTA-923
(cherry picked from commit 5c1839cf6c5899b8f94c51c5db6ed3af507db95f)
=> :sparkles: [backport release-0.2] MigrationWave form: Properly notify user of duplicate wave (#1173)

client/src/app/pages/issues/affected-applications/affected-applications.tsx, client/src/app/pages/issues/helpers.ts, client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/file-incidents-detail-modal.tsx, client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/incident-code-snip-viewer.tsx, client/src/app/pages/issues/issue-detail-drawer/issue-detail-drawer.tsx
Followup to #1116
When we replaced the issue name property (possibly empty in real data) with the truncated issue description in the table, we failed to replace it everywhere else it is used.
This change uses the first line of the issue/report description where necessary, and truncates it with a tooltip in places with limited available width in case it is a long line.
=> :bug: Use truncated first line of issue description everywhere we were using issue name

client/src/app/pages/migration-waves/migration-waves.tsx
Resolves https://issues.redhat.com/browse/MTA-748 
I was finally able to reproduce this by spoofing my TZ within chrome dev tools. Using the dayjs timezone plugin, we can guess the users timezone and display the utc date accordingly within the waves table.
=> :bug: [backport release-0.2] Fix wave display to show current users timezone (#1195)

README.md
Updates the README to use the [`install-tackle.sh` script provided by the operator repo](https://github.com/konveyor/operator/blob/main/hack/install-tackle.sh) instead of us having to separately maintain install instructions that may change.
Also moves the info about configuring `kubectl` for minikube to before the installation step because the script expects `kubectl` on your path.
[The rich diff can be viewed here for easier review](https://github.com/konveyor/tackle2-ui/pull/1204/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
=> :book: Update README to use operator repo install script

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/queries/assessments.ts
Resolves https://issues.redhat.com/browse/MTA-1041
=> :bug: Fix crashing app when deleting

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/applications/components/application-form/__tests__/application-form.test.tsx, client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/queries/applications.ts
While resolving the related notification issues (see associated MTA-1024) this refactors create/update modal.
Includes following changes :
- Push edit/create notifications down to ApplicationForm
- Use onClose to replace onSave and onCancel
- Consolidate New/Edit Modal duplication
Partially address https://issues.redhat.com/browse/MTA-1024
=> :sparkles: Applications: Update Notification and refactors update/create modal

.github/workflows/ci-actions.yml, codecov.yml
- add projects and flags for `client` and `server`, but make the coverage tests non-blocking
- disable the `default` project and just rely on the flagged projects
- remove `unitests` and `e2etests` projects and flags since they don't make sense in the current repo
- github workflow `ci-actions.yml` updated to upload coverage once for each flag
References:
- Non-blocking: https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks
- Flags: https://docs.codecov.com/docs/flags
- `target: auto`: https://docs.codecov.com/docs/commit-status#target
=> :seedling: Update codecov settings, make coverage non-blocking

client/package.json, package-lock.json
#1226 bumped lib-ui to 9.0.2 but that version still uses prerelease PF versions. we need version 9.0.3 which was released with https://github.com/migtools/lib-ui/pull/137
=> :seedling: Bump lib-ui to 9.0.3 to remove remaining prerelease versions from lockfile

client/src/app/queries/tasks.ts
The motivation for this refactoring came while working on #1191 and trying to understand what tasks were given to the analysis table.  The select function used by `useFetchTasks()` to filter by addon and to keep only the newest tasks per application id was confusing to read as written.  This refactor simplifies the steps involved to use a typical stream processing approach.
Output of the refactored function is functionally identical to the original implementation.
=> :sparkles: Refactor useFetchTasks()'s select function

.github/workflows/pr-checks.yml
The `konveyor/release-tools/cmd/verify-pr` action does not require a source checkout to run.  Just skip the step.
=> :seedling: Action PR Checks / Verify PR contents does not require checkout

client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/pages/migration-targets/migration-targets.tsx, client/src/app/queries/rulesets.ts
Resolves https://github.com/konveyor/tackle2-ui/issues/1093
=> :bug: Hide hidden rulesets from seeded hub list

client/src/app/pages/dependencies/dependencies.tsx, client/src/app/pages/issues/affected-applications/affected-applications.tsx, client/src/app/shared/hooks/table-controls/active-row/getActiveRowDerivedState.ts, client/src/app/shared/hooks/table-controls/active-row/useActiveRowState.ts, client/src/app/shared/hooks/table-controls/selection/useSelectionState.ts, client/src/app/shared/hooks/table-controls/types.ts, client/src/app/shared/hooks/table-controls/useTableControlProps.ts, client/src/app/utils/utils.ts
I made these small cleanup changes before starting on refactoring useSelectionState to fit the model of the other table-control hooks, but that grew in scope so I broke this part into its own PR and will continue the rest after PTO.
This PR:
* Removes commented-out `hasClickableRows` lines because I confirmed that they are indeed no longer needed with PF v5
* Changes the behavior of `useActiveRowState` and `getActiveRowDerivedState` so that the id of the active row as returned in the `IActiveRowState` object can be a string or a number. This aligns with other state hooks that deal with item ids, which can be strings or numbers in the data model (as permitted by the type of `idProperty` being `KeyWithValueType<string | number>`.
* Previously, when we added support for numeric ids in …
=> :seedling: Refactor useActiveRowState to allow number or string ids in state for consistency, misc cleanup

client/src/app/components/target-card.tsx
closes #1127 
i have a conversation in pf slack about possibly changing the way styling is applied, but this is a work around until they do that (or if they never do).
=> :bug: 1127 selected card styling issue

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
- Resolves #1256 
- When closing the wizard, the taskgroup state hangs around between analysis runs causing problems. This PR cleans up the react state when closing/submitting the analysis wizard
=> :bug: Reset wizard form after analysis run

client/src/app/pages/issues/affected-applications/affected-applications.tsx, client/src/app/pages/issues/helpers.ts
Fixes an issue @ibolton336 identified where navigating to the affected apps page from the issues page causes a broken URL if the issue's ruleset contains a `/`.
=> :bug: URL-encode ruleset and rule in affected apps page URL so it doesn't break when ruleset contains a slash (/) character

client/src/app/pages/issues/helpers.ts, client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/file-incidents-detail-modal.tsx, client/src/app/pages/issues/issue-detail-drawer/issue-detail-drawer.tsx, client/src/app/pages/issues/issues-table.tsx
- In the event of a blank ruleReport.description, fallback to use the name or a hardcoded string to prevent an app crash
=> :bug: Add a fallback for issue title

.npmrc, package.json
Versions pulled from `registry.access.redhat.com/ubi9/nodejs-18:1-59.1690899127`
- node: 18.14.2
- npm: 9.5.0
If the node or npm versions don't match the versions in `package.json`, any `npm install` will flag a warning.
The `.npmrc` file setting `engine-strict=true` forces the install version mismatch warnings to become errors.
=> :seedling: Require node/npm versions as used in ubi9/nodejs-18

server/src/index.js
The order request handlers are added to the express server matters much more than anticipated.  This rearrangement allows POST requests etc through the proxy to work again.
=> :seedling: Fix proxies for express server / prod build

client/public/questionnaire-data.yaml, client/src/app/Paths.ts, client/src/app/Routes.tsx, client/src/app/api/models.ts, client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx, client/src/app/pages/assessment-management/questionnaire/components/answer-table.tsx, client/src/app/pages/assessment-management/questionnaire/components/questions-table.tsx, client/src/app/pages/assessment-management/questionnaire/questionnaire-page.css, client/src/app/pages/assessment-management/questionnaire/questionnaire-page.tsx, client/src/app/pages/assessment/index.ts
=> :sparkles: Add questionnaire view driven from example yaml

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/components/TaskGroupContext.tsx, client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/applications/analysis-wizard/set-mode.tsx, client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
- Improve handling of taskgroup state by using contextAPI
- Async create the taskgroup before uploading the custom binary in the single app use case. This is currently broken because we require a task group to exist before navigating to the upload file screen. This regression was caused by the move away from useEffect here https://github.com/konveyor/tackle2-ui/pull/1267
Resolves https://issues.redhat.com/browse/MTA-1175
=> :bug: Add taskgroup when uploading binary

client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx
closes https://github.com/konveyor/tackle2-ui/issues/1292
Adding a lock icon to "system" questionnaire.
Before:
After:
=> :sparkles: Add lock icon for "system" questionnaires

client/src/app/hooks/table-controls/types.ts, client/src/app/pages/assessment-management/questionnaire/components/questionnaire-section-tab-title.tsx, client/src/app/pages/assessment-management/questionnaire/components/questions-table.tsx, client/src/app/pages/assessment-management/questionnaire/questionnaire-page.css, client/src/app/pages/assessment-management/questionnaire/questionnaire-page.tsx
Resolves #1293. We determined we don't need the filter dropdown (at least for now), just the search bar.
* Cleans up some layout issues on the page.
* Adds an "All questions" tab above the section tabs. When viewing this tab, the questions table has a "Section" column so you can still tell the sections apart when they are viewed together.
* Adds the total number of questions under each tab title. When the search bar is used, a badge appears next to this to show how many questions match the search.
* Adds an empty state to the table if there are no questions matching your search.
=> :sparkles: Add search toolbar and "all questions" tab to questionnaire view page, clean up layout

client/src/app/pages/assessment-management/questionnaire/components/answer-table.tsx
While working on upgrading eslint (PR #1291), a switch/case `no-fallthrough` error was found in the `getIconByRisk` function in the `AnswerTable` component. This error would cause a risk of "red" to actually render as a risk of "yellow".  Fixing it separately from the eslint upgrade seems like a good thing.
=> :bug: Fix `getIconByRisk` in `answer-table.tsx`

client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
- This PR introduces the ActionsColumn component in the assessment table
=> :sparkles: Introducing ActionsColumn Component in Assessment Table

client/src/app/pages/applications/analysis-wizard/set-mode.tsx, client/src/app/pages/identities/components/identity-form/identity-form.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/1317
=> :bug: Use onChange() instead of setValue()

client/src/app/api/rest.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-detail-drawer/components/download-button.tsx, client/src/app/queries/download.ts, common/src/proxies.ts
- Adds a download button to handle downloading the analysis report with custom headers driven by props passed in
- Uses the Fetch API to allow setting custom headers. Converts the received data to a blob & then creates an object URL from that blob. Then we can use that URL with a temporary anchor `<a>` element to trigger the download with a localized loading state. 
- This approach allows us to bin any custom headers we were adding in the proxy and just use the fetch api to set the custom headers.
=> :sparkles: Add component for downloading the static report

client/src/mocks/stub-new-work/applications.ts
- Comment out application fetch stub. This handler is breaking application fetch on main currently. Need to wire up full MSW mocks for applications before uncommenting this.
=> :bug: Comment out application handler for now

client/public/locales/en/translation.json, client/src/app/Paths.ts, client/src/app/Routes.tsx, client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/pages/archetypes/components/archetype-applications-column.tsx, client/src/app/pages/archetypes/components/archetype-description-column.tsx, client/src/app/pages/archetypes/components/archetype-maintainers-column.tsx, client/src/app/pages/archetypes/components/archetype-tags-column.tsx, client/src/app/queries/archetypes.ts, client/src/mocks/stub-new-work/archetypes.ts, client/src/mocks/stub-new-work/index.ts
Work done:
Resolves #1263
Full function archetypes table will be done under #1264 
Full function archetypes add/edit form will be done under #1265
----
Base display, with mock/stub data from MSW:
=> :sparkles: Archetypes management: Add navigation and placeholder page component

client/public/locales/en/translation.json, client/src/app/pages/archetypes/archetypes-page.tsx
Part of https://github.com/konveyor/tackle2-ui/issues/1264.
Uses the ActionsColumn component pattern introduced in https://github.com/konveyor/tackle2-ui/pull/1314 to add a kebab menu for actions shown in [this mockup](https://www.sketch.com/s/af50e991-8061-4b69-84c1-c11241e274f2/a/eldjjKW). All 3 actions are currently stubs to unblock @sjd78 from integrating his Edit functionality. PR to implement Duplicate and Delete will be next.
Follows the pattern found in this PF example for "danger" menu items (red text below a separator): https://www.patternfly.org/components/menus/menu#danger-menu-item
=> :sparkles: Add actions kebab to archetypes table with stub dropdown items

client/public/locales/en/translation.json, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/queries/archetypes.ts, client/src/mocks/stub-new-work/archetypes.ts
Part of #1264, followup to #1328.
Note that the change to the MSW mock is because that line was a typo that resulted in a 404 when deleting an archetype, the delete questionnaire endpoint is already mocked in its own file.
=> :sparkles: Implement delete archetype kebab action

client/src/app/pages/applications/application-review/components/review-form/review-form.tsx, client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx, client/src/app/pages/controls/business-services/components/business-service-form.tsx, client/src/app/pages/controls/job-functions/components/job-function-form.tsx, client/src/app/pages/controls/stakeholder-groups/components/stakeholder-group-form.tsx, client/src/app/pages/controls/stakeholders/components/stakeholder-form.tsx, client/src/app/pages/controls/tags/components/tag-category-form.tsx, client/src/app/pages/controls/tags/components/tag-form.tsx, client/src/app/pages/external/jira/tracker-form.tsx, client/src/app/pages/identities/components/identity-form/identity-form.tsx, client/src/app/pages/migration-targets/components/custom-target-form.tsx, client/src/app/pages/migration-waves/components/export-form.tsx, client/src/app/pages/migration-waves/components/manage-applications-form.tsx, client/src/app/pages/migration-waves/components/migration-wave-form.tsx, client/src/app/pages/proxies/proxy-form.tsx
https://github.com/konveyor/tackle2-ui/issues/1336
=> :sparkles: Submit button IDs is submit

client/src/app/Paths.ts, client/src/app/pages/applications/application-assessment/components/application-assessment-wizard/application-assessment-wizard.tsx, client/src/app/pages/applications/application-review/application-review.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/applications/assessment-actions/components/assessment-actions-table.tsx, client/src/app/pages/applications/manage-imports/manage-imports.tsx, client/src/app/utils/utils.test.ts, client/src/app/utils/utils.ts
This updates the formatPath function to use a regex pattern that matches :k followed by either a / or the end of the string ($). This way, it won't inadvertently replace parts of other placeholders. 
Resolves #1335
=> :bug: Regex to avoid substring matching on route paths

client/public/locales/en/translation.json, client/src/app/components/Autocomplete.tsx, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx, client/src/app/pages/archetypes/components/archetype-form/index.ts, client/src/app/pages/archetypes/components/items-select.tsx, client/src/app/pages/archetypes/components/tags-select.tsx, client/src/app/queries/archetypes.ts, client/src/mocks/stub-new-work/index.ts
Add the Archetype form along with Create and Edit actions from the archetype table.
MSW stubs for the hub archetype api are enabled by default for now.
Resolves #1265
Create new (empty):
Tag selection field open with typeahead active:
Create fully filled in:
Create in error with an archetype name that already exists:
Edit existing:
=> :sparkles: Archetype form for Create and Edit

client/src/app/components/items-select/items-select.tsx, client/src/app/pages/applications/application-assessment/components/application-assessment-wizard/application-assessment-wizard.tsx, client/src/app/pages/applications/application-assessment/components/assessment-stakeholders-form/assessment-stakeholders-form.tsx, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx
- Uses new Autocomplete field wrapper in the assessment wizard. 
- Moves the ItemsSelect component to the root level of the app for code sharing
=> :sparkles: Add stakeholders and stakeholder group fields to assessment wizard

client/src/app/pages/migration-waves/components/manage-applications-form.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/912
=> :sparkles: Manage applications form: empty data case

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
Resolves [MTA-1264](https://issues.redhat.com/browse/MTA-1264)
=> :bug: Swap reports download tooltip messages

package-lock.json
The cachito downstream dependency downloader uses the `resolved`
and `integrity` fields for dependencies in `package-lock.json` to
checks a dependency's source.  Unfortunately, an npm environment
can get to a state where `npm install` no longer calculates and adds
those fields.  This will let upstream builds work just fine, but
will break downstream builds.
To fix my npm environment and get package-lock.json fixed up:
```
> npm cache clean --force
> npm run clean:all
> rm package-lock.json
> npm install --ignore-scripts
```
A side-effect of rebuilding the lock file is the library version
numbers get bumped according to the semver ranges.  This _should_
be ok.
=> :seedling: restore package-lock.json resolved and integrity fields

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx
https://github.com/konveyor/tackle2-ui/pull/1353 follow-up to fix broken display of analysis status.
`ApplicationAnalysisStatus` must be used to display analysis state.
`IconedStatus` cannot be used here (or at least not yet) because analysis state mapping for tasks is specific.
=> :bug: ApplicationAnalysisStatus is required for status

client/src/app/data/targets.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx
- Remove from "default targets" the targets already stored in the hub.
- Sort all targets by `label` so they appear alphabetically in the select option (especially important because the whole is a concatenation of the default and hub targets, which is why this wasn't obvious when looking at the list from dropdown).
- Use proper `name` for defaults targets. It makes them more consistent with struct of hub stored targets. Although those names (for the default targets only) seems to not be used anywhere in the UI. And easier if down the track we merge both (defaults and hub targets) in the back-end. 
Resolves https://issues.redhat.com/browse/MTA-1258
=> :bug: Remove redundant targets from defaults list and sort targets

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/migration-waves/migration-waves.tsx
@ibragins explained QE needs : 
- A consistent selector across the UI to identify kebab in toolbar, for instance id="toolbar-kebab"
- A consistent selector across the UI to distinct, on a given table row between, between a "pencil" button and the "actions" kebab. There is no need to uniquely identify those selector by row, QE already has selectors for that purpose.
We can see those IDs in action in current PR in applications-table-assessment.tsx.
Meanwhile that cannot be easliy added to the legacy tables (PF4 or PF5 deprecated table) because we don't have access to the wrapper component. Therefore will have to wait for legacy table migration to be finished first.  
This applies to every page having a top kebab (Toolbar) and rows with several actions button/kebab: 
On the MigrationWaves …
=> :sparkles: Selectors to uniquely identify dropdowns

client/src/app/pages/applications/analysis-wizard/custom-rules.tsx
- Addresses missing default value in the credential dropdown for analysis wizard
Without variant 
With variant
=> :bug: Fix missing variant for dropdown

client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx
Part of #1264, see [checklist here](https://github.com/konveyor/tackle2-ui/issues/1264#issuecomment-1702928566).
The Duplicate action is a cross between create and edit: a "create new archetype" form is opened, but its fields are all prefilled as if we are editing an existing archetype. The prefilled name has an appended " (duplicate)" suffix on it.
Just for fun, in case a user duplicates the same archetype multiple times without touching the default name, we check to see if the new default name is taken and use " (duplicate N)" as the suffix, with N incrementing until we get a name that isn't taken. This is probably unnecessary, but I found it annoying that the "name must be unique" error didn't appear until I touched the field, so this makes sure that case never comes up.
Because …
=> :sparkles: Add Duplicate Archetype action

client/src/app/pages/archetypes/archetypes-page.tsx
Part of #1264, see [checklist here](https://github.com/konveyor/tackle2-ui/issues/1264#issuecomment-1702928566).
=> :sparkles: Add client-side pagination to Archetypes table

client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx
Moving from the MSW stub for archetypes to the real hub archetype endpoint, the create/update form payload needs to be adjusted.
=> :sparkles: Update Archetype form to work with hub backend

client/src/app/pages/assessment-management/import-questionnaire-form/import-questionnaire-form.tsx
The import form had incorrect translation keys.  Keys are adjusted to use the secondary grouping "dialog.message" etc.
=> :bug: Fix translation keys for import questionnaire form

client/src/app/Paths.ts, client/src/app/Routes.tsx, client/src/app/api/models.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-assessment.tsx, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/pages/reports/components/adoption-candidate-graph/adoption-candidate-graph.tsx, client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx, client/src/app/pages/review/components/application-details/application-details.tsx, client/src/app/pages/review/components/review-form/review-form.tsx, client/src/app/pages/review/review-page.tsx, client/src/app/queries/reviews.ts
- Review Archetypes 
Closes #1279
=> :sparkles: Review archetypes

client/src/app/pages/assessment-management/import-questionnaire-form/import-questionnaire-form.tsx
The message displayed on successful import of a questionnaire did not exist in the translation file.  The message key now uses an existing message to say:
"Questionnaire _Name Used_ was successfully created."
=> :bug: Import questionnaire form - fix success toast message

client/src/app/api/rest.ts
Fixes a bug @ibolton336 found where filters weren't working on the Single Application tab of the Issues page.
Looks like this param was removed in #1077
=> :bug: Restore missing params object when fetching issuereports

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx
* The `getSortValues` property was missing from these two tables which turned sorting into a noop.
* The `isExpandable` prop was present on the analysis table even though it is no longer expandable.
* There was a missing empty `<Th />` in each of these tables to correspond to the edit-pencil column. (perhaps `hasActionsColumn` is a bad idea since it makes us incorrectly assume the column counts will always be aligned for us?)
=> :bug: Fix sorting on application inventory tables, misc cleanup in these tables

client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/pages/applications/applications-table-assessment/applications-table-assessment.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-risk.tsx
* Fixes the difference in cell spacing between the two tabs of the application inventory page - one was using a `<Tbody>` and one was not.
* Removes `style={{ cursor: "pointer" }}` inline styles from these tables as they seem to have no effect with the `getClickableTrProps` being used
* Restores the use of the `ApplicationDetailDrawerAnalysis` component on the analysis table instead of the `ApplicationDetailDrawerAssessment`
* Removes a `;` character that snuck into the drawer
=> :bug: Fix inconsistent styles between app inventory tables, fix wrong drawer component being used on analysis table, remove stray character

client/src/app/hooks/table-controls/useTableControlProps.ts, client/src/app/pages/migration-waves/migration-waves.tsx
In #1345, we changed the structure of the expandable rows in the Migration Waves table and caused the `isExpanded` prop to be present on all rows (which should only be on the expanded content rows), which caused all rows to be hidden because it was false. This PR restores the intended structure: Each row is wrapped in a `<Tbody>` with the `isExpanded` prop, which contains two `<Tr>`s: one for the row itself and one for the expanded content.
Also removes the `cursor: "pointer"` inline style on the `Tbody` which was causing the whole row to appear clickable even though only the expandable cells are clickable.
=> :bug: Fix broken rendering of migration waves table rows, properly pass isExpandable prop in useTableControlProps

client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/custom-wizard-footer.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/tests/custom-wizard-footer.test.tsx, client/src/app/queries/assessments.ts
Closes https://issues.redhat.com/browse/MTA-1207
- AssessmentWizard component was not re-rendering between assessment fetches
- Adds a function to check if partial questions have been answered to help determine save as draft status
=> :bug: Save as Draft not working

client/src/app/api/rest.ts, client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/queries/applications.ts, client/src/app/utils/model-utils.tsx
The `contributors` field on the `Application` payload needs to be a pure `Ref` object or it will be rejected by the REST API call. Adopt the same set of data transforms used in the archetype-form to handle getting the correct set of data.
Related changes (came up when working on #1331 that ended up revealing #1404):
- REST `createApplication()` function updated to have the proper return type (response data is not unwrapped)
- Query `useCreateApplicationMutation()` updated to properly pass the newly created `Application` to the `onSuccess()` handler
- `onCreateApplicationSuccess()` in the application form updated to use the correct `onSuccess()` response data
Resolves: #1404 
Followup #1403 to update the way tags are updated to an existing application.  Tags that are from an analysis need …
=> :bug: Applications form: Fix contributors and tags field handling

client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/utils/model-utils.tsx, client/types/array-filter-Boolean.ts
With `array-filter-Boolean.ts`, TS will select a better Array.filter() override so this kind of thing will work automatically without an explicit type casting:
```js
const a: Array<string | undefined | null> = ["A", "B", undefined, null, "C", ""];
const b: string[] = a.filter(Boolean);
// b = ["A", "B", "C"]
```
See https://www.karltarvas.com/typescript-array-filter-boolean.html
See https://stackoverflow.com/a/51390763/1470607
=> :seedling: Setup TS to know about `.filter(Boolean)`

client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/pages/controls/business-services/components/business-service-form.tsx, client/src/app/queries/businessservices.ts
The `owner` field on the `BusinessService` payload needs to be a pure `Ref` object or it will be rejected by the REST API call.  Adopt the same set of data transforms used in the application-form to handle getting the correct set of data.
Related changes:
- Business services related REST API functions updated to have the correct response types
- Business services queries updated to pass REST API response and input values to `onSuccess()` and `onError()` handlers
- `BusinessServiceForm` updated to use mutation response data to display the name of the business service in success messages
- Refactored `business-service-form.tsx` to move all data access/mutation code to hook `useApplicationFormData() to logically divide concerns (data access v. UI handling)
Resolves: …
=> :bug: Business services: Fix create/edit when owner is included

client/src/app/utils/utils.ts
- Fixes customer case 03608826 "When setting up an a new application to be analysed by the MTA, we select Subversion as the repository type and enter the URL with the SVN protocol. The UI tells us that this is not a valid URL for a Subversion repository. Changing the URL protocol to HTTP makes the error go away but our department wide Subversion server is set to use only SVN protocol and cannot be changed. This leaves us unable to scan an application a Subversion hosted application with a valid SVN URL."
Adds regex to allow SVN repos to be validated when adding as a source repo to applications
=> :bug: (Backport release-0.2) - allow svn source repos to be validated (#1346)

client/src/app/layout/HeaderApp/SSOMenu.tsx
addresses https://issues.redhat.com/browse/MTA-1247
was:
now:
=> :bug: fix styling for ssoMenu

client/public/locales/en/translation.json, client/src/app/pages/applications/components/application-form/application-form.tsx
Resolves: #1410
Follows up: #1408
- The application form will only show manual tags (i.e. source="")
- All tags are allowable for selection as a manual tag
- Change the label on the field from "Tags" to "Manual Tags" to match the "Manual" grouping of tags in the application drawer
=> :bug: Update the label for the Tag field on the Application Form

client/src/app/api/rest.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-detail-drawer/components/download-button.tsx, client/src/app/pages/assessment-management/assessment-settings/components/export-questionnaire-dropdown-item.tsx, client/src/app/queries/applications.ts, client/src/app/queries/questionnaires.ts
- Revert part of  https://github.com/konveyor/tackle2-ui/commit/1117014e7943f75037d9543a0d4966965207e96d#diff-31cbe8bc7269f3b48ffa72c630c1eaab5355bcca48361242ce31fc18543a8afa which broke the analysis report download functionality 
Resolves https://issues.redhat.com/browse/MTA-1369
Resolves https://issues.redhat.com/browse/MTA-1386
=> :bug: Fix broken analysis report download

client/src/app/components/answer-table/answer-table.tsx
- Adds tooltip to weight answer table column https://issues.redhat.com/browse/MTA-1351?filter=-1
=> :bug: Add tooltip for weight column

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx
Clicking the 'View analysis details' link in the application analysis detail drawer, reports tab should show the most current application's task details.  If no task is available for an application, "Not available" is shown.
The link for a successful task was broken.  It has been updated to use the task id instead of the application id.
=> :bug: Application drawer > reports: show analysis details for successful task

client/src/app/api/models.ts, client/src/app/components/Autocomplete.tsx, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx, client/src/app/pages/archetypes/components/archetype-tags-column.tsx, client/src/mocks/stub-new-work/archetypes.ts
Resolves: #1436
With hub updates to tag handling and api field name changes related to archetypes, adjustments needed to be made to the UI.
- Update `models.ts` to the current state of `TagRef` and `Archetype` in terms of field names and data types.
- MSW stub data updated to use api model changes.
- **Note**: The tags column on the archetype table is currently displaying ALL tags returned with no source differentiation.
- Update `ArchetypeForm` to use `criteria` instead of `criteriaTags`  as per the api model changes.
- With hub changes to combine the archetype and non-archetype tags into a single field, the form processing now ignored non-archetype fields but still sends them on an update.
- Note: This change mirrors the behavior of manual / non-manual tags on applications and the …
=> :bug: Update archetype model, form and detail drawer to current hub spec

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/issues/helpers.ts
- Adds a dependency link to the application detail drawer
=> :ghost: Adds missing dependency link to app drawer

client/public/locales/en/translation.json, client/src/app/api/models.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-detail-drawer/components/download-button.tsx, client/src/app/pages/general/general.tsx
- Remove old setting for assess/review. This setting was determined to be no longer useful once it was identified as a workaround for pathfinder limitations. This bug should be closed as a result.  https://issues.redhat.com/browse/MTA-1295 
- Add new setting for disabling download - Ramon requested that this setting should be added back in. Initial enhancement https://github.com/konveyor/enhancements/issues/91 
- Change TAR -> HTML for download button. Also suggested by Jeff & Ramon.
=> :ghost: Add setting for disabling download

client/src/app/queries/assessments.ts
- Correctly invalidate cache for assessments by archetype after updating an assessment 
Resolves https://issues.redhat.com/browse/MTA-1397
=> :bug: Continue button not showing after draft save

client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx
When a user is assessing an app, they can still navigate to other areas of the app via the sidebar. This handles the orphaned assessment created when unmounting the wizard.
=> :ghost: Handle hard nav from wizard when assessing

client/src/app/pages/assessment/assessment-page.tsx, client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx, client/src/app/pages/assessment/components/questionnaire-form/multi-input-selection/multi-input-selection.tsx, client/src/app/pages/assessment/components/questionnaire-form/questionnaire-form.tsx, client/src/app/pages/assessment/form-utils.test.ts, client/src/app/pages/assessment/form-utils.ts
Resolves https://issues.redhat.com/browse/MTA-1402
=> :bug: Async default values loading for assessment wizard

client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/utils/utils.ts
- Adds a util function for deduping items objects of a generic type) in an array 
- Uses the util function to dedupe tags when selecting from the applications form tags
=> :bug: Dedupe tags when selecting in app form

client/src/app/pages/applications/components/application-form/application-form.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx, client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx
https://issues.redhat.com/browse/MTA-1381
- Shows criteria tags in edit form
- Fixes hard nav cleanup oversight. Only cancel assessment when not actively saving.
=> :bug: Missing assessment tags

client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/custom-wizard-footer.tsx
Resolves https://issues.redhat.com/browse/MTA-1423?filter=12422675
=> :bug: Save and review for archetypes

client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx
-Set form state once the file is read in rather than when the api returns a 200 for the upload post request 
Resolves https://issues.redhat.com/browse/MTA-1420
=> :bug: Handle upload state for binary upload

client/public/locales/en/translation.json, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-assessment.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx
https://issues.redhat.com/browse/MTA-1384?filter=12422675
=> :bug: Add lists of associated apps & archetypes

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx
"Run" instead of "Next", not sure if someone wants to set up the translations for this
=> :bug: rename last submit button in analysis wizard

client/src/app/components/ConfirmDeleteDialog/ConfirmDeleteDialog.css, client/src/app/components/ConfirmDeleteDialog/ConfirmDeleteDialog.tsx
`ConfirmDeleteDialog` requires the user to enter the item's name before the delete button is enabled.  The user entered text was being cleared on Cancel and Close, but not on Confirm.  Action handlers now clear the user entered text on ALL actions.
Resolves: #1478
=> :bug: ConfirmDeleteDialog: always clear name input value on action

.eslintrc.cjs, client/src/app/api/models.ts, client/src/app/pages/controls/job-functions/components/job-function-form.tsx, client/src/app/pages/reports/components/adoption-candidate-graph/adoption-candidate-graph.tsx, client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx, client/src/app/pages/reports/components/adoption-plan/adoption-plan.tsx, client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx, client/src/app/queries/applications.ts, client/src/app/queries/assessments.ts, client/src/app/queries/dependencies.ts, client/src/app/queries/facts.ts, client/src/app/queries/identities.ts, client/src/app/queries/imports.ts, client/src/app/queries/issues.ts, client/src/app/queries/jobfunctions.ts, client/src/app/queries/questionnaires.ts, client/src/app/queries/targets.ts, client/src/app/queries/taskgroups.ts, client/src/app/queries/tasks.ts, package-lock.json, package.json
Looking at [1], add eslint rules for react-query.  The rules are currently set to `error` in order to highlight what "best practices" will be enforced with this change.
Fixed the reported errors for the eslint plugins:
- `"@tanstack/query/prefer-query-object-syntax`: fix the `useQuery()`
to use the query object syntax throughout the code base.
- `@tanstack/query/exhaustive-deps`:
- Fix the `queryKey` params to include all of the variables used
in the `queryFn`.  This is similar behavior to the `useMemo()`
lint rule.
- Where a `params` prop was being transformed to a string in the
`queryKey`, the transform was removed.  The bare `params` object
is allowed to be used as part of the queryKey.
- A number of warnings in the files that were touched were also resolved (some prettier, some no any …
=> :seedling: eslint - add react-query checks

client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/custom-wizard-footer.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/tests/custom-wizard-footer.test.tsx
Would like some thorough testing on this.
#1244
=> :seedling: update to new wizard for assessment-wizard and custom-wizard-footer

client/src/app/pages/assessment/assessment-page.tsx, client/src/app/pages/assessment/components/assessment-actions/components/dynamic-assessment-actions-row.tsx, client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx
- Fixes an issue previously worked around by refreshing the sections when the assessment was being fetched. This can be solved by conditional rendering the entire wizard.
- Removes old isOpen props & state
- Fixes retake by removing a history.push to the previous assessment.id
- Adds an error alert to indicate a failed assessment fetch
=> :bug: Fix stale wizard state when navigating between assessments

client/src/app/pages/applications/components/application-business-service.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx, client/src/app/pages/applications/components/application-identity-form/application-identity-form.tsx, client/src/app/pages/applications/manage-imports-details/manage-imports-details.tsx, client/src/app/queries/businessservices.ts, client/src/app/queries/imports.ts, client/src/app/utils/model-utils.tsx
Appears that konveyor have since settled on "ID->Id". There are still a few places where we need to reflect this decision in the code. E.g. getKindIDByRef, useFetchBusinessServiceByID, etc
closes #1307
=> :sparkles: refelect ID -> Id

client/src/app/api/models.ts, client/src/app/components/questionnaire-summary/questionnaire-summary.tsx, client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx, client/src/app/pages/assessment/components/questionnaire-form/questionnaire-form.tsx, client/src/app/pages/assessment/components/wizard-step-nav-description/tests/wizard-step-nav-description.test.tsx, client/src/app/pages/assessment/form-utils.test.ts, client/src/app/pages/assessment/form-utils.ts
- Add comments to assessment wizard sections
- Allow comments to be viewed in assessment review screen
=> :ghost: Add comments to assessment wizard & review components

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/review.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx
- Only include explicitly selected source labels from a selected target
=> :bug: Don't auto select source labels when setting a target

client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/components/upload-binary.tsx, client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx, client/src/app/queries/applications.ts, client/src/app/queries/tasks.ts
- Address https://issues.redhat.com/browse/MTA-1420 
- Removes bg polling while wizard is open 
- Adds a check for ongoing mutations while the file upload operation is underway.
=> :bug: Accurately represent upload state in binary upload step

client/src/app/components/SimpleSelect.tsx, client/src/app/components/SimpleSelectBasic.tsx, client/src/app/components/SimpleSelectTypeahead.tsx, client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/pages/applications/components/application-form/application-form.tsx
effort towards #1242 
pushing a couple new components without any changes to other stuff yet so ian can use one with something he is working on.
=> :seedling: adding some pf5 select wrappers

client/public/locales/en/translation.json, client/src/app/pages/identities/identities.tsx, client/src/app/pages/migration-targets/components/custom-target-form.tsx
https://issues.redhat.com/browse/MTA-1542
https://issues.redhat.com/browse/MTA-1543
=> :bug: Adjust custom target edit to reflect api changes

client/src/app/pages/assessment/components/assessment-wizard/assessment-wizard.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/custom-wizard-footer.tsx, client/src/app/pages/assessment/components/custom-wizard-footer/tests/custom-wizard-footer.test.tsx
https://issues.redhat.com/browse/MTA-1451
https://issues.redhat.com/browse/MTA-1207
=> :bug: Adjust save as draft logic

client/src/app/components/labels-from-items/labels-from-items.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-assessment.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx
Follow up to: https://github.com/konveyor/tackle2-ui/pull/1470 
- Added a reusable component for drawer labels. 
- Adds random colors to the tags just for differentiation between the tags when viewing in the drawer.
=> :ghost: Adds colors to drawer tags & removes boilerplate

common/src/environment.ts
Fixes https://issues.redhat.com/browse/MTA-1599
=> :ghost: Default to production for NODE_ENV

client/package.json, common/package.json, server/package.json
Being explicit about what the `NODE_ENV` value should be for each npm script where the value could impact the results can help remove any errors in future.  Motivated by working on #1502.
=> :seedling: Explicitly set NODE_ENV for npm scripts

client/src/app/pages/applications/manage-imports/manage-imports.tsx
Solves [MTA-1592](https://issues.redhat.com/browse/MTA-1592)
@ibolton336 Could you please review this PR? Thanks!
=> :bug: Add download attribute to csv import template link

client/src/app/pages/applications/components/application-detail-drawer/application-detail-fields.tsx
Pick the application owner name to display instead of the `Ref`.
=> :bug: Application drawer, fix owner display

client/src/app/components/PageDrawerContext.tsx
- Addresses an issue with the drawer click functionality which occurs when clicking in-between the columns on a table. The entire layout is left in an unrecoverable state.
https://github.com/konveyor/tackle2-ui/assets/11218376/a3425889-f5f9-4beb-99b1-4c768df0bea4
=> :bug: Fix layout bug on row click (intermittent)

client/src/app/pages/applications/applications.tsx
Solves [MTA-1644](https://issues.redhat.com/browse/MTA-1644)
=> :bug: Remove pb0 class from application section header

client/src/app/components/FilterToolbar/FilterToolbar.tsx, client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/components/FilterToolbar/SelectFilterControl.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/pages/issues/helpers.ts, client/src/app/queries/tags.ts
Resolves: https://issues.redhat.com/browse/MTA-1534
On the following tables, the Tag filter has been enhanced to show the Tag with Tag Category:
- Applications
- Issues / All Issues
- Dependencies
- Dependency Details Drawer / Application Table
Tables that use Tag filters now use a set of options in the format "Tag Category Name / Tag Name".  The filter render component `MultiselectFilterControl` has been updated to have special handling of selected values where the selection chips display the Tag Name and the Tag Category Name is displayed as a tooltip.
Existing item filtering and filter values are still operating as a `string` or `string[]`, but use a string that can uniquely identify each tag.  The net effect means that if a tag of the same name exists in more than one category, they …
=> :sparkles: Add Tag Categories to Tag filters

client/public/locales/en/translation.json, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/queries/applications.ts, client/src/app/queries/archetypes.ts
- Resolves https://issues.redhat.com/browse/MTA-1611
- Add tooltip to indicate review completed for ARCHETYPE.
- Break up delete for reviews /assessments into two separate options for applications table actions column.
- Invalidate assessments by AppId when fetching apps to fix stale assessment status post-assessmentDelete from the app table. 
- Add discard assessment & discard review options for archetype page.
=> :bug: UX improvements for app assessment/review discard

server/src/index.js
Fixes https://issues.redhat.com/browse/MTA-1649
=> :seedling: Disable "X-Powered-By: Express" header

client/src/app/pages/dependencies/dependencies.tsx
Resolves https://github.com/konveyor/tackle2-ui/issues/1510
=> :bug: Add unique key for dependency row item

client/src/app/api/models.ts, client/src/app/pages/dependencies/dependencies.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx
Resolves: #1338
Resolves: https://issues.redhat.com/browse/MTA-1585
Depends on hub change https://github.com/konveyor/tackle2-hub/issues/557 / https://github.com/konveyor/tackle2-hub/pull/558.
- The dependency table will show a single row for every named dependency.
- Multiple versions will be aggregated as a single row.
- Details about multiple versions will be available in the details drawer.
- The details view application table will show the application + version, allowing for all versions used to be listed.
Screencap:
https://github.com/konveyor/tackle2-ui/assets/3985964/6d57aa6e-ce8a-4e2f-9a6f-ebedd79e2241
=> :sparkles: Regroup the dependencies table on name only, version/sha shown in details

client/src/app/pages/dependencies/dependencies.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx
- Add management column for application dependencies table
- Add parsed label conversion for dependency labels
https://github.com/konveyor/tackle2-ui/issues/1339
Depends on https://github.com/konveyor/tackle2-addon-analyzer/pull/62
=> :sparkles: Add management column for application dependencies table

client/src/app/api/models.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-fields.tsx, client/src/app/queries/migration-waves.ts
- Adds missing link for https://issues.redhat.com/browse/MTA-1539
=> :sparkles: Add link for jira ticket in drawer view

client/src/app/components/ExternalLink.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/utils/utils.test.ts, client/src/app/utils/utils.ts
Resolves: #1340
On the Dependencies page, detail drawer, applications table: render the version text as a link to the maven central repository.  The link uses the dependency's sha as the key in the maven central search.
Add component `ExternalLink` to standardize rendering links outside of the app opening in a new tab.
Note: The resolution to #1338 will require a change to the application table's query filter and response object.  This will be done in PR #1536.  See https://github.com/konveyor/tackle2-hub/issues/557 for the response object change.
Screenshot:
=> :bug: Render dependency versions as links

client/src/app/pages/assessment/components/custom-wizard-footer/custom-wizard-footer.tsx
Resolves https://issues.redhat.com/browse/MTA-1676 
- QE raised the point that we should be able to save as draft on the first page of the wizard if the user has navigated back after selecting answers.
=> :bug: Allow save as draft on first page if answers exist

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx
Resolves https://issues.redhat.com/browse/MTA-1651
Wrapping the Tabs component inside a div helps manage the overflow issue seen when testing responsiveness of drawer.
=> :bug: Fix header issue causing tabs to be hidden

client/public/locales/en/translation.json
On the archetype table, applications column, update the translation key used to be plural aware via i18next:
- When `count == 1`, use key `archetypeApplicationCount`
- When `count != 1`, use key `archetypeApplicationCount_plural`
Net result is "1 application" and "3 applications" will be rendered. The "(s)" suffix is no longer required.
Note: The app is currently using `i18next` v19.  In current versions, and therefore current docs, the count suffixes are different.
=> :ghost: Refactor archetype table app column text

client/src/app/pages/dependencies/dependency-apps-detail-drawer.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx
Changes:
- Refactor the header and layout of tabs for the dependencies detail drawer following the changes in #1542.
- Show the dependency name and provider in the header since those two fields together are the row unique key (see #1554).
- Update the filter for the dependency applications to include both the name and the provider to match the row unique key (see #1554).
=> :ghost: Refactor Dependencies details drawer layout and unique row handling

client/public/locales/en/translation.json, client/src/app/pages/dependencies/dependencies.tsx, client/src/app/queries/dependencies.ts
Resolves: #1509
The Dependencies table was setup to use the `AnalysisDependency.name` as the selected row key.  Since the `.name` field is not unique across all rows multiple rows would be erroneously selected at the same time.  To solve the problem, a UI only unique id is generated after fetching and used for the table selection itemId.
Change details:
- Dependencies fetch query updated to inject a UI uid and return `WithUiId<AnalysisDependency>[]`.  This transform is done outside the react-query `useQuery()` handling.
- Updated the table to use the `WithUiId<>` key `_ui_unique_id` for selection.
- Since the button rendered in the "Found in" column had no function, the button was removed.
- "Found in" column moved to the last column to match the placement of matching columns on the …
=> :bug: Refactor dependencies, select row by name and provider

client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx, client/src/app/pages/controls/stakeholders/stakeholders.tsx
Resolves: https://issues.redhat.com/browse/MTA-1694
On the Stakeholder and Stakeholder Group tables, the column "Display Name" was renamed to "Name" to match the add/edit form.  Any other columns and filters that needed to be adjusted to accommodate this change were adjusted.
=> :bug: Rename stakeholder and stakeholder group table's entity name column

client/src/app/pages/migration-waves/components/ticket-issue.tsx, client/src/app/pages/migration-waves/components/wave-status-table.tsx
Resolves https://issues.redhat.com/browse/MTA-701
Resolves https://issues.redhat.com/browse/MTA-1539
=> :bug: Add link to associated ticket

client/src/app/pages/reports/reports.tsx, client/src/app/pages/review/review-page.tsx, client/src/app/queries/assessments.ts
Followup changes to #1573:
- Simplify the assessment risk query
- Simplify the header for reports / identified risk card header
- Fixup layout of the review page assessment summary card
=> :bug: Refactoring to follow up PR #1573 comments

client/src/app/api/models.ts, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/review.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx
Resolves:
https://issues.redhat.com/browse/MTA-1806
https://issues.redhat.com/browse/MTA-1645
=> :bug: Remove DIVA support

client/src/app/pages/assessment/components/assessment-actions/components/assessment-actions-table.tsx
- Missed this in the first pass. Need to filter the archived questionnaires passed when rendering the archived table.
https://issues.redhat.com/browse/MTA-1722
=> :bug: Fix issue causing all non-required assessments to show as archived

client/src/app/api/models.ts, client/src/app/pages/assessment-management/assessment-settings/components/export-questionnaire-dropdown-item.tsx, client/src/app/queries/questionnaires.ts
Resolves: https://issues.redhat.com/browse/MTA-1721
=> :bug: Trim unwanted questionnaire fields on export

client/src/app/queries/questionnaires.ts
A questionnaire's sections, questions and answers all have a order key.  The key needs to be present in the defining yaml file, but does not need to be in sorted order.  To ensure that the UI always has questionnaire items in proper order order, sort everything in the fetch hooks.
Note: Hub returns the questionnaire in the same order as the original yaml file.  We need to make sure things are sorted properly.
=> :bug: Sort Questionnaire items on fetch

client/src/app/pages/assessment/components/assessment-actions/components/dynamic-assessment-actions-row.tsx, client/src/app/queries/assessments.ts
Resolves https://issues.redhat.com/browse/MTA-1826
- Uses a useEffect hook to synchronize the state of the action based on the assessment object. This way, whenever assessment changes, we can ensure that the action is recalculated.
=> :bug: Add useEffect for action state sync

client/src/app/components/ExternalLink.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/pages/issues/components/issue-description-and-links.tsx, client/src/app/pages/migration-waves/components/ticket-issue.tsx
Resolves: https://issues.redhat.com/browse/MTA-1846
Update the render of external links to be consistent across the UI:
- Use `ExternalLink` consistently
- The icon used is the small size of `ExternalLinkAltIcon`
- The text and the icon are both part of the link
Use of `ExternalLink` updated to use the inline variant when used directly in table cells so it doesn't introduce extra height to the row. In a `td`, we want text and link content to be the same height.
Use updated in:
- Dependencies detail drawer, application table, version link
- Issues table, expanded row, details links
- Migration waves, status sub-table, issue link
=> :bug: Update external links styling across the UI

client/public/locales/en/translation.json, client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx
Resolves https://issues.redhat.com/browse/MTA-1840
=> :bug: Add filtering for identified risks table

client/src/app/pages/assessment/components/assessment-actions/components/dynamic-assessment-actions-row.css, client/src/app/pages/assessment/components/assessment-actions/components/dynamic-assessment-actions-row.tsx, client/src/app/pages/assessment/components/assessment-actions/components/questionnaires-table.css, client/src/app/pages/assessment/components/assessment-actions/components/questionnaires-table.tsx
- Address issues with css alignment on assessment actions page
Before: 
After:
=> :bug: Fix alignment on actions screen

client/public/locales/en/translation.json, client/src/app/api/models.ts, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/review.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx
- Requested for improving analysis experience when debugging
=> :sparkles: Add debug flag for analysis

client/src/app/pages/reports/components/application-landscape/application-landscape.tsx
Resolves https://issues.redhat.com/browse/MTA-1867
=> :bug: Fix total count for landscape

client/src/app/pages/migration-waves/components/migration-wave-form.tsx
https://issues.redhat.com/browse/MTA-1815
=> :bug: AppendTo conflict resolved for migration wave datepicker

client/src/app/pages/issues/helpers.ts
Resolves https://issues.redhat.com/browse/MTA-1791
=> :bug: only render archetypes with associated apps in filter

client/src/app/axios-config/apiInit.ts, client/src/app/components/KeycloakProvider.tsx, client/src/app/layout/HeaderApp/SSOMenu.tsx
Resolves https://issues.redhat.com/browse/MTA-1255
- Since we no longer have to support windup reports in a new tab, this code can be cleaned up to use keycloaks internal session management
=> :bug: Fix session expiry when refresh tokens are disabled

client/src/app/components/KeycloakProvider.tsx
Only add the actual `AuthEnabledKeycloakProvider` keycloak handler if the `AUTH_REQUIRED` environment variable is set `"true"`.
=> :bug: Only load keycloak when `AUTH_REQUIRED` is "true"

.github/workflows/ci-actions.yml
Time marches on and github action version need to be updated because old versions get deprecated.  This change updates the actions to the current stable versions available.
=> :seedling: Update github action versions

client/src/app/hooks/table-controls/getLocalTableControlDerivedState.ts, client/src/app/hooks/table-controls/types.ts
Made the same fix in the new react-table-batteries code as well. Note to self: Perhaps we should rename the `totalItemCount` to `filteredItemCount` in the new version, since it really should be the count of all items just before pagination (after filtering), not the total number of items in the unfiltered collection.
For client-side tables, the `totalItemCount` is derived internally inside `getLocalTableControlDerivedState`, and it was incorrectly using `items.length`. Changing that to `filteredItems.length` makes the logic in `usePaginationEffects` behave as intended, which means if the user ends up on an invalid pagination page (e.g. they are on page 2 and they apply a filter that has results on one page), it will kick them back to the last valid page.
cc @ibolton336
=> :bug: Fix pagination effects - for client tables, use `filteredItems` instead of `items` length for `totalItemCount`

client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/rbac.ts
https://issues.redhat.com/browse/MTA-1893
=> :bug: Update archetype rbac scopes

client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx
Use "Reviews" instead of "Review" on the Archetype details drawer Reviews tab.  This keeps the terms used on the tab labels all consistent.
Resolves: https://issues.redhat.com/browse/MTA-1888
=> :bug: Fix label on Archetype detail drawer, Reviews tab

client/src/app/pages/migration-waves/components/migration-wave-form.tsx, client/src/index.tsx
https://issues.redhat.com/browse/MTA-1815
=> :bug: Invalidate isSameOrBefore for enddate wave

client/public/locales/en/translation.json
This is to address an issue where a user expected the technology tags on the output report to be filtered, when the filtering is based on the labels on the rule itself. This PR just makes sure the UI and analyzer use the same terminology
tried to keep the change minimal, can change the internal variables/div names as well if we want.
wasn't sure if :bug: or :ghost: was more appropriate
=> :bug: Rename Rules tags to rules labels for better clarity

client/src/app/components/IconedStatus.tsx, client/src/app/components/questions-table/questions-table.tsx
=> :sparkles: Revert inherited status

client/public/locales/en/translation.json, client/src/app/pages/applications/components/application-detail-drawer/application-detail-fields.tsx, client/src/app/pages/migration-waves/components/wave-status-table.tsx
https://issues.redhat.com/browse/MTA-1783
=> :bug: Add tooltip for unlink jira ticket

client/src/app/pages/controls/tags/tags.tsx
https://issues.redhat.com/browse/MTA-1787
=> :bug: Ensure a tag category rank of 0 is  the lowest value when sorting

client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts
- Update custom rules step validation to allow custom targets with no labels when using rules from a repo.
=> :bug: Allow wizard to proceed with an empty custom target

client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx
After some discussions in the Jira ticket, the archetype detail drawer tab should be named "Review" since an archetype will only have a single review.  The application detail drawer tab will remain "Reviews" since applications can inherit multiple reviews from multiple archetype matches.
Follow up to: #1626
Resolves: https://issues.redhat.com/browse/MTA-1888
=> :bug: Archetype detail drawer, tab renamed "Review"

client/public/locales/en/translation.json, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx
Add a custom error message for the min array length check of the criteria tags and archetype tags fields on the create/edit archetype form.  The new error message properly handles a minimum count of 1 or >1.
Resolves: https://issues.redhat.com/browse/MTA-1945
The error message now:
=> :bug: Enhance error message for archetype create/edit tag fields

.github/workflows/pr-closed.yaml
=> :seedling: add cherry-pick workflow for pr-closed event

client/src/app/App.tsx, client/src/app/dayjs.ts, client/src/index.tsx
Refactoring:
- Explicitly add `i18n` initialization on the root `index.tsx`.
- Move `dayjs` initialization to its own file `dayjs.ts` referenced from `index.tsx`.  This follows the `i18n` init style.
- Move PF css includes from `App.tsx` to `index.tsx`
=> :seedling: Refactor patternfly, i18n, and dayjs initialization

client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/dependencies/dependencies.tsx
Resolves [[Dependencies]Application inventory page shows no applications once Accessed from dependencies](https://issues.redhat.com/browse/MTA-2007) 
Resolves https://issues.redhat.com/browse/MTA-2056
- Removes the auto applied search string when direct navigating using the side nav. This was applying filters that were not registered within the application table ( & other tables). I.E when navigating from the dependencies page, the search string was including an "applications.name" filter which is just referenced as "name" within the applications table. Future iterations may allow us to rewrite the search string when navigating between pages or standardizing on a specific key for app names on the back end. 
- Adds the ability to parse the url string for initial search values in the …
=> :bug: Broken search string when navigating from deps page

client/src/app/api/models.ts, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/applications/components/application-detail-drawer/components/assessed-archetypes.tsx, client/src/app/queries/archetypes.ts, client/src/app/queries/assessments.ts
Resolves https://issues.redhat.com/browse/MTA-1967
Addresses an issue where the assessed boolean for archetypes is set to true when all questionnaires are marked as not-required. Uses the new assessment.required boolean surfaced in https://github.com/konveyor/tackle2-hub/commit/25522337608b2dbab5df85ce4a5b5a9fc78a2289 to filter out these false positives.
=> :bug: Exclude non-required questionnaires in assessed calculation

client/public/templates/questionnaire-template.yaml
Resolves https://issues.redhat.com/browse/MTA-1965
=> :bug: Add excludeFor example for questionnaire

client/public/locales/en/translation.json, client/src/app/pages/applications/analysis-wizard/set-mode.tsx
=> :sparkles: Improve documentation for source analysis mode

client/src/app/pages/applications/applications-table/applications-table.tsx
Resolves: https://issues.redhat.com/browse/MTA-1468
=> :bug: Adding tooltip to PencilAltIcon

client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/components/FilterToolbar/SelectFilterControl.tsx
- Resolves:
- https://issues.redhat.com/browse/MTA-1872 
- https://issues.redhat.com/browse/MTA-467
- Upgrade our usage of the PF select component to the pf 5 supported version.
=> :ghost: Convert single/multi filter toolbar controls to use pf5 select 

client/src/app/components/Notifications.tsx, client/src/app/components/NotificationsContext.tsx
https://issues.redhat.com/browse/MTA-2260
- Previously, the notification delay timeout was being overridden by the timeout set on the alert component itself. This fixes this accidental override.
- Lengthens timeout for notification clear globally to 8 seconds.
=> :bug: Extend notification delay & fix broken delay customization

client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/applications/components/application-detail-drawer/review-fields.tsx
https://issues.redhat.com/browse/MTA-1888
It appears that an application can only have a single review. So this changes the Tab title from `Reviews` -> `Review` and drops the redundant header inside.
=> :bug: application can only have one review

client/src/app/hooks/table-controls/filtering/useFilterState.ts, client/src/app/pages/dependencies/dependency-apps-table.tsx
Resolves https://issues.redhat.com/browse/MTA-2008
&& 
https://github.com/konveyor/tackle2-ui/issues/1498
=> :sparkles: Add url filter to drawer results for dependency apps

client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/components/application-assessment-status/application-assessment-status.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/applications/components/application-detail-drawer/components/assessed-archetypes.tsx, client/src/app/queries/applications.ts, client/src/app/queries/archetypes.ts
- Reduce assessment fetch calls resulting from unnecessary hook calls & query invalidations. 
- Passes assessments down from app table into sub components
=> :sparkles: Reduce assessment calls in effort to reduce network overhead

client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/applications/components/application-detail-drawer/review-fields.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx, client/src/app/pages/review/components/review-form/review-form.tsx, client/src/app/queries/applications.ts, client/src/app/queries/archetypes.ts
https://issues.redhat.com/browse/MTA-2359
- Removes query invalidation & additional archetypes / reviews api calls inside each instance of a rendered (but hidden) drawer. This was causing a huge performance hit.
- Adds margin at top of reviews tab <img width="540" alt="Screenshot 2024-03-04 at 2 46 40 PM" src="https://github.com/konveyor/tackle2-ui/assets/11218376/9c6c8a8f-f8c6-45c9-8609-86a30e206a99">
=> :bug: Remove unnecessary query invalidations for reviews (#1735)

.github/workflows/image-build.yaml
Builds keep failing with EMFILE errors, so follow the advice from a similar issue work around: https://github.com/npm/cli/issues/4783#issuecomment-1908016260
=> :seedling: Increase ulimit nofiles on image-build.yaml

INTERNATIONALIZATION.md, README.md, development.md
Changes:
1. fix dead links i.e. to PF4 components or refactored code
2.  in README 
1. OLM addon issue
2. be more general about minikube drivers i.e. rootless or without VMs
3.  prefer port forwarding to proxy when accessing dashboard (seems safer)
3. in INTERNATIONALIZATION - comment that questionnaire is data imported from YAML files
=> :book: Update developer documentation

client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx
=> :seedling: Use placeholder styling for 'No results' option

client/src/app/pages/issues/helpers.ts, client/src/app/utils/utils.ts
=> :seedling: Use multi select filter for application names

client/src/app/pages/archetypes/archetypes-page.tsx
Review states:
1. Completed - a review exists
2. NotStarted
Assessment states:
1. Completed - all required assessments done (based on 'assessed' flag)
2. InProgress - some assessments done
3. NotStarted
Resolves: https://github.com/konveyor/tackle2-ui/issues/1751
=> :sparkles: Add assessment/review status to archetype table

client/src/app/layout/HeaderApp/SSOMenu.tsx
Reverts konveyor/tackle2-ui#1766
This PR breaks logout and needs to be reverted.
=> :ghost: Revert ":bug: sso-actions-toggle: Adding onBlur event"

client/src/app/hooks/useAssessmentStatus.ts, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/components/application-assessment-status/tests/application-assessment-status.test.tsx, client/src/app/queries/assessments.ts, client/src/app/queries/reviews.ts, client/src/app/test-config/test-utils.tsx
Resolves https://issues.redhat.com/browse/MTA-2503
Resolves https://issues.redhat.com/browse/MTA-2505
=> :bug: Add more assessment status unit tests & modify useAssessmentStatus to fix 2 regression bugs

.github/workflows/ci-repo.yml
Lookup the "FROM .* as builder" image from the project's Dockerfile, and use that image to run the CI unit-test job.
This will ensure the unit-test job is using the same container image that the image builds will be using.  A problem with the container should show up quickly in the unit-testing.
=> :seedling: Setup CI workflow to use same container as Dockerfile

client/public/locales/en/translation.json, client/src/app/components/labels/item-tag-label/item-tag-label.tsx, client/src/app/pages/controls/tags/components/tag-table.tsx, client/src/app/pages/controls/tags/tags.tsx
Working towards resolving:
https://github.com/konveyor/tackle2-ui/issues/1283
=> :ghost: Refactor tags table to remove deprecated legacy table dep

client/src/app/components/FilterToolbar/FilterToolbar.tsx, client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/components/FilterToolbar/SelectFilterControl.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/pages/identities/identities.tsx, client/src/app/pages/issues/helpers.ts, client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx, client/src/app/pages/review/components/application-assessment-summary-table/application-assessment-summary-table.tsx
Key points:
1. do not extend PF SelectOptionProps interface - this allows to add
custom props to the interface and provides better control what prop
are forwarded to SelectOption
2. remove key prop as it's a special prop used internally by React
3. use value prop according to PF documentation - effectively replace
previously used key prop
4. add label prop - to be used as human friendly representation of the
value
5. add groupLabel prop
6. add chipLabel prop - for cases where it differs from the label prop
(main use case are tag items)
=> :seedling: Refactor FilterSelectOptionProps

client/src/app/components/FilterToolbar/FilterToolbar.tsx, client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/components/FilterToolbar/SelectFilterControl.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/pages/identities/identities.tsx, client/src/app/pages/issues/helpers.ts, client/src/app/pages/reports/components/identified-risks-table/identified-risks-table.tsx, client/src/app/pages/review/components/application-assessment-summary-table/application-assessment-summary-table.tsx
Key points:
1. do not extend PF SelectOptionProps interface - this allows to add
custom props to the interface and provides better control what prop
are forwarded to SelectOption
2. remove key prop as it's a special prop used internally by React
3. use value prop according to PF documentation - effectively replace
previously used key prop
4. add label prop - to be used as human friendly representation of the
value
5. add groupLabel prop
6. add chipLabel prop - for cases where it differs from the label prop
(main use case are tag items)
=> :seedling: Refactor FilterSelectOptionProps (https://github.com/konveyor/tackle2-ui/pull/1802)

client/src/app/pages/external/jira/tracker-form.tsx
Resolves https://issues.redhat.com/browse/MTA-2426
---------
=> :bug: Fix insecure toggle regression (#1831)

client/src/app/pages/applications/applications-table/applications-table.tsx
Part of #1318
Resolves: https://issues.redhat.com/browse/MTA-2261
Backport-of: #1829
=> :sparkles: Set application delete as danger kebab menu item (#1829)

client/src/app/pages/review/components/review-form/review-form.tsx
On the review form, fix the `onChange` handler for the following `NumberInput` fields:
- criticality
- priority
Note: This fix is a follow up to the fix in #1831.  A grep across the codebase showed 2 more or the same problems.
Resolves: #1844
=> :bug: Review form, fix `onChange` handlers

client/src/app/hooks/useAssessmentStatus.ts, client/src/app/pages/applications/components/application-assessment-status/tests/application-assessment-status.test.tsx
Resolves https://issues.redhat.com/browse/MTA-2505
- Adds additional unit test coverage
=> :bug: Address required status bug

client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/file-all-incidents-table.css, client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/file-all-incidents-table.tsx
Resolves https://issues.redhat.com/browse/MTA-1959
=> :bug: Show first non-empty line in incident message overflow tab

package-lock.json, package.json
Resolves: https://issues.redhat.com/browse/MTA-1952
Resolves: https://issues.redhat.com/browse/MTA-2456
Override `follow-redirects` and upgrade to `follow-redirects@^1.15.6`.
=> :bug: Upgrade version of follow-redirects

package-lock.json, package.json
Resolves: https://issues.redhat.com/browse/MTA-2489
Resolves: https://issues.redhat.com/browse/MTA-2649
Bump to `webpack-dev-middleware@5.3.4` on __release-0.2__ to keep developers safe.
=> :bug: [backport release-0.2] Upgrade version of webpack-dev-middleware

.github/workflows/march-image-build-push.yml, Dockerfile
Backport image build changes made on main and release-0.3 to get release-0.2 building properly.
See: #1781, #1780
Follow-up to #1801, #1871
=> :ghost: [backport release-0.2] Update Dockerfile and image build

client/src/app/pages/applications/applications-table/components/manage-columns-toolbar.tsx
Missing full path to translation text in manage columns modal.
=> :bug: Missing manage columns title translation

codecov.yml
Resolves: #1909
Disable codecov's github annotations feature since it generates an annoying amount of annotations with our current level of testing coverage.
=> :ghost: Disable codecov annotations

.github/dependabot.yml
Configure dependabot to create PRs when the images we use in the `Dockerfile` have a newer version.  This allows us to reference specific container images and be automatically notified of newer versions.
Supports: #1883
CI added in #1907 will run against the PRs dependabot will open for `Dockerfile` changes.  This will allow us to have confidence that the update will be successful.
=> :seedling: Have dependabot track `Dockerfile` referenced images

.github/workflows/ci-image-build.yml, .github/workflows/image-build.yaml
If the workflow is run from a PR, and the PR includes a change to the `Dockerfile` or `package-lock.json`, then run image builds for all of our target platforms.
The images are built but not pushed to any repository.
We want to be reasonably sure that any major build file changes will not cause the image-build-and-push on PR merge workflow to break. Doing the image build here should reveal most problems much earlier. For example, a npm version update in the build container could break github action `nofiles` or network access capabilities for the npm install.
See #1742, #1746, and #1781 for some other examples of when this check could have caught issues before a PR merge.
Supports: #1883
Backport-of: #1907
=> :seedling: [backport release-0.4] Test image build when build related files change (#1907)

.github/workflows/ci-image-build.yml
If the workflow is run from a PR, and the PR includes a change to the `Dockerfile` or `package-lock.json`, then run image builds for all of our target platforms.
The images are built but not pushed to any repository.
We want to be reasonably sure that any major build file changes will not cause the image-build-and-push on PR merge workflow to break. Doing the image build here should reveal most problems much earlier. For example, a npm version update in the build container could break github action `nofiles` or network access capabilities for the npm install.
See #1742, #1746, and #1781 for some other examples of when this check could have caught issues before a PR merge.
Supports: #1883
Backport-of: #1907
Note: build architectures updated to match the settings on the backport target …
=> :seedling: [backport release-0.3] Test image build when build related files change (#1907)

client/src/app/components/FilterToolbar/FilterToolbar.tsx, client/src/app/components/FilterToolbar/MultiselectFilterControl.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx
Use one ToolbarFilter per options group. First filter provides 
the option list. Remaining filters are hidden and used only for
side effects (separate chip groups). The approach follows
similar widgets used by Forklift plugin and OpenShift Console but
uses a flat list of toolbars (nesting trick requires the widget to be
visible all the time).
Related refactorings in MuliselectFilterControl:
1. drop unused feature - using dictionary type for selectedOptions
2. drop state that can be calculated:
a) active item from focusedItemIndex
b) selectedOptions from filters
3. centralize id calculations - use prefix based on category title
4. use label styling for tag category part of option
Resolves: #1774 
Reference-Url: https://github.com/kubev2v/forklift-console-plugin/pull/90
Reference-Url: …
=> :bug: Use separate chip groups for tag categories

client/src/app/hooks/table-controls/sorting/getLocalSortDerivedState.ts, client/src/app/hooks/useLegacySortState.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/components/application-tags/application-tags.tsx, client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx, client/src/app/pages/controls/tags/components/tag-form.tsx, client/src/app/pages/controls/tags/components/tag-table.tsx, client/src/app/pages/controls/tags/tags.tsx, client/src/app/pages/issues/helpers.ts, client/src/app/pages/reports/reports.tsx, client/src/app/queries/tags.ts, client/src/app/queries/tasks.ts, client/src/app/utils/utils.ts
Replace default alphabetical sort order (i.e. a, a11, a2)               
with human friendly "natural" sort (i.e. a, a2, a11).                   
The change applies to all found cases of string sorting.                
For convenience the comparator converts all values to strings (with     
nulish values being converted to empty string).                         
In addition, the natural sort with string conversion (universal          
comparator) was used as a replacement in sorting hooks. There a general 
sorting algorithm was implemented with type-specific comparators.     
Benefits of universal comparator:                                       
1. better handling of mixed types (i.e. string and number). String value
most likely gets converted to NaN. …
=> :bug: Use natural sort order

client/src/app/components/FilterToolbar/FilterToolbar.tsx, client/src/app/hooks/table-controls/filtering/getLocalFilterDerivedState.ts
Before this PR, all values were matched in the same way:
1. value needs to be string or have string representation via
getItemValue
2. positive match is returned if (lowercased) value contains
(lowercased) filter value.
After this PR, a custom algorithm can be provided using "matcher"
property. Direct motivation is DateRange filter which stores filter
values as ISO 8601 time intervals i.e. "2024-04-01/2024-05-01".
Positive match (value is in the range) requires parsing to date objects.
Reference-Url: https://en.wikipedia.org/wiki/ISO_8601#Time_intervals
Reference-Url: https://github.com/konveyor/tackle2-ui/pull/1913
=> :sparkles: Add custom matchers to client side filters

.github/workflows/ci-image-build.yml, package.json
Changes:
- If any of the `package.json` files change, test the image builds. We want to make sure that changes to the `engine` or `script` blocks receive a full image build testing.
- Update the npm version check to `>=9.5.0`. This will allow the test image build CI to check new builder images that also have npm major version updates.
=> :seedling: Add and allow test image builds for more changes

.github/workflows/ci-image-build.yml, package.json
Changes:
- If any of the `package.json` files change, test the image builds. We want to make sure that changes to the `engine` or `script` blocks receive a full image build testing.
- Update the npm version check to `>=9.5.0`. This will allow the test image build CI to check new builder images that also have npm major version updates.
Backport-of: #1926
=> :seedling: [backport release-0.3] Add and allow test image builds for more changes (#1926)

client/src/app/pages/issues/affected-applications/affected-applications.tsx
Resolves: #1936 
UI Tests PR: 1124
Addresses mismatch between data column and displayed text for "Effort" Column in affected applications table
PR konveyor/tackle2-ui#1846 intended to revert back to using effort favoring tooltips to differentiate what is being displayed in fields labeled effort.  The Issues>Affected Application table effort column heading text was updated, but the data-label used was still "Total Effort".
=> :bug: On Issues>Affected Application table, update column data-label to match displayed text

client/src/app/pages/applications/analysis-wizard/set-options.tsx
Resolves https://issues.redhat.com/browse/MTA-2795
- Resolves any potential duplicates between hardcoded default targets / sources labels & parsed labels from targets.
=> :bug: Remove duplicate targets in advanced options screen

CODEOWNERS
Updating the `CODEOWNERS` by:
- removing old groups that no longer exist
- remove the path that doesn't exist
- individually add owners/reviewers
Now it should match `OWNERS.md` and let new PRs auto-request reviews.
=> :ghost: Update `CODEOWNERS` to match `OWNERS.md`

client/src/app/api/rest.ts, client/src/app/queries/tasks.ts
Part-of: https://github.com/konveyor/tackle2-ui/issues/1931
Reference-Url: https://github.com/konveyor/tackle2-hub/pull/640
=> :sparkles: Fetch tasks with server-based filtering

client/src/app/api/models.ts
Update the `Task` interface, and related, to follow the current definitions of Task REST resource[^1] on the hub.
Supports: #1955, #1956, #1957
[^1]: https://github.com/konveyor/tackle2-hub/blob/1366d95b62ac7717826fd9f64c9e268013107008/api/task.go#L725-L748
=> :seedling: Update the `Task` TypeScript interface

client/src/app/hooks/table-controls/sorting/useSortState.ts
Before, initialSort property passed as parameter to useTableControlState() hook was not used as default value. Instead the defaults were calculated based on available sortable columns.
=> :bug:  Use initialSort property

client/src/app/hooks/table-controls/column/useColumnState.ts, client/src/app/hooks/table-controls/types.ts, client/src/app/hooks/table-controls/useTableControlState.ts, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/applications-table/components/manage-columns-modal.tsx, client/src/app/pages/applications/applications-table/components/manage-columns-toolbar.tsx
Related improvements:
1. support restoring columns to initial configuration
2. clean up invalid columns stored in local storage
Part-of: https://github.com/konveyor/tackle2-ui/issues/1931
=> :sparkles: Provide initial state for column management

client/src/app/pages/applications/components/application-form/application-form.tsx
Resolves: https://github.com/konveyor/tackle2-ui/issues/1967
Note: validation is not necessary since the ui already breaks up the input into separate for fields and composes the binary coordinates under the hood.
=> :sparkles: Add mvn:// prefix to application binary value in post request

client/public/locales/en/translation.json, client/src/app/Paths.ts, client/src/app/Routes.tsx, client/src/app/api/rest.ts, client/src/app/components/simple-document-viewer/AttachmentToggle.tsx, client/src/app/components/simple-document-viewer/LanguageToggle.tsx, client/src/app/components/simple-document-viewer/SimpleDocumentViewer.css, client/src/app/components/simple-document-viewer/SimpleDocumentViewer.tsx, client/src/app/components/simple-document-viewer/SimpleDocumentViewerModal.tsx, client/src/app/pages/applications/analysis-details/AnalysisDetails.tsx, client/src/app/queries/tasks.ts
Resolves: https://github.com/konveyor/tackle2-ui/issues/1929
Functional changes:
1. document to be viewed is selected from the list (first action above
the editor) or via URL
2. display language toggle based on languages supported by the document.
For attachments the list consists of plain text and optionally a
second language discovered based on file extension (YAML or JSON).
3. replace "merged" checkbox with an option in the select
Related refactorings:
1. split getTaskById() query into specialized queries:
a) getTaskById() returning Promise<Task> for working with the object
b) getTaskByIdAndFormat() returning Promise<string> for displaying
the task as a formatted text
2. configure AnalysisDetails component to respond to 2 routes: existing
details route and newly added …
=> :sparkles: View files task attachments

client/public/locales/en/translation.json, client/src/app/Constants.ts, client/src/app/Paths.ts, client/src/app/Routes.tsx, client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/components/Icons/index.ts, client/src/app/components/Icons/taskStateToIcon.tsx, client/src/app/layout/SidebarApp/SidebarApp.tsx, client/src/app/pages/tasks/tasks-page.tsx, client/src/app/pages/tasks/useTaskActions.tsx, client/src/app/queries/tasks.ts
Functional changes:
1. create task manager entry in the sidebar navigation list
2. place task page under /tasks route
3. present tasks in a server-filtered table
4. row actions supported: canceling, enable/disable preemption flag
5. use column management to hide optional columns: pod, started,
terminated
Related features:
1. make id property required in Task type
2. switch task update endpoint to use patch method
3. provide icon-to-state mapping that preserves original state names
which are required for server filtering
Resolves: https://github.com/konveyor/tackle2-ui/issues/1931
=> :sparkles: Task table

client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/tasks/tasks-page.tsx, client/src/app/queries/tasks.ts
Resolves: #1970
- When creating a new `Taskgroup`, specify `kind` instead of `addon`
- Process Tasks where `kind` may be missing and `addon` is given instead (i.e. tasks created before this change)
- Make `Task.id` and `Taskgroup.id` required, `New<>` as needed
=> :bug: Prefer `Task` field `kind` over `addon`

client/src/app/pages/applications/applications-table/applications-table.tsx
This PR narrows down the check for analysis tasks that are cancellable. Also the logic is updated and flipped for "disabling" the creation of a new analysis task. Analysis tasks should be creatable when there are no states for tasks outside of "succeeded" or "failed". This will future proof against any other additional task states that may be added in the future. The "scheduled" state was just added for 0.4 & is the motivation behind this PR ( as requested by @jortel )
=> :ghost: Update check for running analysis / cancel analysis 

README.md, hack/README.md, hack/setup-operator.sh
Add a helpful script to setup the operator and create a Tackle instance.  Update README.md files to match.  Added some useful commands to `hack/README.md`.
The script is based on the operator's scripts of similar names, but modified to install the dev version without building anything locally first.
For reference, here is the OLM install script: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/scripts/install.sh
=> :ghost: Add `hack/setup-operator.sh` scripts and more dev doc

client/src/app/pages/applications/applications-table/applications-table.tsx
On the application table, update the analysis button's enable/disable check such that analysis is only allowed to be started when all of the tasks for the selected applications are in a terminal state (they are not in-flight/queued).
Fixes: #1976
=> :bug: Update the enabled check for the Analysis button

client/src/app/components/Icons/TaskStateIcon.tsx, client/src/app/components/Icons/index.ts, client/src/app/components/Icons/taskStateToIcon.tsx, client/src/app/components/task-manager/TaskManagerDrawer.tsx, client/src/app/pages/tasks/tasks-page.tsx
Follow the mapping used by the drawer with following changes:
1. use PauseCircleIcon also for QuotaBlocked state
2. use TaskIcon for Ready state (instead of CheckCircleIcon)
3. use CheckCircleIcon for state Succeeded
Part-of: #1969
=> :bug: Refactor task state to icon mapping

client/src/app/components/Icons/TaskStateIcon.tsx
Align `TaskStateIcon` Icon status fields with `IconedStatus`.
This amounts to setting some icons blue instead of black consistently across tables and the drawer.
Related to #1985
=> :ghost: Align TaskStateIcon Icon status fields with IconedStatus

client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/applications-table/components/column-application-name.tsx, client/src/app/pages/applications/applications-table/useDecoratedApplications.ts, client/src/app/queries/tasks.ts
On the application table's name column, add a status icon.  The icon summarizes the status of the various kinds of tasks attached to an application (a single application has 0 or more tasks while a task acts on a single application).
The icon will be driven off looking at the most recent task (by `createTime`) per `kind` for an application:
- If there are no tasks, show the application in No Tasks state
- Else if any are "running", show the application in Running
- Else if any are "queued", show the application in Queued state
- Else if any are "failed", show the application as Failed
- Else if any are "canceled", show the application as Canceled
- Else if any are "succeeded", show the application as Success
A popover on hover will render on the application name column to display summary …
=> :sparkles: Add application tasks status icon and popover to application table

client/public/locales/en/translation.json
=> :bug: Change description of application details binary section to Binary(Java)

client/src/app/pages/tasks/tasks-page.tsx
The API provides date/time in UTC. For user convenience we display it in the browser time zone. Before this PR, UTC offset for the local time zone was included.
The format used is a subset of ISO 8601 which allows for predictable sorting in the table.
Format string: "YYYY-MM-DD HH:mm:ss".
Example date: "2024-07-03 13:21:44".
Part-of: #1969
=> :bug: Drop UTC offset for local time used in tasks table

client/src/app/components/task-manager/TaskManagerDrawer.tsx, client/src/app/pages/tasks/TaskActionColumn.tsx, client/src/app/pages/tasks/tasks-page.tsx, client/src/app/pages/tasks/useTaskActions.tsx
=> :bug: Add task actions to task manager drawer

client/public/locales/en/translation.json, client/src/app/pages/tasks/tasks-page.tsx
Resolves: https://issues.redhat.com/browse/MTA-3235
=> :bug: Add tooltips for Priority and Preemption columns

client/src/app/pages/identities/identities.tsx
Drop conditional rendering as it clashes with column type definitions:
the dynamic column is interpreted as optional property which is not
allowed by the current typing in the table hooks.
Resolves: https://issues.redhat.com/browse/MTA-3143
Co-authored-by: Ian Bolton <ibolton@redhat.com>
=> :bug: Filter credentials by createUser property

client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/applications-table/useDecoratedApplications.ts
Resolves: #2007
Resolves: https://issues.redhat.com/browse/MTA-3232
- The application edit form needs to use the base `Application` data and not the `DecoratedApplication` as its basis for generating an update request.  Extra information added by the decoration will be unknown to the hub endpoint and will cause issues.
- All references to `Application` in the application table code have been updated to `DecoratedApplication`
- Any adjustments needed when a `DecoratedApplication` is passed to a child component as an `Application` have been made
- The dereferencing part of decoration has been moved to a `direct` container.  This will allow the reuse of the `Application` property name without replacing it.
=> :bug: Fix application edit data source

client/src/app/pages/applications/components/application-form/application-form.tsx
When creating an application, if the "Binary (Java)" source is not specified, we want to store an empty string as the `binary` value and not `"mvn://::`.  This also applied to editing an existing application.
Resolves: #2014 
Resolves: https://issues.redhat.com/browse/MTA-3238
=> :bug: Don't use "mvn://::" for an empty binary source in applications

client/src/app/hooks/table-controls/types.ts, client/src/app/hooks/table-controls/useTableControlProps.ts, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/manage-imports-details/manage-imports-details.tsx, client/src/app/pages/applications/manage-imports/manage-imports.tsx, client/src/app/pages/archetypes/archetypes-page.tsx, client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx, client/src/app/pages/assessment/components/assessment-actions/components/questionnaires-table.tsx, client/src/app/pages/controls/business-services/business-services.tsx, client/src/app/pages/controls/job-functions/job-functions.tsx, client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx, client/src/app/pages/controls/stakeholders/stakeholders.tsx, client/src/app/pages/controls/tags/tags.tsx, client/src/app/pages/external/jira/trackers.tsx, client/src/app/pages/identities/identities.tsx, client/src/app/pages/migration-waves/components/manage-applications-form.tsx, client/src/app/pages/migration-waves/components/stakeholders-table.tsx, client/src/app/pages/migration-waves/components/wave-applications-table.tsx, client/src/app/pages/migration-waves/components/wave-status-table.tsx
To enable easier and safer selection of table rows by testing code, add some data attributes to the tr:
- `data-item-id` - Holds the `idProperty` value of a table's items.  This is typically the item's id number but may be a frontend generated ID in some cases.
- `data-item-name` - If the table property `dataNameProperty` is provided, hold the name property of a table's item.
For any tables that use `/use.?*TableControls\(/`, add a `dataNameProperty` and if necessary, adjust the `idProperty`.  A few tables for items without a good item id and name property were left with just the `idProperty`.
=> :seedling: Add data attributes to table rows

client/public/locales/en/translation.json, client/src/app/api/models.ts, client/src/app/api/rest.ts, client/src/app/components/Icons/IconedStatus.tsx, client/src/app/components/Icons/TaskStateIcon.tsx, client/src/app/components/tests/__snapshots__/StatusIcon.test.tsx.snap, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/applications-table/components/column-application-name.tsx, client/src/app/pages/applications/applications-table/useDecoratedApplications.ts, client/src/app/pages/applications/components/application-analysis-status.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/tasks/tasks-page.tsx, client/src/app/queries/archetypes.ts, client/src/app/queries/tasks.ts
Resolves: #1997
When a task is succeeded but has attached errors, render task state, application tasks state and application analysis state with a warning.
With this change, hub is not adding a new terminal state, but having a new terminal state is an easy way to handle things.  The task queries will now evaluate the `state` and `errors` props to determine if "Succeeded" should be "SucceededWithErrors".  This synthetic task status makes updating all of the UI component much simpler.
To function properly, HUB [Issue 725](https://github.com/konveyor/tackle2-hub/issues/725)  / [PR 720](https://github.com/konveyor/tackle2-hub/pull/720) are required.
Changes have also been made to utilize the `/tasks/reports/dashboard` endpoint to get a much smaller view of tasks when dealing with them in …
=> :sparkles: Add handling for tasks "Succeeded with errors" in task and application tables

client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/queries/tasks.ts
Resolves: #2017
The check used to only allow starting an analysis if an application's analysis task is still running
(i.e. not in a terminal state) needs to also consider the frontend synthetic state `SucceededWithErrors` as a non-running / terminal state.
=> :bug: Update task terminal state check to include "SucceededWithErrors"

client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/pages/applications/analysis-wizard/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-3180
- Currently, the set-options screen allows edit of target labels which can be set manually on the Advanced options step or by way of selecting a target card on the target card step. This PR brings the form labels and selectedTarget form values in sync by updating the selected targets to reflect any form label changes in the set options page. This fixes the mta-3180 scenario by causing validation to reflect the now accurate state of the selectedTargets form value. 
https://github.com/user-attachments/assets/d580f857-8236-4e30-bf28-ebd3a4c73792
=> :bug: Address targets falling out of sync after label selection changes

client/src/app/pages/applications/applications-table/applications-table.tsx
Application analysis tasks should be cancellable when the task in NOT in a terminal state.  Use the
`TaskStates.Terminal` collection for the check so all current terminal states are considered.
Resolves: #1993
Resolves: https://issues.redhat.com/browse/MTA-3219
=> :bug: Fix application table `isTaskCancellable`

client/src/app/components/target-card/target-card.css, client/src/app/components/target-card/target-card.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Resolves: #2022
Resolves: #2010
Resolves: #1981
Resolves: #1252
Resolves: https://issues.redhat.com/browse/MTA-3094
Target card behavior and rendering on the target selection step of the analysis wizard and on the custom migrations target page have been updated:
- All of the card contents render inside the card itself (#1981 / MTA-3094)
- When changing the specific label selection for a target, the card selection will not changes (#2010)
- The target label select now sorts the labels in numeric natural sort descending order.  `OpenJDK 21` will be initially selected and appear above `OpenJDK 17` in the select list. (#2022)
- Layouts used on the card have been refactored to use base layouts instead of the `EmptyState` component
- The target label select box has been updated to the current …
=> :bug: Fix target card behavior and rendering

client/public/locales/en/translation.json
Update the tooltip for the priority column to be more descriptive.
Resolves: https://issues.redhat.com/browse/MTA-3235
Follow-up: #2005
=> :bug: Update tooltip text for Task's Priority column

client/src/app/components/simple-document-viewer/SimpleDocumentViewer.tsx
Resolves: #2030
On the Analysis details / Task details page, the log viewer allows downloading of the file being displayed. Set a filename that matches the attachment name when doing the download.
File names used:
- Base log view -> "log-${taskId}"
- Merged log view -> "log-merged-${taskId}"
- Task attachment -> attachment name
Due to the way the `CodeEditor` PF5 component implements the download action, only file extensions of known file types can be used.  Any log or attachment files will have file extensions of `.yaml` or `.json` or `.txt` depending on the detected file type.  File type detection is only using attachment name file extensions currently, and only differentiates between yaml and json with a default to plain text.  For example, given an attachment name, the download file …
=> :bug: Set filenames for task details downloads

client/src/app/pages/applications/applications-table/applications-table.tsx
Fix regression after: https://github.com/konveyor/tackle2-ui/pull/1980
Resolves: https://issues.redhat.com/browse/MTA-1390
Initial filter values work best if the table is not persisting state between reloads (default strategy, component state). If the table uses session or local storage then any existing filter overwrites the default value. From the end user perspective the functionality works only on the first load with a clean browser (no previous state).
Switching to URL filter persistence provides the same functionality and ensures we have only one source of filters.
Reference-Url:  https://github.com/konveyor/tackle2-ui/pull/1698
=> :bug: Persist filters in URL for applications table

client/public/locales/en/translation.json, client/src/app/Constants.ts, client/src/app/api/models.ts, client/src/app/components/RiskLabel.tsx, client/src/app/components/application-assessment-donut-chart/application-assessment-donut-chart.tsx, client/src/app/components/tests/RiskLabel.test.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx, client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx, client/src/app/utils/type-utils.ts, hack/import-questionnaire/assign-risk.yaml
Resolves: https://issues.redhat.com/browse/MTA-2816
Application risk options are one of:
- High (red)
- Medium (yellow)
- Low (green)
- Unknown (unknown)
- Unassessed (unassessed)
Added the __Unassessed__ option to the risk filter list on the application table to have a complete
set of risk filters.
Note: To help test risk levels, the questionnaire `hack/import-questionnaire/assign-risk.yaml` has been added.  The single question has a 1 to 1 mapping between answer and risk level.  As long as that questionnaire is the only one active on the system, it works well to quickly assign risks to applications.
=> :bug: Add application risk filter of "Unassessed"

client/public/locales/en/translation.json, client/src/app/Constants.ts, client/src/app/api/models.ts, client/src/app/components/RiskLabel.tsx, client/src/app/components/application-assessment-donut-chart/application-assessment-donut-chart.tsx, client/src/app/components/tests/RiskLabel.test.tsx, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer.tsx, client/src/app/pages/archetypes/components/archetype-detail-drawer.tsx, client/src/app/pages/reports/components/adoption-candidate-table/adoption-candidate-table.tsx, client/src/app/utils/type-utils.ts, hack/import-questionnaire/assign-risk.yaml
Backport-of: #2032
Resolves: https://issues.redhat.com/browse/MTA-2816
Application risk options are one of:
- High (red)
- Medium (yellow)
- Low (green)
- Unknown (unknown)
- Unassessed (unassessed)
Added the __Unassessed__ option to the risk filter list on the application table to have a complete set of risk filters.
Note: To help test risk levels, the questionnaire
`hack/import-questionnaire/assign-risk.yaml` has been added. The single question has a 1 to 1 mapping between answer and risk level. As long as that questionnaire is the only one active on the system, it works well to quickly assign risks to applications.
=> :bug: [backport release-0.5] Add application risk filter of "Unassessed" (#2032)

client/src/app/pages/applications/applications-table/applications-table.tsx
Backport-of:  (#2033)
Fix regression after: https://github.com/konveyor/tackle2-ui/pull/1980
Resolves: https://issues.redhat.com/browse/MTA-1390
Initial filter values work best if the table is not persisting state between reloads (default strategy, component state). If the table uses session or local storage then any existing filter overwrites the default value. From the end user perspective the functionality works only on the first load with a clean browser (no previous state).
Switching to URL filter persistence provides the same functionality and ensures we have only one source of filters.
Reference-Url:  https://github.com/konveyor/tackle2-ui/pull/1698
=> :bug: [backport release-0.5] Persist filters in URL for applications table (#2033)

common/package.json, package-lock.json, package.json, server/package.json
Resolves: https://issues.redhat.com/browse/MTA-2934
Upgrade the `express` dependency in the server workspace to resolve security issues.
=> :bug: Upgrade `express` dependency

package-lock.json, package.json, server/package.json
Backport-of: #2036
Resolves: https://issues.redhat.com/browse/MTA-2934
Resolve security issues for the `express` dependency across the workspaces and as a dependency of a
dependency.
=> :bug: [backport release-0.2] Upgrade `express` dependency (#2036)

client/src/app/pages/archetypes/components/archetype-form/archetype-form.tsx
Resolves: https://github.com/konveyor/tackle2-ui/issues/1999
=> :bug: Allow creating archetype without tags

client/public/locales/en/translation.json, client/src/app/pages/reports/components/application-landscape/application-landscape.tsx
Resolves: https://issues.redhat.com/browse/MTA-2678
On the reports page, split the combine Unknown / Unassessed landscape chart into separate charts.
Unknown and unassessed are two different risk states.
=> :bug: Split the reports landscape unknown/unassessed chart

.github/workflows/ci-repo.yml
- Setup concurrency on the ci-repo.yml workflow so rapid updates to a PR will have old/pending CI runs just cancel (saving resources)
- Allow the codecov action to upload on any run. This should allow the codecov reports on PRs be accurate based on the current commit on main (or PR target branch)
Fixes: #1820
=> :seedling: ci-repo: concurrency limits, codecov upload

.dockerignore, Dockerfile, package-lock.json, package.json
Upgrade the project to use nodejs-20 in the `Dockerfile`, and package.json engine block.  More specific entries for `.dockerignore` will help keep the `COPY` step quick (especially for local dev image builds).
Reasoning:
- nodejs-18 is in LTS until May 2025, but nodejs-20 will be in LTS until May 2026. [^1]
- node and npm are distributed together, and the `ubi9/nodejs-20` container has a newer version of npm included (10.7.0) than the current `ubi9/nodejs-18` container (10.5.0)
- Given github issues [^2] and [^3], we can assume that the only versions of npm that will be stable in CI during the `npm install` phase are `npm@9` and `npm@>=10.5.2`. Any npm version <10.5.2 is at severe risk of encountering network errors when installing packages, especially when running in a qemu environment …
=> :seedling: Update project to use nodejs 20, npm >=10.5.2

.dockerignore, Dockerfile, package-lock.json, package.json
Upgrade the project to use nodejs-20 in the `Dockerfile`, and package.json engine block. More specific entries for `.dockerignore` will help keep the `COPY` step quick (especially for local dev image builds).
Reasoning:
- nodejs-18 is in LTS until May 2025, but nodejs-20 will be in LTS until May 2026. [^1]
- node and npm are distributed together, and the `ubi9/nodejs-20` container has a newer version of npm included (10.7.0) than the current `ubi9/nodejs-18` container (10.5.0)
- Given github issues [^2] and [^3], we can assume that the only versions of npm that will be stable in CI during the `npm install` phase are `npm@9` and `npm@>=10.5.2`. Any npm version <10.5.2 is at severe risk of encountering network errors when installing packages, especially when running in a qemu environment …
=> :seedling: Update project to use nodejs 20, npm >=10.5.2 (#2062)

client/src/app/components/task-manager/TaskManagerDrawer.tsx
On the task drawer's empty state, remove the "View all tasks" link from the empty state. The link is already available in the task drawer header.
Resolves: https://issues.redhat.com/browse/MTA-3220
=> :bug: Remove extra link from empty task drawer

client/src/app/components/FilterToolbar/FilterToolbar.tsx, client/src/app/components/ToolbarBulkSelector.tsx
Fix applies to bulk selection dropdown and to filter categories dropdown on all table-based screens.
Resolves:  https://issues.redhat.com/browse/MTA-3321
=> :bug:  Close dropdown after selection or click outside the list

hack/wsl/README.md
The WSL docs example curl commands to download the shim scripts needed to be updated follow redirects as necessary and to download to a file instead of writing to sysout.
=> :book: Fix wsl docs curl commands

hack/setup-operator.sh
Update the `setup-operator.sh` script such that the two hub volume sizes can be overridden by env var at script execution time.
=> :ghost: Update setup-operator to include hub volume sizes

common/src/proxies.ts
Related: https://github.com/konveyor/tackle2-hub/pull/750
=> :sparkles: Add /kai reverse-proxy route.

.github/workflows/ci-global.yml, .github/workflows/ci-image-build.yml, .github/workflows/ci-repo.yml
When a PR only contains changes to root level markdown, or anything under `docs/` or `hack/`, there is no need to run the CI github actions.
To satisfy branch protection rules that may exist that require the "unit-test" job to run, the `ci-repo.yml` action looks up details about a PR and will skip the unit test if it detects that the only changes made in the PR are docs or hacks.
The ignores do not apply to pushes to main, pushes to release, or workflow calls.
=> :seedling: Skip PR CI actions for docs/hacks changes

.github/workflows/image-build.yaml
To help out people building images in a fork, use github action variables to be able to configure the target registry and image names.
Now on a fork, the destination of an image build can be set by using action variables[^1]:
- IMAGE_BUILD_REGISTRY (default: "quay.io/konveyor")
- IMAGE_BUILD_IMAGE_NAME (default: "tackle2-ui")
and action secrets[^2]:
- QUAY_PUBLISH_ROBOT
- QUAY_PUBLISH_TOKEN
[^1]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#creating-configuration-variables-for-a-repository
[^2]: https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secret
=> :seedling: Image build, use variables for repo push

client/src/app/components/InfiniteScroller/InfiniteScroller.tsx, client/src/app/components/InfiniteScroller/useVisibilityTracker.tsx, client/src/app/components/task-manager/TaskManagerDrawer.tsx
Fixes:
1. initial delay in first fetch - root cause was delayed initialization of sentinel reference
2. extra page fetch request  - algorithm based on items count was not sufficient 
Reference-Url:  https://github.com/konveyor/tackle2-ui/pull/2049
=> :bug:  Fix fetching in InfiniteScroller

client/src/app/hooks/table-controls/active-item/useActiveItemState.ts, client/src/app/hooks/table-controls/expansion/useExpansionState.ts, client/src/app/hooks/table-controls/filtering/useFilterState.ts, client/src/app/hooks/table-controls/pagination/usePaginationState.ts, client/src/app/hooks/table-controls/sorting/useSortState.ts, client/src/app/hooks/table-controls/types.ts, client/src/app/hooks/table-controls/useTableControlState.ts, client/src/app/hooks/usePersistentState.ts, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-targets.tsx
Changes:
1.  add persistence provider to feature level persistence (IFeaturePersistenceArgs) but not to table layer persistence (ITablePersistenceArgs). This simplifies the provider code (feature-specific providers). 
2. remove meta-persistence target "default" - no target has the same effect.
3. when in persistence provider mode use default values when the deserialized value is nulish. This solves the problem of initialFilterValues being overwritten in target cards scenario (the hook is called more then once and useState() based logic fails to detect initial load).
Using the newly added feature, store the filters selected in the Target step (Analysis wizard) inside react-hook form in the same way as other values. 
Resolves: https://issues.redhat.com/browse/MTA-3438
=> :bug: Support custom serializers in table hooks

client/src/app/pages/controls/stakeholder-groups/stakeholder-groups.tsx
Addition ActionsColumn to  Stakeholder groups table
Relates to https://github.com/konveyor/tackle2-ui/issues/1318
UI tests PR: 1222
=> :sparkles: Update stakeholder groups table to use ActionsColumn

client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/utils/rules-utils.ts
Added filters:
1. by name (freetext search)
2. by custom target (yes/no select)
3. by labels (multiselect)
Resolves: https://issues.redhat.com/browse/MTA-3702
=> :sparkles: Extend filtering in the Set Target step

client/src/app/pages/archetypes/archetypes-page.tsx
**Changes Made:**
- Removed the edit action from the ActionsColumn.
- Added a dedicated edit icon outside the ActionsColumn, providing a clearer and more focused user interface.
Part of #1318 
Before the change:
After the change:
=> :sparkles: Add edit icon with ActionColumns property in the Archetypes table

client/src/app/pages/repositories/Mvn.tsx, client/src/app/queries/cache.ts
Resolves: https://issues.redhat.com/browse/MTA-3699
=> :bug: Disabling useFetchCache query if RWX_SUPPORTED=false

client/src/app/api/rest.ts, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/queries/tasks.ts
Update the backend to implement a bulk cancellation functionality, enabling the cancellation of multiple analyses based on provided IDs in a single request. Modify the existing logic to integrate the new endpoint for handling multiple cancellations simultaneously.
Part of: #2153 
Related to: [tackle2-hub PR #769](https://github.com/konveyor/tackle2-hub/pull/769)
=> :sparkles: Implement bulk analysis cancellation

client/public/locales/en/translation.json, client/src/app/components/Icons/IconedStatus.tsx, client/src/app/pages/applications/components/application-analysis-status.tsx
refactoring code according to comments in issue #2100
these functions are used in the PR there
=> :sparkles:Build presets & map analysis state functions

.github/workflows/ci-global.yml
- actions/upload-artifact@v3 has been deprecated as of April 16, 2024
=> :seedling: Bump actions/upload-artifact@v3 -> v4

.github/workflows/ci-global.yml
With `upload-artifact@v3` deprecated and shut off, move to use the `global-ci-bundle.yml` workflow for global CI. This change drops the need for artifacts and just uses the ttl.sh service. This technique is already being used in a few other Konveyor projects as well.
Ref: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Ref: https://ttl.sh
=> :seedling: Update ci-global.yml use ttl.sh and global-ci-bundle.yml

client/config/jest.config.ts, client/package.json, package-lock.json
Related hub PR:  https://github.com/konveyor/tackle2-hub/pull/780
No breaking changes were observed in our implementation, and login flows remain functional.
=> :seedling: Update keycloak-js to 26.1.0

.github/workflows/ci-repo.yml
We don't have any gating or processes that use the reports that codecov generate on PRs.  Dropping the codecov actions from the `ci-repo.yml` to reduce the noise on PRs.
=> :seedling: Drop codecov from ci

README.md, client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx
Solves [MTA-4630](https://issues.redhat.com/browse/MTA-4630)
=> :bug: Fix questionnaire import row placement issue

.github/workflows/ci-global.yml
A recent change in the UI tests repo [1] changed the basic CI testing suite from `@tier0` to `@ci`. Updating the CI workflow to use the new tier.
[1]: https://github.com/konveyor/tackle-ui-tests/pull/1351
=> :seedling: Update global-ci testing tag to `@ci`

README.md, client/src/app/pages/assessment-management/assessment-settings/assessment-settings-page.tsx
Backport-of: (#2185 )
Resolves [MTA-4630](https://issues.redhat.com/browse/MTA-4630)
=> :bug:  [backport release-0.6] Fix questionnaire import row placement issue (#2185)

.github/workflows/ci-global.yml
Backport of: #2179
Backport of: #2186
With `upload-artifact@v3` deprecated[^1] and shut off, move to use the `global-ci-bundle.yml` workflow for global CI. This change drops the need for artifacts and just uses the ttl.sh service[^2]. This technique is already being used in a few other Konveyor projects as well.
A recent change in the UI tests repo[^3] changed the basic CI testing suite from `@tier0` to `@ci`. Updating the CI workflow to use the new tier.
[^1]: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
[^2]: https://ttl.sh
[^3]: https://github.com/konveyor/tackle-ui-tests/pull/1351
=> :seedling: [backport release-0.6] Update ci-global.yml (#2179)(#2186)

.github/workflows/ci-global.yml
Working from backports #2188 and #2189, updated the `ci-global.yml` workflow to run e2e UI tests on PRs targeting and pushes to the `release-0.6` branch.
The UI tests from from the konveyor-ui-test repo's `release-0.6` branch using the `@ci` test tier.
=> :seedling: Enable e2e UI testing on release-0.6 branch

client/package.json, client/src/app/hooks/table-controls/column/useColumnState.ts, client/src/app/hooks/table-controls/types.ts, client/src/app/hooks/table-controls/useLocalTableControls.ts, client/src/app/hooks/usePersistentState.ts, client/src/app/hooks/useSelectionState/index.ts, client/src/app/hooks/useSelectionState/useSelectionState.test.ts, client/src/app/hooks/useSelectionState/useSelectionState.ts, client/src/app/hooks/useStorage.ts, client/src/app/pages/dependencies/dependencies.tsx, client/src/app/pages/dependencies/dependency-apps-table.tsx, client/src/app/pages/issues/affected-applications/affected-applications.tsx, client/src/app/pages/issues/issue-detail-drawer/file-incidents-detail-modal/file-all-incidents-table.tsx, client/src/app/pages/issues/issue-detail-drawer/issue-affected-files-table.tsx, client/src/app/pages/issues/issues-table.tsx, client/src/app/pages/reports/application-selection-context.tsx, client/src/app/pages/tasks/tasks-page.tsx, package-lock.json
Backport of: #2193
Resolves: #2044
To have direct control over storage and selection
hooks used in the project, pull in the used code
from `@migtools/lib-ui` and drop it as a dependency.
Changes:
- Drop `@migtools/lib-ui` from dependencies
- Pull in hooks useSelectionState() and useStorage()
- Adjust components to use the project's versions of the hooks
Source: https://github.com/migtools/lib-ui
Tag: [v10.0.1](https://github.com/migtools/lib-ui/tree/v10.0.1)
Commit SHA: 0cb74ce6d4de236abe1b7d20bbe747ceca392f28
=> :seedling: [backport release-0.6] Drop use of `@migtools/lib-ui` (#2193)

client/src/app/hooks/selection/useBulkSelection.ts, client/src/app/hooks/table-controls/index.ts, client/src/app/hooks/table-controls/types.ts, client/src/app/hooks/table-controls/useLocalTableControlDerivedState.ts, client/src/app/hooks/table-controls/useLocalTableControls.ts, client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/pages/migration-waves/components/manage-applications-form.tsx, client/src/app/pages/migration-waves/migration-waves.tsx
Resolves: https://issues.redhat.com/browse/MTA-4886
Update the bulk selection hook and component to enable selecting:
- nothing
- the current page of items
- the current set of filtered items (if provided)
- the full set of items (if provided)
Refactor the `getLocalTableControlDerviedState()` function into a react hook, and apply a memo to each derived state function call.  This will keep the item references stable and allow bulk selection to function properly.
The application inventory table passes in enough items such that the bulk selector can provide selection of: none, page, all filtered.
=> :bug: Add "select all filtered" to bulk selection MTA-4886

.github/dependabot.yml
For the npm package checking, update the configs so all patternfly changes are grouped in a single PR and that only minor and patch level changes are considered.  Having dependabot attempt to upgrade a major version number of patternfly will never work.
=> :seedling: Update dependabot configs

client/public/locales/en/translation.json, client/src/app/api/models.ts, client/src/app/pages/controls/tags/components/tag-category-form.tsx, client/src/app/pages/controls/tags/tags.tsx, client/src/mocks/stub-new-work/archetypes.ts
Remove the `rank` field and related UI handling from:
- api models
- tag table
- tag category create/edit form
Resolves: https://issues.redhat.com/browse/MTA-4980
=> :bug: Remove the unused tag category rank field

client/src/app/pages/tasks/tasks-page.tsx
Resolves: https://issues.redhat.com/browse/MTA-4336
Before:
After:
=> :bug: Replace EmptyState with NoDataEmptyState component for consistency

client/src/app/api/rest.ts, client/src/app/pages/applications/applications-table/applications-table.tsx
This PR introduces a new feature allowing users to download multiple analysis details at once.
Resolves: https://github.com/konveyor/tackle2-ui/issues/2143
Demo
[Bulk Analysis Download Demo](https://github.com/user-attachments/assets/7ca66e94-f144-444b-a720-fb874cb8aae5).
=> :sparkles: Bulk download analysis details

client/src/app/pages/applications/applications-table/applications-table.tsx
The actions element has a different ID locator on the Controls pages (Eg: Stakeholder groups, stakeholders etc.) .
So, I'm updating the ID locator for the element in application tables to keep it consistent. This will also help us with automation code maintenance .
=> :seedling: Update ID locator for actions element in application tables

cspell.json
By having a project level cspell dictionary we can avoid words that are spelled project local correctly from being flagged as incorrect.  The dictionary can be updated over time.
vscode extension `streetsidesoftware.code-spell-checker` is recommended to keep spelling in sources nice and clean.
=> :ghost: Add project level cspell dictionary

.husky/pre-commit, package-lock.json, package.json
replaces #2277
Note: The hook scripts no longer use shebangs and don't need to use `npx` to call npm tools.
=> :seedling: Upgrade husky to 9.1.7 and adjust scripts

.github/dependabot.yml, package.json
Change from daily to weekly to reduce disturbance and keep dep updates to Thursdays.
Add more groups to keep some like things together as best as possible.
Have prettier format yaml files under `.github/` via `lint-staged`.
=> :seedling: Dependabot - do weekly checks, group changes

client/src/app/pages/applications/analysis-wizard/__tests__/utils.test.tsx
Add a set of unit tests for `getUpdatedFormLabels()` in the file `client/src/app/pages/applications/analysis-wizard/utils.ts`.  With the refactoring in #2200, we want to make sure the function continues to work the same way.
=> :seedling: add unit tests for `getUpdatedFormLabels`

client/public/locales/en/translation.json, client/src/app/components/target-card/target-card.tsx, client/src/app/pages/applications/analysis-wizard/__tests__/utils.test.tsx, client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx, client/src/app/pages/applications/analysis-wizard/custom-rules.tsx, client/src/app/pages/applications/analysis-wizard/review.tsx, client/src/app/pages/applications/analysis-wizard/schema.ts, client/src/app/pages/applications/analysis-wizard/set-options.tsx, client/src/app/pages/applications/analysis-wizard/set-targets.tsx, client/src/app/pages/applications/analysis-wizard/utils.ts, client/src/app/utils/rules-utils.ts
The wizard form field `formLabels` is confusing and misleading. The field has been renamed `selectedTargetLabels`.  Variables have been renamed as appropriate.
Util function `getUpdatedFormLabels()` changed to `updateSelectedTargetLabels()` and refactored to streamline its functionality.
Pre-work for #2198 
Needs #2325 for unit tests
=> :seedling: Refactor wizard form field name to improve readability

client/src/app/pages/applications/applications-table/applications-table.tsx, client/src/app/queries/tasks.ts
Resolves: https://issues.redhat.com/browse/MTA-5181
Historically and for performance reasons, the application inventory page tried to not always refresh in the background. The approach never really consistently worked, and if hub has a large number of applications, the refresh query logic would almost always run anyway.
The refresh logic has been removed and the page will refresh the applications every 5 seconds.
Performance issues may emerge in a large environment and #2350 was written to capture what is known and have some ideas about how to approach a solution.
=> :bug: always refresh the application query on application inventory

.github/workflows/ci-global.yml
Update the `ci-global.yml` workflow to run e2e UI tests on PRs targeting and pushes to the `release-0.7` branch.  Use the UI tests from from the konveyor-ui-test repo's `release-0.7` branch and the `@ci` test tier.
=> :seedling: Enable e2e UI testing on release-0.7 branch

client/src/app/api/models.ts, client/src/app/components/schema-defined-fields/utils.tsx, client/src/app/pages/applications/application-form/application-form.tsx, client/src/app/pages/applications/generate-assets-wizard/step-capture-parameters.tsx, client/src/app/pages/source-platforms/discover-import-wizard/filter-input-cloudfoundry.tsx, client/src/app/pages/source-platforms/discover-import-wizard/filter-input.tsx, client/src/app/pages/source-platforms/discover-import-wizard/review-input-cloudfoundry.tsx, client/src/app/pages/source-platforms/discover-import-wizard/review.tsx, client/src/app/utils/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-6121
Create a form specifically for cloud foundry discover application filters as the schema currently exists.  The shape and format of the filter document will still be validated against the live schema fetched from the hub.  Any schema changes will require code changes to accommodate.
Starting:
With data:
On review:
=> :bug: Discover application filter input for cloud foundry
